TRD: calibration: Separated calibration methods
AliceO2Group/AliceO2 pull request #10060
Opened 2022-10-12 15:13 UTC by f3sch

This patch separates the future gain from vdexb calibration clearly. As a consequence it introduces a new interface for o2-calibration-trd (renamed) as a generic binary and gives a bare bones structure for gain calibration.
The various classes introduced are subject to change in the future.

One can then select and configure different calibration methods:

1. `--vdexb` and `--enable-root-input-vdexb` for VDrift and ExB calibration
2. `--gain` and `--enable-root-input-gain` for gain calibration

This can easily be extended for other possible calibrations in the future.

Signed-off-by: Felix Schlepper <felix.schlepper@cern.ch>

2022-10-12 15:44 UTC, martenole requested changes
Could you please wait for https://github.com/AliceO2Group/AliceO2/pull/9955 and rebase afterwards since I already changed there the tr-calib-workflow.cxx?
And then I would mark this as WIP. Since you are doing the gain calibration implementation yourself I don't see why we cannot directly add the first version here instead of the empty classes? Maybe not everything you have added here is actually needed (for example some readers/writers). That would give a much cleaner and simpler to review PR

2022-10-12 15:58 UTC, f3sch commented
Aye.

2022-10-12 16:13 UTC, alibuild commented
Error while checking build/O2/o2 for 94e2c1082a947012cbec41c2c02cc28c94cb988f at 2022-10-12 18:13:
```
## sw/BUILD/O2-latest/log
/sw/SOURCES/O2/10060-slc7_x86-64/0/Detectors/TRD/workflow/include/TRDWorkflow/GainCalibSpec.h:96:12: error: 'payloadVec' was not declared in this scope
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/10060/94e2c1082a947012cbec41c2c02cc28c94cb988f/build_O2_o2/pretty.html).

2022-10-12 16:17 UTC, alibuild commented
Error while checking build/O2/o2-dataflow-cs8 for 94e2c1082a947012cbec41c2c02cc28c94cb988f at 2022-10-12 18:17:
```
## sw/BUILD/O2-latest/log
/sw/SOURCES/O2/10060-slc8_x86-64/0/Detectors/TRD/workflow/include/TRDWorkflow/GainCalibSpec.h:96:12: error: 'payloadVec' was not declared in this scope
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/10060/94e2c1082a947012cbec41c2c02cc28c94cb988f/build_O2_o2-dataflow-cs8/pretty.html).

2022-10-12 16:29 UTC, alibuild commented
Error while checking build/O2/o2-dataflow for 94e2c1082a947012cbec41c2c02cc28c94cb988f at 2022-10-12 18:29:
```
## sw/BUILD/O2-latest/log
/sw/SOURCES/O2/10060-slc7_x86-64/0/Detectors/TRD/workflow/include/TRDWorkflow/GainCalibSpec.h:96:12: error: 'payloadVec' was not declared in this scope
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/10060/94e2c1082a947012cbec41c2c02cc28c94cb988f/build_O2_o2-dataflow/pretty.html).

2022-10-12 17:39 UTC, alibuild commented
Error while checking build/AliceO2/O2/o2/macOS for 94e2c1082a947012cbec41c2c02cc28c94cb988f at 2022-10-12 19:39:
```
## sw/BUILD/O2-latest/log
/System/Volumes/Data/build/alice-ci-workdir/o2/sw/SOURCES/O2/10060/0/Detectors/TRD/workflow/include/TRDWorkflow/GainCalibSpec.h:96:12: error: use of undeclared identifier 'payloadVec'
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/10060/94e2c1082a947012cbec41c2c02cc28c94cb988f/build_AliceO2_O2_o2_macOS/pretty.html).

2022-10-14 14:12 UTC, f3sch commented
Closing this since #9955 already introduced the better interface and I am actually not doing the gain calibration after all. This will be now a service task.

2022-10-14 14:12 UTC, closed without merging