[RFC] TRD: adding PID workflow
AliceO2Group/AliceO2 pull request #10501
Opened 2022-12-18 13:01 UTC by f3sch

This introduces a new workflow 'o2-trd-pid-workflow', which provides PID information based currently on ML models using the ONNXRuntime.

Should not get merged before at least the default model is in the ccdb.

2022-12-18 18:45 UTC, shahor02 requested changes

2022-12-18 18:45 UTC, shahor02 commented on Detectors/AOD/src/aod-producer-workflow.cxx
> +    {"disable-trd-pid", o2::framework::VariantType::Bool, true, {"disable trd pid"}},
The default of bool option should be false, please change this to `enable-trd-pid`

2022-12-19 10:15 UTC, martenole reviewed
Some small comments beforehand. Now its better we talk :)

2022-12-19 10:15 UTC, martenole commented on DataFormats/Detectors/TRD/include/DataFormatsTRD/PID.h
> +static const char* PIDPolicyEnum[] = {
I wonder why this is needed. Don't you have the information in the map above?

2022-12-19 10:15 UTC, martenole commented on Detectors/TRD/workflow/src/trd-pid-workflow.cxx
> +  auto maskMatches = GTrackID::getSourcesMask(GTrackID::NONE);
don't you use the maskMatches in the InputHelper?

2022-12-19 10:15 UTC, martenole commented on Detectors/GlobalTrackingWorkflow/helpers/src/InputHelper.cxx
> +  if (maskMatches[GID::TPCTRD]) {
Maybe better to use `maskTracks` instead of `maskMathes`? See comment below

2022-12-19 10:15 UTC, martenole commented on Detectors/TRD/pid/CMakeLists.txt
> +               SOURCES src/ML.cxx
no need for `SOURCES` in each line, only in the first

2022-12-19 10:15 UTC, martenole commented on Detectors/TRD/pid/include/TRDPID/ML.h
> +  PIDValue calculate(const TrackTRD& trkTRD);
Is there a reason to use a template parameter instead of a function one?

2022-12-19 10:15 UTC, martenole commented on Detectors/TRD/pid/macros/ccdbModelUpload.C
> +  metadata["UploadedBy"] = "felix";
Better to use full name + mail address

2022-12-19 10:15 UTC, martenole commented on Detectors/TRD/pid/macros/ccdbModelUpload.C
> +  metadata["default"] = "true"; // tag default objects
Better set to `false`, or adjust time range below (should be 0..infinite for default objects)

2022-12-19 10:15 UTC, martenole commented on Detectors/TRD/pid/src/ML.cxx
> +  // input is [slope0, slope1, ..., slope5, charge0.0, charge0.1, charge0.2, charge1.0, ..., charge5.3, p]
```suggestion
  // input is [slope0, slope1, ..., slope5, charge0.0, charge0.1, charge0.2, charge1.0, ..., charge5.2, p]
```

2022-12-19 10:15 UTC, martenole commented on Detectors/TRD/pid/src/ML.cxx
> +    in[NLAYER + iLayer * 3 + 0] = q0;
I think we have the number of charge windows in our constants

2022-12-19 11:14 UTC, martenole commented
Ok, so as we just discussed it is probably better to add the PID workflow device directly to Detectors/TRD/workflow/src/trd-tracking-workflow.cxx and have it there as an option. The track writer can then optionally also put the vector with PID values into the output.
And it would be good to add a dummy PID workflow (that does not even need to rely on any CCDB object) which just puts -1 for all tracks. Then this could already be enabled in the async reco in case there are problems with the ML model.

2022-12-20 14:16 UTC, closed without merging