Create topology-dictionary routine for ITS3
AliceO2Group/AliceO2 pull request #10874
Opened 2023-03-03 07:53 UTC by lbariogl

All the new classes inherit from ITS2 version.

Main points:
- in the new dictionary format the position of the COG within the bounding box is given in pixels and not in cm. This change is needed because the same topology can be in the inner barrel or in the outher barrel, which have different segemtations.
- `its3::BuildTopologyDictionary` fills the entries of the dictionary with coordinates in pixels.
- In `its3::TopologyDictionary`, the `GetClusterCoordinates` method returns the position of the cluster in cm (conversion is made internally).
-  It was necessaty to make `its3::TopologyDictionary` private data members public, to make them accessible to its3::BuildTopologyDictionary` (different namespace and `itsmft::BuildTopologyDictionary` already present). This is compatible with previous versions of the code
- A macro for creating the dictionaries was added `Detectors/Upgrades/ITS3/macros/test`. It was modulated from the its2 version.

The routine, up to the creation of the ITS3 dictionary, has been tested on simulated Pb-Pb collisions

2023-03-03 10:29 UTC, fgrosa requested changes
Ciao @lbariogl thanks a lot for the work!
The only comment I have is that the cast from `o2::itsmft::TopologyDictionary` to `o2::its3::TopologyDictionary` should be fixed in the `TrackerSpec` (otherwise I fear that the vertexer would not work anymore) and in the `CheckClusters.C` macro, which makes fail the tests otherwise.

2023-03-03 10:29 UTC, fgrosa commented on Detectors/Upgrades/ITS3/workflow/include/ITS3Workflow/TrackerSpec.h
> +  void setClusterDictionary(const o2::itsmft::TopologyDictionary* d) { mDict = static_cast<const o2::its3::TopologyDictionary*>(d); } // TODO: remove casting from Run3 to RUn2 dictionary
This is needed for the vertexer, which is currently working. Could you please adapt it?

2023-03-03 16:01 UTC, lbariogl commented
Hi @fgrosa, you are right and I have implemented your suggestions. I have also solved the problem with the test of `CreateDictionariesITS3.C` (or at least when testin macros also in local, let's se here). Perhaps it is better to test the full chain (including vertexing and tracking) in local before merging the PR and eventually uploading a `its3::TopologyDictionary` object to the CCDB. I can mark the PR as WIP in case.

2023-03-03 17:34 UTC, fgrosa submitted a review, later dismissed

2023-03-06 09:16 UTC, lbariogl commented
Hi @fgrosa @mconcas, I have tested the changes using `CheckClustersITS3.C` and the results (in attachment) look reasonable.

[it3clusters_dx_vs_dz.pdf](https://github.com/AliceO2Group/AliceO2/files/10896274/it3clusters_dx_vs_dz.pdf)
[it3clusters_y_vs_x_vs_z.pdf](https://github.com/AliceO2Group/AliceO2/files/10896276/it3clusters_y_vs_x_vs_z.pdf)

2023-03-06 09:24 UTC, fgrosa approved these changes

2023-03-06 16:19 UTC, alibuild commented
Error while checking build/O2/fullCI for f48d4fedfbfe980ddc37657ddece4a287c82637a at 2023-03-06 17:19:
```
## sw/BUILD/o2checkcode-latest/log
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/Common/test/testGPUsortCUDA.cu:22:10: error: 'boost/test/unit_test.hpp' file not found [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:696:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:709:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUTracking/TRDTracking/GPUTRDTracker.cxx:37:10: error: 'omp.h' file not found [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUTracking/Base/GPUReconstruction.cxx:37:10: error: 'omp.h' file not found [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUTracking/Base/GPUReconstructionCPU.cxx:45:10: error: 'omp.h' file not found [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUTracking/display/GPUDisplay.cxx:36:10: error: 'omp.h' file not found [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUTracking/Base/cuda/GPUReconstructionCUDAGenRTC.cu:16:10: error: 'omp.h' file not found [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:696:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:709:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/cuda/../Shared/Utils.h:26:10: error: 'boost/program_options.hpp' file not found [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:696:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:709:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/cuda/../Shared/Utils.h:26:10: error: 'boost/program_options.hpp' file not found [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:696:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:709:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/Framework/Logger/include/Framework/Logger.h:14:10: error: 'fairlogger/Logger.h' file not found [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:696:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:709:13: error: no template named 'texture' [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:520:12: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:1059:69: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:1175:5: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:1852:16: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:2276:18: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:4336:16: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/sm_20_atomic_functions.h:103:39: error: redefinition of 'atomicAdd' [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/Framework/Logger/include/Framework/Logger.h:14:10: error: 'fairlogger/Logger.h' file not found [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:696:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:709:13: error: no template named 'texture' [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:520:12: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:1059:69: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:1175:5: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:1852:16: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:2276:18: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:4336:16: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/sm_20_atomic_functions.h:103:39: error: redefinition of 'atomicAdd' [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/hip/../Shared/Utils.h:146:34: error: use of undeclared identifier 'int4'; did you mean 'int'? [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/hip/benchmark.hip.cxx:199:35: error: use of undeclared identifier 'int4'; did you mean 'int'? [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/hip/../Shared/Utils.h:146:34: error: use of undeclared identifier 'int4'; did you mean 'int'? [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:64:8: error: unknown type name '__host__' [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:64:27: error: expected ';' after top level declarator [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:64:33: error: overloaded 'operator+=' must have at least one parameter of class or enumeration type [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:64:44: error: unknown type name 'int4'; did you mean 'int'? [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:64:53: error: unknown type name 'int4'; did you mean 'int'? [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:66:4: error: member reference base type 'int' is not a structure or union [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:66:11: error: member reference base type 'int' is not a structure or union [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:67:4: error: member reference base type 'int' is not a structure or union [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:67:11: error: member reference base type 'int' is not a structure or union [clang-diagnostic-error]
/sw/SOURCES/O2/10874-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:68:4: error: member ref [...]

2023-03-08 10:20 UTC, mconcas approved these changes
Seems fine for the ITS part

2023-03-08 10:20 UTC, merged