[ITS3]: Add a file to customize material budget LUT input for ITS3 IB
AliceO2Group/AliceO2 pull request #10892
Opened 2023-03-06 05:19 UTC by ChunzhengLab

2023-03-06 08:37 UTC, fgrosa requested changes
Hi @ChunzhengLab thanks a lot for the work! I only have one comment, see below

2023-03-06 08:37 UTC, fgrosa commented on Detectors/Upgrades/ITS3/macros/test/buildMatBudLUT.C
> +  lrData.emplace_back(LrData(lrData.back().rMax, lrData.back().rMax + drStepChip4Layer, zSpanH, zBin, rphiBin));
Maybe we can have an argument that allows us to turn on/off the addition of the 4th layer to have the possibility to build the LUT both for the 3-layer and the 4-layer versions

2023-03-06 15:45 UTC, ChunzhengLab commented on Detectors/Upgrades/ITS3/macros/test/buildMatBudLUT.C
> +  lrData.emplace_back(LrData(lrData.back().rMax, lrData.back().rMax + drStepChip4Layer, zSpanH, zBin, rphiBin));
Many thanks!
With your method, it is now able to automatically determine configure with the 3-layer or the 4-layer version based on the read-in geometry.

2023-03-06 16:17 UTC, fgrosa submitted a review, later dismissed

2023-03-07 00:31 UTC, alibuild commented
Error while checking build/O2/fullCI for 4f36100ddd47437f3b8838ed9dddcb110d54e5a6 at 2023-03-07 01:31:
```
## sw/BUILD/o2checkcode-latest/log
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/Common/test/testGPUsortCUDA.cu:22:10: error: 'boost/test/unit_test.hpp' file not found [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:696:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:709:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUTracking/TRDTracking/GPUTRDTracker.cxx:37:10: error: 'omp.h' file not found [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUTracking/Base/GPUReconstruction.cxx:37:10: error: 'omp.h' file not found [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUTracking/Base/GPUReconstructionCPU.cxx:45:10: error: 'omp.h' file not found [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUTracking/display/GPUDisplay.cxx:36:10: error: 'omp.h' file not found [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUTracking/Base/cuda/GPUReconstructionCUDAGenRTC.cu:16:10: error: 'omp.h' file not found [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:696:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:709:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/cuda/../Shared/Utils.h:26:10: error: 'boost/program_options.hpp' file not found [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:696:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:709:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/cuda/../Shared/Utils.h:26:10: error: 'boost/program_options.hpp' file not found [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:696:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:709:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/Framework/Logger/include/Framework/Logger.h:14:10: error: 'fairlogger/Logger.h' file not found [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:696:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:709:13: error: no template named 'texture' [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:520:12: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:1059:69: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:1175:5: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:1852:16: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:2276:18: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:4336:16: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/sm_20_atomic_functions.h:103:39: error: redefinition of 'atomicAdd' [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/Framework/Logger/include/Framework/Logger.h:14:10: error: 'fairlogger/Logger.h' file not found [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:696:13: error: no template named 'texture' [clang-diagnostic-error]
/sw/slc8_x86-64/o2codechecker/v15.0-local2/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:709:13: error: no template named 'texture' [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:520:12: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:1059:69: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:1175:5: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:1852:16: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:2276:18: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/cuda/std/detail/libcxx/include/type_traits:4336:16: error: CUDA device code does not support variadic functions [clang-diagnostic-error]
/usr/local/cuda-12.0/include/sm_20_atomic_functions.h:103:39: error: redefinition of 'atomicAdd' [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/hip/../Shared/Utils.h:146:34: error: use of undeclared identifier 'int4'; did you mean 'int'? [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:64:8: error: unknown type name '__host__' [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:64:27: error: expected ';' after top level declarator [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:64:33: error: overloaded 'operator+=' must have at least one parameter of class or enumeration type [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:64:44: error: unknown type name 'int4'; did you mean 'int'? [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:64:53: error: unknown type name 'int4'; did you mean 'int'? [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:66:4: error: member reference base type 'int' is not a structure or union [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:66:11: error: member reference base type 'int' is not a structure or union [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:67:4: error: member reference base type 'int' is not a structure or union [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:67:11: error: member reference base type 'int' is not a structure or union [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:68:4: error: member reference base type 'int' is not a structure or union [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:68:11: error: member reference base type 'int' is not a structure or union [clang-diagnostic-error]
/sw/SOURCES/O2/10892-slc8_x86-64/0/GPU/GPUbenchmark/hip/Kernels.hip.cxx:69:4: error: member re [...]

2023-03-08 20:50 UTC, alibuild commented
Error while checking build/O2/fullCI for 64f745a9d066b450aac98cc4d7c2c07443c7fc0c at 2023-03-08 21:50:
```
## sw/BUILD/O2-full-system-test-latest/log
Detected critical problem in logfile qedsim.log
qedsim.log-[20:50:29][FATAL] TGrid::Connect returned nullptr. May be due to missing alien token
[ERROR] SHUTTING DOWN DUE TO SIGNALED EXIT IN COMPONENT 396
/usr/include/features.h:18:2: error: unterminated conditional directive
Error in <TInterpreter::AutoParse>: Error parsing payload code for class o2::eventgen::QEDGenParam with content:
/sw/slc8_x86-64/O2/10892-slc8_x86-64-local1/share/Generators/external/QEDepem.C:19:34: error: incomplete type 'o2::eventgen::QEDGenParam' named in nested name specifier
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/variant:1886:34: error: temporary of type '__hash_enum<unsigned long>' has private destructor
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/variant:1886:34: error: no matching constructor for initialization of '__hash_enum<unsigned long>'
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/variant:1889:34: error: temporary of type '__hash_enum<unsigned long>' has private destructor
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/variant:1889:34: error: no matching constructor for initialization of '__hash_enum<unsigned long>'
/sw/slc8_x86-64/pythia/v8304-42/include/Pythia8/TimeShower.h:188:14: error: member reference type 'unordered_map<string, double>::iterator' (aka '_Node_iterator<std::pair<const std::__cxx11::basic_string<char>, double>, __constant_iterators::value, __hash_cached::value>') is not a pointer; did you mean to use '.'?
/sw/slc8_x86-64/pythia/v8304-42/include/Pythia8/TimeShower.h:188:16: error: no member named 'second' in 'std::__detail::_Node_iterator<std::pair<const std::__cxx11::basic_string<char>, double>, false, true>'
/sw/slc8_x86-64/pythia/v8304-42/include/Pythia8/MultipartonInteractions.h:201:25: error: cannot increment value of type 'map<int, int>::iterator' (aka '_Rb_tree_iterator<std::pair<const int, int> >')
/sw/slc8_x86-64/pythia/v8304-42/include/Pythia8/MultipartonInteractions.h:201:37: error: member reference type 'map<int, int>::iterator' (aka '_Rb_tree_iterator<std::pair<const int, int> >') is not a pointer; did you mean to use '.'?
/sw/slc8_x86-64/pythia/v8304-42/include/Pythia8/MultipartonInteractions.h:201:39: error: no member named 'second' in 'std::_Rb_tree_iterator<std::pair<const int, int> >'
/sw/slc8_x86-64/pythia/v8304-42/include/Pythia8/SpaceShower.h:153:14: error: member reference type 'unordered_map<string, double>::iterator' (aka '_Node_iterator<std::pair<const std::__cxx11::basic_string<char>, double>, __constant_iterators::value, __hash_cached::value>') is not a pointer; did you mean to use '.'?
/sw/slc8_x86-64/pythia/v8304-42/include/Pythia8/SpaceShower.h:153:16: error: no member named 'second' in 'std::__detail::_Node_iterator<std::pair<const std::__cxx11::basic_string<char>, double>, false, true>'
/sw/slc8_x86-64/pythia/v8304-42/include/Pythia8/LowEnergySigma.h:21:7: error: implicit default constructor for 'Pythia8::LowEnergySigma' must explicitly initialize the member 'sigRes' which does not have a default constructor
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/stl_vector.h:1601:39: error: no member named '_M_start' in 'std::_Vector_base<TParticle, std::allocator<TParticle> >::_Vector_impl'
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/stl_vector.h:1930:36: error: no member named '_M_finish' in 'std::_Vector_base<TParticle, std::allocator<TParticle> >::_Vector_impl'
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/new_allocator.h:175:23: error: no matching constructor for initialization of 'std::pair<const std::__cxx11::basic_string<char>, std::shared_ptr<Pythia8::Plugin> >'
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/new_allocator.h:175:23: error: no matching constructor for initialization of 'std::pair<const int, std::vector<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > > >'
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/new_allocator.h:175:23: error: no matching constructor for initialization of 'std::pair<const std::__cxx11::basic_string<char>, Pythia8::Flag>'
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/new_allocator.h:175:23: error: no matching constructor for initialization of 'std::pair<const std::__cxx11::basic_string<char>, Pythia8::Mode>'
Error in <TInterpreter::AutoParse>: Error parsing payload code for class o2::eventgen::InteractionDiamondParam with content:
/sw/slc8_x86-64/O2/10892-slc8_x86-64-local1/share/Generators/external/QEDepem.C:20:33: error: incomplete type 'o2::eventgen::InteractionDiamondParam' named in nested name specifier
Error in <TInterpreter::AutoParse>: Error parsing payload code for class TGenEpEmv1 with content:
/sw/slc8_x86-64/O2/10892-slc8_x86-64-local1/share/Generators/external/QEDepem.C:28:20: error: allocation of incomplete type 'TGenEpEmv1'
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/variant:1886:34: error: temporary of type '__hash_enum<unsigned long>' has private destructor
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/variant:1886:34: error: no matching constructor for initialization of '__hash_enum<unsigned long>'
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/variant:1889:34: error: temporary of type '__hash_enum<unsigned long>' has private destructor
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/variant:1889:34: error: no matching constructor for initialization of '__hash_enum<unsigned long>'
/sw/slc8_x86-64/pythia/v8304-42/include/Pythia8/Weights.h:367:43: error: call to implicitly-deleted default constructor of 'Pythia8::WeightsSimpleShower'
Error in <TGeoCompositeShape::MakeNode>: Expression has no boolean operation
Error in <TGeoCompositeShape::ctor>: Composite halfFixationToPipe: cannot parse expression: pipeSupportTubeCarbon
/usr/include/features.h:18:2: error: unterminated conditional directive
Error in <TInterpreter::AutoParse>: Error parsing payload code for class TJAlien with content:
Error in <TClass::LoadClassInfo>: no interpreter information for class TJAlien is available even though it has a TClass initialization routine.
Error in <TPluginHandler::SetupCallEnv>: method TJAlien not found in class TJAlien
[20:50:29][FATAL] TGrid::Connect returned nullptr. May be due to missing alien token


## sw/BUILD/o2checkcode-latest/log
--
========== List of errors found ==========
--
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/10892/64f745a9d066b450aac98cc4d7c2c07443c7fc0c/build_O2_fullCI/pretty.html).

2023-03-17 17:16 UTC, mconcas approved these changes

2023-03-17 17:17 UTC, merged