TPC QC: adds IDCvsSACZero Task
AliceO2Group/AliceO2 pull request #10915
Opened 2023-03-07 16:49 UTC by sbhawani

2023-03-09 21:04 UTC, wiechula requested changes
Just minor things. In the QC meeting we also discussed to add ratio histograms. Please check with @bulukutlu

2023-03-09 21:04 UTC, wiechula commented on Detectors/TPC/qc/include/TPCQC/IDCsVsSACs.h
> +#include "TPCCalibration/IDCContainer.h"
```suggestion
```

2023-03-09 21:04 UTC, wiechula commented on Detectors/TPC/qc/include/TPCQC/IDCsVsSACs.h
> +class SACCCDBHelper;
```suggestion
class TCanvas;

namespace o2::tpc {
template <class>
class IDCCCDBHelper;

template <class>
class SACCCDBHelper;
}

```

2023-03-09 21:04 UTC, wiechula commented on Detectors/TPC/qc/include/TPCQC/IDCsVsSACs.h
> +#include "TCanvas.h"
```suggestion
#include <string>
```

2023-03-09 21:04 UTC, wiechula commented on Detectors/TPC/qc/src/IDCsVsSACs.cxx
> +#include "TPCCalibration/IDCContainer.h"
```suggestion
#include "TPCCalibration/IDCContainer.h"
```

2023-03-09 21:04 UTC, wiechula commented on Detectors/TPC/qc/src/IDCsVsSACs.cxx
> +#include "TPCCalibration/IDCCCDBHelper.h"
```suggestion
#include "TPCCalibration/IDCCCDBHelper.h"
#include "TPCCalibration/SACCCDBHelper.h"
```

2023-03-09 21:04 UTC, wiechula commented on Detectors/TPC/qc/src/IDCsVsSACs.cxx
> +#include "TProfile.h"
Please remove unneded headers

2023-03-09 21:04 UTC, wiechula commented on Detectors/TPC/qc/src/IDCsVsSACs.cxx
> +  std::string SACname = "SAC0";
```suggestion
  const std::string SACname = "SAC0";
```

2023-03-09 21:04 UTC, wiechula commented on Detectors/TPC/qc/src/IDCsVsSACs.cxx
> +  // drawSectorsXY(Side::A);
Why did you remove it?

2023-04-12 07:39 UTC, wiechula approved these changes

2023-04-12 07:39 UTC, wiechula commented on Detectors/TPC/qc/include/TPCQC/IDCsVsSACs.h
> +// namespace o2::tpc
```suggestion

```

2023-04-19 10:02 UTC, sbhawani commented
Hi, can this be merged? thanks

2023-04-19 10:58 UTC, merged