MCH: rename output of error merger to avoid duplicate name
AliceO2Group/AliceO2 pull request #10995
Opened 2023-03-22 17:11 UTC by aphecetche

Otherwise MCH/ERROR/0 is used both by the error merger and the data decoder(s).

2023-03-22 17:19 UTC, martenole submitted a review, later dismissed
Thanks! One of the possible errors caught by https://github.com/AliceO2Group/AliceO2/pull/10970 :)

2023-03-22 17:22 UTC, pillot requested changes
You must also change the corresponding reader and writer
Please also update the readme
Note that this will break the current QC async in DPL, unless you deactivate it first.

2023-03-22 17:40 UTC, pillot commented on Detectors/MUON/MCH/Workflow/README.md
There is one more, for the merger actually ;-)

2023-03-22 17:51 UTC, pillot approved these changes

2023-03-22 20:55 UTC, alibuild commented
Error while checking build/O2/fullCI for f9cc052c1f78691ee2c20bcb1df88a658fc0b1d7 at 2023-03-22 21:55:
```
## sw/BUILD/O2-full-system-test-latest/log
./sim-challenge.log[ERROR] invalid workflow in o2-mch-reco-workflow: No matching output found for MCH/ERRORS/0 as requested by data processor "mch-error-writer". Candidates:
./digi.log[ERROR] Found duplicate input binding collisioncontext
./digi.log[ERROR] Found duplicate input binding collisioncontext
./digi.log[ERROR] Found duplicate input binding collisioncontext
./digi.log[ERROR] Found duplicate input binding collisioncontext
./digi.log[ERROR] Found duplicate input binding collisioncontext
./digi.log[ERROR] Found duplicate input binding collisioncontext
./digi.log[ERROR] Found duplicate input binding collisioncontext
./digi.log[ERROR] Found duplicate input binding collisioncontext
./digi.log[ERROR] Found duplicate input binding collisioncontext
./digi.log[ERROR] Found duplicate input binding collisioncontext
./digi.log[ERROR] Found duplicate input binding collisioncontext
./digi.log[26335:FT0Digitizer]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26335:FT0Digitizer]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26335:FT0Digitizer]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26335:FT0Digitizer]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26335:FT0Digitizer]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26335:FT0Digitizer]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26335:FT0Digitizer]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26335:FT0Digitizer]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26335:FT0Digitizer]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26335:FT0Digitizer]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26335:FT0Digitizer]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26346:TRAP]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26346:TRAP]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26346:TRAP]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26346:TRAP]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26346:TRAP]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26346:TRAP]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26346:TRAP]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26346:TRAP]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26346:TRAP]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26346:TRAP]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26346:TRAP]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26345:TPCDigitizer_7]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26345:TPCDigitizer_7]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26345:TPCDigitizer_7]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26345:TPCDigitizer_7]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26345:TPCDigitizer_7]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26345:TPCDigitizer_7]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26345:TPCDigitizer_7]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26345:TPCDigitizer_7]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26345:TPCDigitizer_7]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26345:TPCDigitizer_7]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26345:TPCDigitizer_7]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26347:TRD-tracklet-writer]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26347:TRD-tracklet-writer]: [ERROR] Found duplicate input binding collisioncontext
./digi.log[26347:TRD-tracklet-writer]: [ERROR] Found duplicate input binding collisioncontext
[0 more errors; see full log]
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/10995/f9cc052c1f78691ee2c20bcb1df88a658fc0b1d7/build_O2_fullCI/pretty.html).

2023-03-23 15:51 UTC, martenole commented
Errors look unrelated to me. Shall I merge this?

2023-03-27 10:17 UTC, aphecetche commented
@martenole yes, could be merged IMO

2023-03-27 10:36 UTC, merged