[EMCAL-565, EMCAL-566]: Add start stop functionality to EMCal calib
AliceO2Group/AliceO2 pull request #11111
Opened 2023-04-05 07:19 UTC by jokonig

- Data close to the end of run, or runs that dont have enough events to trigger the calibration, were neglected until now and the data was dropped
- Now, the data is saved at the end of run and loaded in the next run to continue the calibration and to not neglect data that was already recorded
- To store the data, boost histograms are converted to root histograms and for the reading of the histograms its vice-versa. Therefore, the boost histograms have to have variable axes instead of integer axes
- For longer stops, one does not always want to load the old data. Therefore, the parameter setSavedSlotAllowedSOR_EMC in the calib params can be used to avoid loading the old parameters at the SOR.
- To disable the procedure completely, setSavedSlotAllowed_EMC has to be set to false

2023-04-08 12:15 UTC, shahor02 requested changes

2023-04-08 12:15 UTC, shahor02 commented on Detectors/EMCAL/calibration/include/EMCALCalibration/EMCALChannelCalibrator.h
> +  bool getSaveAtEOR() { return mSaveAtEOR; }
const method

2023-04-08 12:15 UTC, shahor02 commented on Detectors/EMCAL/calibration/include/EMCALCalibration/EMCALChannelCalibrator.h
> +  bool getLoadAtSOR() { return mLoadAtSOR; }
const method

2023-04-08 12:15 UTC, shahor02 commented on Detectors/EMCAL/calibration/testWorkflow/EMCALChannelCalibratorSpec.h
> +
Could you make this compatible with ECS stop/start procedure (i.e. starting a new run within the same O2 session, see https://indico.cern.ch/event/1270050/contributions/5335478/attachments/2620040/4530862/EOS_and_SSS.pdf)

2023-04-11 13:12 UTC, jokonig commented on Detectors/EMCAL/calibration/testWorkflow/EMCALChannelCalibratorSpec.h
> +
@shahor02 Are you refering to the TimingInfo::globalRunNumberChanged variable? Is this also needed in case that the accumulation should just continue in the case of the start-stop-start procedure? 
Because for the EMCal we discussed internally that the calibration should not be sensitive to run changes and hence the calibration can just continue with the exact same settings and therefore no new initialization is needed. But maybe I am missing something here.

2023-04-11 14:33 UTC, shahor02 commented on Detectors/EMCAL/calibration/testWorkflow/EMCALChannelCalibratorSpec.h
> +
Yes, I was referring to the TimingInfo::globalRunNumberChanged. If you are filling just a single slot and don't need to take any action at EOR/SOR, then you don't need to implement it.
But I see that you have SaveAtEOR and EndOfStream processing, they will be invoked at the EOR (between stop/start), are you going to ignore their results?

2023-04-12 15:03 UTC, jokonig commented on Detectors/EMCAL/calibration/testWorkflow/EMCALChannelCalibratorSpec.h
> +
Hi @shahor02 I discussed with Markus and we concluded the following:
- We want to save the calibration histograms at each end of run, also at the start-stop-start. If the start-stop-start procedure is executed, it would not be necessary to store these objects as the calibration just continues. And we also dont read in the histograms as the fisrtcall should still be set to false. If then the new runs stops, these histograms will be overwritten by the ones accumulated in the new run. SO yes, we are ignoring the objects in case of the start-stop-start procedure.
-  For "normal" runs where no start-stop-start was executed, it should store the calib histograms at the end of run. In the next run where we also call the SOR they should be read in and the calibration can continue
So we think that the implementation as it is now should be sufficient for this.

2023-04-14 09:04 UTC, jokonig commented on Detectors/EMCAL/calibration/include/EMCALCalibration/EMCALChannelCalibrator.h
> +  bool getLoadAtSOR() { return mLoadAtSOR; }
done

2023-04-14 09:04 UTC, jokonig commented on Detectors/EMCAL/calibration/include/EMCALCalibration/EMCALChannelCalibrator.h
> +  bool getSaveAtEOR() { return mSaveAtEOR; }
done

2023-04-17 13:46 UTC, jokonig commented
@shahor02 could you have a look if this can be merged now?

2023-04-17 14:43 UTC, shahor02 approved these changes

2023-04-17 14:43 UTC, merged