[EMCAL-562] EMCAL/DCAL STU Decoder
AliceO2Group/AliceO2 pull request #11246
Opened 2023-04-27 14:20 UTC by mpoghos

2023-04-27 15:47 UTC, mfasDa requested changes
In addition to dedicated code remarks nearly all std::couts need to be replaced by LOG(DEBUG) or lower level.

2023-04-27 15:47 UTC, mfasDa commented on Detectors/EMCAL/reconstruction/include/EMCALReconstruction/StuDecoder.h
> +  void decodeFastOrADC(const uint32_t* buffer);
Buffer should be passed as `const gsl::span<const uint32_t>`

2023-04-27 15:47 UTC, mfasDa commented on Detectors/EMCAL/reconstruction/include/EMCALReconstruction/StuDecoder.h
> +  std::vector<int16_t> getFastOrADCs() const { return mFastOrADC; }
Return type should be `gsl::span<const int16>`. Do we really expect the indices to be signed?

2023-04-27 15:47 UTC, mfasDa commented on Detectors/EMCAL/reconstruction/include/EMCALReconstruction/StuDecoder.h
> +  int16_t getFastOrADC(int iTRU, int iCh) const { return mFastOrADC[iTRU + getNumberOfTRUs() * iCh]; }
Use std::size_t for index in order to prevent access with negative indices. What happens if index >  size?

2023-04-27 15:47 UTC, mfasDa commented on Detectors/EMCAL/reconstruction/src/StuDecoder.cxx
> +  unsigned short gammaLow[nTRU][TRUparam::NchannelsOverPhi];
Since the functions return non-const the const here is effectively a lie. The array creation results in undefined behaviour. A std::vector must be used instead. In any case for arrays please use std::array instead of c-arrays.

2023-04-27 15:47 UTC, mfasDa commented on Detectors/EMCAL/reconstruction/src/StuDecoder.cxx
> +}
Ideally one would put the configuration in a struct, create a streaming operator (operator<<) for the struct (where I usually add a function printStream that is called by the streaming operator). Like that the dumpSTUcfg could make use of that, but other streams as well.

2023-04-27 15:47 UTC, mfasDa commented on Detectors/EMCAL/reconstruction/src/StuDecoder.cxx
> +  unsigned short gammaLow[nTRU][TRUparam::NchannelsOverPhi];
Furthermore, if they are intended to serve as bitsets, use std::bitset instead.

2023-04-27 15:47 UTC, mfasDa commented on Detectors/EMCAL/reconstruction/src/StuDecoder.cxx
> +    uint32_t row_JetLow = buffer[ix + offset];
Also those two I assume are bitsets in reality ...

2023-04-27 15:47 UTC, mfasDa commented on Detectors/EMCAL/reconstruction/include/EMCALReconstruction/StuDecoder.h
> +  std::vector<int16_t> mL1GammaLowPatchIndex;
Only from the code one realises that this a bitset which is absolutely confusing. I recommend using bitfields as used in various places, i.e. https://github.com/AliceO2Group/AliceO2/blob/dev/Detectors/EMCAL/base/include/EMCALBase/RCUTrailer.h

An implementation would be 
```c++
struct GammaPatchIndex {
  union {
    uint16_t mDataWord;
    struct {
       uint16_t mPhiIndex: 5;
       uint16_t mEtaIndex: 5;
       uint16_t mTRUindex: 5;
    };
  };
};
```
... and then:
``` c++
std::vector<GammaPatchIndex> mGammaHighPatchIndex;
```

Similar for jet patch indices.

2023-04-27 15:47 UTC, mfasDa commented on Detectors/EMCAL/reconstruction/src/StuDecoder.cxx
> +void StuDecoder::decodeL1GammaPatchIndices(const uint32_t* buffer)
In the way I see in the code buffer is a sequence of 32 bit words with 4 8 bit words, a struct can be defined as

```c++
struct GammaPatchWord{
  union {
    uint32_t mData;
    struct {
       uint32_t mWord3: 8;
       uint32_t mWord2: 8;
       uint32_t mWord1: 8;
       uint32_t mWord0: 8;
    };
  };
};
```
See particularly as exampled how the different word types are defined for ITSMFT https://github.com/AliceO2Group/AliceO2/blob/dev/Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/GBTWord.h and adapted in a similar way for FOCAL https://github.com/AliceO2Group/AliceO2/blob/dev/Detectors/FOCAL/reconstruction/include/FOCALReconstruction/PadWord.h

you would call the function via
```c++
decodeL1GammaPatchIndices(gsl::span<const GammaPatchWord>(reinterpret_cast<const GammaPatchWord *>(buffer + first, nwords)));
```

2023-04-27 23:07 UTC, alibuild commented
Error while checking build/O2/fullCI for 4a089e59f11dec34ce1adc4e40835c98e6c238ba at 2023-04-28 01:07:
```
## sw/BUILD/o2checkcode-latest/log
--
++ echo '========== List of errors found =========='
========== List of errors found ==========
++ GRERR=0
++ grep -v clang-diagnostic-error error-log.txt
++ grep ' error:'
/sw/SOURCES/O2/11246-slc8_x86-64/0/Detectors/EMCAL/reconstruction/src/StuDecoder.cxx:46:13: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11246-slc8_x86-64/0/Detectors/EMCAL/reconstruction/src/StuDecoder.cxx:106:24: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11246-slc8_x86-64/0/Detectors/EMCAL/reconstruction/src/StuDecoder.cxx:122:37: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11246-slc8_x86-64/0/Detectors/EMCAL/reconstruction/src/StuDecoder.cxx:124:37: error: statement should be inside braces [readability-braces-around-statements]
++ [[ 0 == 0 ]]
++ exit 1
--
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/11246/4a089e59f11dec34ce1adc4e40835c98e6c238ba/build_O2_fullCI/pretty.html).

2023-12-08 08:18 UTC, davidrohr commented
@mfasDa @mpoghos : what is the status of this PR? It is stall for quite some time. Is it still needed? Should it be merged?

2023-12-08 08:19 UTC, mfasDa commented
@davidrohr yes, please merge!

2023-12-08 08:20 UTC, merged