Add FOCAL to rawTF reader
AliceO2Group/AliceO2 pull request #11293
Opened 2023-05-06 13:09 UTC by mfasDa

2023-05-07 18:50 UTC, shahor02 reviewed
I would avoid requiring Focal by default in the raw reader. You may have it allowed, but then the default should be not 'all' but 'all'-FOC

2023-05-08 11:14 UTC, mfasDa commented
this formatting clash gets really annoying ...

2023-05-09 08:57 UTC, mfasDa commented
Re-formatted with ancient clang-format-13, now formatting checks pass. Incredible.

2023-05-09 13:09 UTC, shahor02 requested changes

2023-05-09 13:09 UTC, shahor02 commented on Detectors/Raw/TFReaderDD/src/tf-reader-workflow.cxx
> +  options.push_back(ConfigParamSpec{"onlyDet", VariantType::String, "all-FOC", {"list of dectors"}});
this will not work, the all-FOC should be implemented as: 
```
o2::detectors::DetID::getMask("all") & ~o2::detectors::DetID::getMask("FOC")
```

2023-05-09 13:33 UTC, mfasDa commented
Withdrawing PR

2023-05-09 13:33 UTC, closed without merging