Anglerecon
AliceO2Group/AliceO2 pull request #11400
Opened 2023-05-29 14:45 UTC by gvolpe79

2023-05-30 08:19 UTC, shahor02 requested changes

2023-05-30 08:19 UTC, shahor02 commented on DataFormats/Reconstruction/include/ReconstructionDataFormats/MatchInfoHMP.h
> +  float mPhotCharge[10];
init array as `float mPhotCharge[10] = {};`

2023-05-30 08:19 UTC, shahor02 commented on DataFormats/Reconstruction/include/ReconstructionDataFormats/TrackHMP.h
> +  ClassDef(TrackHMP, 0) // HMPID reconstructed tracks
0 has a special meaning, start from 1

2023-05-30 08:19 UTC, shahor02 commented on Detectors/GlobalTracking/include/GlobalTracking/MatchHMP.h
> +  template <typename V>
what is this?

2023-05-30 10:24 UTC, gvolpe79 commented
Done!
Giacomo.

------------------------
Giacomo Volpe, Ph.D.
Associate Professor - Dipartimento Interateneo di Fisica ‘M. Merlin’of Bari University and Sezione INFN
Via Giovanni Amendola, 173
Bari, ITALY
contacts:
***@***.***, ***@***.***, ***@***.***
tel. +39 5443242
------------------------
________________________________
Da: Ruben Shahoyan ***@***.***>
Inviato: martedì 30 maggio 2023 10:19
A: AliceO2Group/AliceO2 ***@***.***>
Cc: Giacomo Volpe ***@***.***>; Author ***@***.***>
Oggetto: Re: [AliceO2Group/AliceO2] Anglerecon (PR #11400)


@shahor02 requested changes on this pull request.

________________________________

In DataFormats/Reconstruction/include/ReconstructionDataFormats/MatchInfoHMP.h<https://github.com/AliceO2Group/AliceO2/pull/11400#discussion_r1209895826>:

>    int mMipCluSize = 0.0; // MIP cluster size
   int mNPhots = 0.0;     // number of candidate photo-electrons
   int mIdxPhotClus;      // index of the first photo
+  int mHMPqn;            // 1000000*number of photon clusters + QDC
+  float mPhotCharge[10];


init array as float mPhotCharge[10] = {};

________________________________

In DataFormats/Reconstruction/include/ReconstructionDataFormats/TrackHMP.h<https://github.com/AliceO2Group/AliceO2/pull/11400#discussion_r1209897207>:

> + public:
+  TrackHMP();
+  TrackHMP(const TrackHMP& t) = default;
+  TrackHMP(const o2::track::TrackParCov& t) : o2::track::TrackParCov{t} {};
+  //  TrackHMP(const o2::track::TrackParCov& t);
+  TrackHMP& operator=(const o2::track::TrackParCov& t);
+  ~TrackHMP() = default;
+
+  Bool_t intersect(Double_t pnt[3], Double_t norm[3], double bz) const; //
+  void propagate(Double_t len, std::array<float, 3>& x, std::array<float, 3>& p, double bz) const;
+
+  // protected:
+  //    Bool_t   Update(const AliCluster */*c*/, Double_t /*chi2*/, Int_t /*idx*/) {return 0;}
+  //    Double_t GetPredictedChi2(const AliCluster */*c*/) const {return 0.;}
+ private:
+  ClassDef(TrackHMP, 0) // HMPID reconstructed tracks


0 has a special meaning, start from 1

________________________________

In Detectors/GlobalTracking/include/GlobalTracking/MatchHMP.h<https://github.com/AliceO2Group/AliceO2/pull/11400#discussion_r1209899615>:

> +  ///< populate externally provided container by TOF-time-constrained TPC tracks
+  template <typename V>


what is this?

—
Reply to this email directly, view it on GitHub<https://github.com/AliceO2Group/AliceO2/pull/11400#pullrequestreview-1450369943>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJNP5OTKDOMC6BMGHB6EB6LXIWUSJANCNFSM6AAAAAAYS4EEZU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-05-30 14:52 UTC, alibuild commented
Error while checking build/O2/fullCI for 047b505c23347caa5ec11879ff31e491b4b578eb at 2023-05-30 22:46:
```
## sw/BUILD/o2checkcode-latest/log
--
========== List of errors found ==========
++ GRERR=0
++ grep -v clang-diagnostic-error error-log.txt
++ grep ' error:'
/sw/SOURCES/O2/11400-slc8_x86-64/0/DataFormats/Reconstruction/src/TrackHMP.cxx:41:11: error: use '= default' to define a trivial default constructor [modernize-use-equals-default]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:112:36: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:114:7: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:161:24: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:167:26: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:170:21: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:172:27: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:228:56: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:309:28: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:314:51: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:321:26: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:326:49: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:357:44: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:363:44: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:369:44: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:375:44: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:395:34: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:397:34: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:406:18: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:408:7: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:411:17: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:413:7: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:446:27: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:496:31: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:498:7: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:516:40: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:529:24: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:539:18: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:541:21: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:544:22: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:547:47: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:580:45: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:585:84: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:587:46: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:411:39: error: use nullptr [modernize-use-nullptr]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:420:20: error: use nullptr [modernize-use-nullptr]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:441:35: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:448:34: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:469:20: error: use nullptr [modernize-use-nullptr]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:471:31: error: use nullptr [modernize-use-nullptr]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:483:38: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:487:20: error: use nullptr [modernize-use-nullptr]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:489:31: error: use nullptr [modernize-use-nullptr]
[0 more errors; see full log]
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/11400/047b505c23347caa5ec11879ff31e491b4b578eb/build_O2_fullCI/pretty.html).

2023-05-31 12:31 UTC, shahor02 commented on DataFormats/Reconstruction/include/ReconstructionDataFormats/MatchInfoHMP.h
> +      return mCkovAngle;
please add `{}`, it will trigger CI problems in the following PRs.

2023-06-01 13:40 UTC, alibuild commented
Error while checking build/O2/fullCI for c22248e24fe192ccea3e2d971a93d6a2b1fcdb72 at 2023-06-01 15:40:
```
## sw/BUILD/o2checkcode-latest/log
--
========== List of errors found ==========
++ GRERR=0
++ grep -v clang-diagnostic-error error-log.txt
++ grep ' error:'
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:177:27: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:321:51: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/HMPID/reconstruction/src/Recon.cxx:336:49: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:512:20: error: use nullptr [modernize-use-nullptr]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:557:33: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:563:20: error: use nullptr [modernize-use-nullptr]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:565:31: error: use nullptr [modernize-use-nullptr]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:600:16: error: use nullptr [modernize-use-nullptr]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:605:12: error: use nullptr [modernize-use-nullptr]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:625:48: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:627:48: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11400-slc8_x86-64/0/Detectors/GlobalTracking/src/MatchHMP.cxx:633:62: error: statement should be inside braces [readability-braces-around-statements]
++ [[ 0 == 0 ]]
++ exit 1
--
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/11400/c22248e24fe192ccea3e2d971a93d6a2b1fcdb72/build_O2_fullCI/pretty.html).

2023-06-02 13:12 UTC, shahor02 approved these changes

2023-06-02 13:12 UTC, merged