Add barrel track propagation to PV at AOD creation stage
AliceO2Group/AliceO2 pull request #11458
Opened 2023-06-08 11:52 UTC by nburmaso

Dear @ddobrigk, @jgrosseo, @sawenzel

Here is an implementation of (barrel) track propagation. It is similar to the track propagation task:
- tracks with x > 83.1 cm are not propagated
- If propagated successfully then type is set to `aod::track::Track`, `aod::track::TrackIU` otherwise
- track propagation can be enabled via option `--propagate-tracks`
- tracks are propagated using cov matrix if `--propagate-tracks-cov` is passed (in addition to `--propagate-tracks`)
- tracks used by the secondary vertexer are skipped

Please let me know if you have any suggestions

Nazar

2023-06-08 12:20 UTC, shahor02 requested changes

2023-06-08 12:20 UTC, shahor02 commented on Detectors/AOD/include/AODProducerWorkflow/AODProducerWorkflowSpec.h
> +
Please don't use ccdb manager but use the DPL fetcher, e.g. like:
https://github.com/AliceO2Group/AliceO2/blob/b4871415bbb9a0988f92714cce3b1176198bbe64/Detectors/GlobalTrackingWorkflow/src/PrimaryVertexingSpec.cxx#L241
https://github.com/AliceO2Group/AliceO2/blob/b4871415bbb9a0988f92714cce3b1176198bbe64/Detectors/GlobalTrackingWorkflow/src/PrimaryVertexingSpec.cxx#L212
https://github.com/AliceO2Group/AliceO2/blob/b4871415bbb9a0988f92714cce3b1176198bbe64/Detectors/GlobalTrackingWorkflow/src/PrimaryVertexingSpec.cxx#L180

2023-06-08 12:20 UTC, shahor02 commented on Detectors/AOD/src/AODProducerWorkflowSpec.cxx
> +    }
Note that now we also going to have the strangeness tracking: https://github.com/fmazzasc/AliceO2/commit/3715b202069ef621e60aa6bc5b5aca60d9304ce3

2023-06-08 12:20 UTC, shahor02 commented on Detectors/AOD/src/AODProducerWorkflowSpec.cxx
> +  if (trackPar.getX() > mMinPropR)
add `{}`

2023-06-08 12:20 UTC, shahor02 commented on Detectors/AOD/src/AODProducerWorkflowSpec.cxx
> +          o2::track::TrackParametrizationWithError<float> trackPar = data.getTrackParam(trackIndex);
here you create a track copy and check for the getX() > Xtpc only in the propagateTrackToPV. It would be faster to 1st check if the  track should be propagated then to create its copy

2023-06-08 12:20 UTC, shahor02 commented on Detectors/AOD/src/AODProducerWorkflowSpec.cxx
> +  }
don't use the manager, see above.

2023-06-08 12:20 UTC, shahor02 commented on Detectors/AOD/src/AODProducerWorkflowSpec.cxx
> +  }
The MeanVertex is in general Z-dependent (the beams have some angles), use just

```
o2::dataformats::VertexBase v = mVtx.getMeanVertex( colID < 0 ? 0.f : data.getPrimaryVertex(colID).getZ());
```

2023-06-08 12:20 UTC, shahor02 commented on Detectors/AOD/src/AODProducerWorkflowSpec.cxx
> +  return o2::base::Propagator::Instance()->propagateToDCABxByBz(v, trackPar, 2.f, mMatCorr, &dcaInfo);
Not sure what is the point of `mPropTracksCov` option? You are always propagating the cov.matrix.

2023-06-08 12:26 UTC, nburmaso commented
Thank you for the comments @shahor02! I will fix the code and ping you back :)

2023-06-08 13:09 UTC, nburmaso commented
@shahor02, I have tried fixing the code according to your suggestions. Could you please take a look when you have a moment?

2023-06-08 13:28 UTC, shahor02 reviewed
Thanks @nburmaso 
please see 1 comment below, the rest looks fine,

2023-06-08 13:28 UTC, shahor02 commented on Detectors/AOD/src/AODProducerWorkflowSpec.cxx
> +          if (mPropTracks && trackPar.getX() < mMinPropR) {
Now you have the trackPar undefined before the check :).
I would do:
```
const auto& trOrig = data.getTrackParam(trackIndex);
bool isProp = false;
if (mPropTracks && trOrig.getX() < mMinPropR) {
  auto trackPar(trOrig);
  if (isProp = propagateTrackToPV(trackPar, data, collisionID)) {
     addToTracksTable(tracksCursor, trackPar, collisionID, aod::track::Track);
  }
}
if (!isProp) {
  addToTracksTable(tracksCursor, tracksCovCursor, trOrig, collisionID, aod::track::TrackIU);
}

```

2023-06-08 13:41 UTC, nburmaso commented on Detectors/AOD/src/AODProducerWorkflowSpec.cxx
> +          if (mPropTracks && trackPar.getX() < mMinPropR) {
Thank you @shahor02, this looks better indeed :)

2023-06-08 14:04 UTC, alibuild commented
Error while checking build/O2/fullCI for 38887fc138291753d38c1dc01fab0fd33ee1bc1d at 2023-06-08 16:04:
```
## sw/BUILD/o2checkcode-latest/log
--
========== List of errors found ==========
++ GRERR=0
++ grep -v clang-diagnostic-error error-log.txt
++ grep ' error:'
/sw/SOURCES/O2/11458-slc8_x86-64/0/Detectors/AOD/src/AODProducerWorkflowSpec.cxx:447:73: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/11458-slc8_x86-64/0/Detectors/AOD/src/AODProducerWorkflowSpec.cxx:2362:35: error: statement should be inside braces [readability-braces-around-statements]
++ [[ 0 == 0 ]]
++ exit 1
--
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/11458/38887fc138291753d38c1dc01fab0fd33ee1bc1d/build_O2_fullCI/pretty.html).

2023-06-08 14:20 UTC, shahor02 approved these changes
now looks ok to me

2023-06-12 08:11 UTC, jgrosseo commented
Thanks a lot for this work. I have no further comments.

2023-06-13 11:13 UTC, merged