DPL: runNumber can never change to zero
AliceO2Group/AliceO2 pull request #11508
Opened 2023-06-15 15:11 UTC by martenole

In the end of run sequence it can happen that we receive a message with runNumber = 0. For some devices this can trigger a call which is only meant to happen in case a real new run is started. So for runNumber=0 the globalRunNumberChanged should not be set to true

```
[15:29:01][INFO] Processing timeslice:40260, tfCounter:40446, firstTForbit:32, runNumber:538056, creation:1547590800002, action:0
[15:29:01][INFO] Done processing timeslice:40260, tfCounter:40446, firstTForbit:32, runNumber:538056, creation:1547590800002, action:0, wall:1440
[15:29:01][INFO] Processing timeslice:40261, tfCounter:169, firstTForbit:0, runNumber:0, creation:1547590800000, action:0

```

Related to https://alice.its.cern.ch/jira/browse/O2-3859

2023-06-15 16:28 UTC, martenole commented
I am now not 100% sure anymore if we had not also seen run number 0 in synthetics at some point and therefore initialized the last run number with -1 instead of 0

2023-06-15 17:22 UTC, shahor02 commented
In principle, we are not supposed to use 0 as a run number, but to be safe, we can trigger globalRunNumberChanged on changing from -1 to 0, i.e.
```
timingInfo.globalRunNumberChanged = !TimingInfo::timesliceIsTimer(timeslice.value) 
&& dataProcessorContext.lastRunNumberProcessed != timingInfo.runNumber 
&& (timingInfo.runNumber != 0  || dataProcessorContext.lastRunNumberProcessed == -1) ;
```

2023-06-15 18:11 UTC, martenole commented
Yes, thanks, I think that would be better

2023-06-16 08:49 UTC, davidrohr requested changes
We can have runNumber 0 in MC / SYNTHETICS, so I would still support this, as you are doing now.

2023-06-16 08:49 UTC, davidrohr commented on Framework/Core/src/DataProcessingDevice.cxx
> +    timingInfo.globalRunNumberChanged |= (dataProcessorContext.lastRunNumberProcessed == -1 || timingInfo.runNumber != 0);
Shouldn't this be `&=`?

2023-06-16 08:54 UTC, martenole commented on Framework/Core/src/DataProcessingDevice.cxx
> +    timingInfo.globalRunNumberChanged |= (dataProcessorContext.lastRunNumberProcessed == -1 || timingInfo.runNumber != 0);
Right, thanks for spotting!

2023-06-16 22:04 UTC, merged