Improved thread safety in construtor and destructor of the downloader
AliceO2Group/AliceO2 pull request #11543
Opened 2023-06-22 09:30 UTC by TrifleMichael

All handle and loop initialization and deletion has been moved from the constructor and destructor to the loop thread.

Additionally, all mechanisms regarding the use of an external uv_loop have been removed, as their use would cause more thread safety violations.

2023-06-22 09:37 UTC, ktf requested changes
I am not sure I understand the changes. Why do you need a separate thread and a condition variable to initialise the thing?

2023-06-22 09:38 UTC, ktf commented
Also, I am completely against the removal of a the external uv_loop, which is a requirement for having this integrated in the multithreaded framework.

2023-06-22 09:43 UTC, TrifleMichael commented
> I am not sure I understand the changes. Why do you need a separate thread and a condition variable to initialise the thing?

uv_loop runs in a seperate thread in allow the main thread to continue executing the CcdbApi code. The seperate thread has been there since the first version of the downloader.

The condition variable is used to stop the downloader constructor from returning before the uv_loop is initialized. This protects it from receiving asynchronous handles (via download scheduling) too early.

2023-06-22 09:44 UTC, TrifleMichael commented
> Also, I am completely against the removal of a the external uv_loop, which is a requirement for having this integrated in the multithreaded framework.

The removal of external uv_loop is temporary, as the previous implementation both had multiple thread safety violations, and it required the uv_loop to not be initialized, effectively making it useless.

After this PR is finished I'll start working on adding proper external uv_loop handling.

2023-06-22 10:00 UTC, ktf commented
> uv_loop runs in a seperate thread to allow the main thread to continue executing the CcdbApi code. The seperate thread has been there since the first version of the downloader.

I think you should consider running everything on the main thread, using UV_RUN_ONCE / uv_task to avoid blocking whatever CCDB API code you need to run in parallel. I am pretty sure it will result in much simpler and more robust behaviour.

2023-06-22 10:20 UTC, sawenzel commented
I would suggest to take these improvements as they are now with the objective to make EPN operations stable. Then one can attack next-level milestones such as external uv_loop.

2023-06-22 10:20 UTC, sawenzel approved these changes

2023-06-22 10:27 UTC, ktf commented
The problem is not the external uv_loop, the issue is that having uv_loop on a separate thread and synchronising the main thread is a recipe for more headaches. I would remove the mThreadLoop, make sure the uv_loop is always running on the main thread and invoke uv_run(UV_NO_WAIT) whenever you have a chance in the CCDB downloader API. When you need to block to get an actual result, you simply invoke uv_run(UV_NO_WAIT) in a loop, until the handle you are interested in is completed. I think you can probably remove half of the current CCDBDownloader code and synchronization points if you structure it like that.

2023-06-22 11:07 UTC, ktf requested changes
I would suggest to fix the design for good, rather than postponing it.

2023-06-22 12:42 UTC, alibuild commented
Error while checking build/O2/fullCI for 6401e8d8bfed982195463cffd2478a5c187eec82 at 2023-06-22 14:42:
```
## sw/BUILD/O2-full-system-test-latest/log
command o2-sim --seed 12345 -j 28 -n 100 -m PIPE ITS MFT FT0 FV0 FDD -g extgen -e TGeant4 --configKeyValues "GeneratorExternal.fileName=$O2_ROOT/share/Generators/external/QEDLoader.C;QEDGenParam.yMin=-7;QEDGenParam.yMax=7;QEDGenParam.ptMin=0.001;QEDGenParam.ptMax=1.;${SIMOPTKEY}" --run 310000 had nonzero exit code 127
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/11543/6401e8d8bfed982195463cffd2478a5c187eec82/build_O2_fullCI/pretty.html).

2023-06-23 07:41 UTC, merged

2023-06-23 17:44 UTC, davidrohr commented
Unfortunately, this fix did not work. Run 538751 with it shows still the same symptoms:
```
E | 2 | 19:37:47.010 | epn117 |   | DPL | internal-dpl-ccdb-backend | 2g3hoQAnW2V | 538751 | CCDBDownloader: uvloop closed prematurely
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
```
So I think we should either redesign the libuv usage in a safer way, probably what @ktf commented makes sense.
Alternatively, as discussed, we actually don't need the threading at the moment, so if we add an option to just run everything synchronously, only keeping the sockets and tcp connections open with some timeout, that should be ok as well.