ITS-Study: create pt resolution, add efficiency of sec study
AliceO2Group/AliceO2 pull request #11763
Opened 2023-08-14 12:56 UTC by Roberta-Ferioli

@mconcas

2023-08-14 13:17 UTC, mconcas approved these changes, later dismissed
Approving just for CI, do nt merge yet.

2023-10-13 09:49 UTC, mconcas approved these changes

2023-10-13 12:02 UTC, mconcas requested changes

2023-10-13 12:02 UTC, mconcas commented on Detectors/ITSMFT/ITS/postprocessing/studies/src/TrackCheck.cxx
> +      histLength[iH - 4][jj] = new TH1I(Form("trk_len_%d_%s", iH, name[jj]), Form("#exists cluster %s", name), 7, -.5, 6.5);
```suggestion
      histLength[iH - 4][jj] = new TH1I(Form("trk_len_%d_%s", iH, name[jj]), Form("#exists cluster %s", name[jj]), 7, -.5, 6.5);
```

2023-10-13 12:02 UTC, mconcas commented on Detectors/ITSMFT/ITS/postprocessing/studies/src/TrackCheck.cxx
> +      histLengthNoCl[iH - 4][jj] = new TH1I(Form("trk_len_%d_nocl_%s", iH, name[jj]), Form("#slash{#exists} cluster %s", name), 7, -.5, 6.5);
```suggestion
      histLengthNoCl[iH - 4][jj] = new TH1I(Form("trk_len_%d_nocl_%s", iH, name[jj]), Form("#slash{#exists} cluster %s", name[jj]), 7, -.5, 6.5);
```

2023-10-13 12:14 UTC, mconcas requested changes

2023-10-13 12:14 UTC, mconcas commented on Detectors/ITSMFT/ITS/postprocessing/studies/src/TrackCheck.cxx
> +                                                                                                       bb, particleToanalize[aa]),
```suggestion
                                                                                                       particleToanalize[aa], bb),
```

2023-10-13 12:14 UTC, mconcas commented on Detectors/ITSMFT/ITS/postprocessing/studies/src/TrackCheck.cxx
> +                                                                                                       bb, particleToanalize[aa]),
```suggestion
                                                                                                       particleToanalize[aa], bb),
```

2023-10-13 12:14 UTC, mconcas commented on Detectors/ITSMFT/ITS/postprocessing/studies/src/TrackCheck.cxx
> +                                                                                                         bb, particleToanalize[aa]),
```suggestion
                                                                                                         particleToanalize[aa], bb),
```

2023-10-13 12:14 UTC, mconcas commented on Detectors/ITSMFT/ITS/postprocessing/studies/src/TrackCheck.cxx
> +                                                                                                         bb, particleToanalize[aa]),
```suggestion
                                                                                                         particleToanalize[aa], bb),
```

2023-10-13 12:31 UTC, mconcas submitted a review, later dismissed

2023-10-13 15:08 UTC, mconcas commented on Detectors/ITSMFT/ITS/postprocessing/studies/src/TrackCheck.cxx
> +      if (ProcessName[part.prodProcess] == " ")
```suggestion
      if (strcmp(ProcessName[part.prodProcess], " "))
```

2023-10-13 15:13 UTC, mconcas approved these changes

2023-10-13 19:42 UTC, alibuild commented
Error while checking build/O2/fullCI for c3b6b626f8dce123837de284995088790277b70b at 2023-10-13 21:42:
```
No log files found
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/11763/c3b6b626f8dce123837de284995088790277b70b/build_O2_fullCI/pretty.html).

2023-10-16 19:53 UTC, mconcas commented
Hi @TimoWilken, I see CentOS 8 builders failing the git fetch on multiple PRs. Will it run periodically so I can expect to have it going through at some point or shall I re-trigger the builds somehow? Thanks in advance.

2023-10-17 06:36 UTC, merged

2023-10-18 06:49 UTC, ktf commented
@mconcas @TimoWilken it's not clear to me how this could have passed the fullCI, given it breaks the code checker but apparently the test was green. Do we have some race condition in the tests? Was it force merged?

2023-10-18 06:50 UTC, ktf commented
Regression in code checker hopefully fixed by #12094.

2023-10-18 07:00 UTC, mconcas commented
> @mconcas @TimoWilken it's not clear to me how this could have passed the fullCI, given it breaks the code checker but apparently the test was green. Do we have some race condition in the tests? Was it force merged?

PR was merged with macos red as it always is lately, fullCI and co were green.
Similar issue in this open pr: https://github.com/AliceO2Group/AliceO2/pull/12044#discussion_r1361857734

Thanks for the fixes, I admittedly relied on automatic checks for this kind of problems.

2023-10-18 07:09 UTC, ktf commented
> PR was merged with macos red as it always is lately, fullCI and co were green.

Yes, that's exactly my point. fullCI should have caught it already when checking the PR.