Handling local files in CcdbApi
AliceO2Group/AliceO2 pull request #11796
Opened 2023-08-21 08:59 UTC by TrifleMichael

I tested this with both local files and cvmfs. If the file located via url is not present then that information is logged and other redirects follow as usual. If the file is found then it is returned correctly.

2023-08-21 09:02 UTC, costing submitted a review, later dismissed

2023-08-21 13:07 UTC, sawenzel approved these changes

2023-08-21 13:14 UTC, sawenzel commented on CCDB/src/CcdbApi.cxx
> +    return (void*)TFile::Open(url.c_str());
probably this is right, but there is now a divergence between alien and file protocols: The `alien:` code path is doing sanity type check etc.

I would suggest to modify the existing function to work for `file:` protocolls as well. (The only difference would be that we don't need to check for the GridToken in `downloadAlienContent`.

2023-08-21 13:14 UTC, sawenzel requested changes
see inline comment

2023-08-22 08:01 UTC, TrifleMichael commented
> see inline comment

Thank you for the suggestion. I've implemented that.

2023-08-22 08:20 UTC, sawenzel approved these changes

2023-08-23 09:03 UTC, merged