[EMCAL-565, EMCAL-566] Add option for subspecification for CTP information
AliceO2Group/AliceO2 pull request #11805
Opened 2023-08-22 13:36 UTC by jokonig

- EMCal online calibration relies on CTP digits to identify EMCal triggered events from minimum bias events
- As CTP digits are already send to another calib-node, the CTP information was not available online
- CTP now publishes the information to different subspecs, therefore, EMCal online calibration code is changed to have the subspec as a workflow option

2023-08-22 14:38 UTC, mfasDa requested changes
Subspec must not affect the CCDB objects.

2023-08-22 14:38 UTC, mfasDa commented on Detectors/EMCAL/calibration/testWorkflow/EMCALChannelCalibratorSpec.h
> +    inputs.emplace_back(device::getCTPConfigBinding(), "CTP", "CTPCONFIG", inputsubspecCTP, Lifetime::Condition, ccdbParamSpec("CTP/Config/Config", ctpcfgperrun));
Confgurable subspec does not impact CCDB objects - should stay with 0.

2023-08-22 14:38 UTC, mfasDa commented on Detectors/EMCAL/calibration/testWorkflow/EMCALChannelCalibratorSpec.h
> +    inputs.emplace_back(device::getCTPConfigBinding(), "CTP", "CTPCONFIG", inputsubspecCTP, Lifetime::Condition, ccdbParamSpec("CTP/Config/Config", ctpcfgperrun));
Here we have however a different problem: we can have multiple CTP configs per run, as AliECS allows multiple runs to be in parallel. We needs somehow a protection that the object for the proper run is selected. We might be able to do this in the finalizeCCDB.

2023-08-22 15:14 UTC, jokonig commented on Detectors/EMCAL/calibration/testWorkflow/EMCALChannelCalibratorSpec.h
> +    inputs.emplace_back(device::getCTPConfigBinding(), "CTP", "CTPCONFIG", inputsubspecCTP, Lifetime::Condition, ccdbParamSpec("CTP/Config/Config", ctpcfgperrun));
I changed the subspec for the ccdb object related ctp input back to 0

2023-08-25 01:42 UTC, alibuild commented
Error while checking build/O2/fullCI for 75adada89682769795dc04f4c877e6cd7a353708 at 2023-08-25 03:42:
```
## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'


## sw/BUILD/QualityControl-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'


## sw/BUILD/O2Physics-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
[ERROR] Function RecoDecay::getMassPDG is deprecated and will be removed soon.
[ERROR] Please use the Mass function in the O2DatabasePDG service instead.
[ERROR] See the example of usage in Tutorials/src/usingPDGService.cxx.
[ERROR] Function RecoDecay::getMassPDG is deprecated and will be removed soon.
[ERROR] Please use the Mass function in the O2DatabasePDG service instead.
[ERROR] See the example of usage in Tutorials/src/usingPDGService.cxx.
[ERROR] Function RecoDecay::getMassPDG is deprecated and will be removed soon.
[ERROR] Please use the Mass function in the O2DatabasePDG service instead.
[ERROR] See the example of usage in Tutorials/src/usingPDGService.cxx.
[ERROR] Function RecoDecay::getMassPDG is deprecated and will be removed soon.
[ERROR] Please use the Mass function in the O2DatabasePDG service instead.
[ERROR] See the example of usage in Tutorials/src/usingPDGService.cxx.
[ERROR] Function RecoDecay::getMassPDG is deprecated and will be removed soon.
[ERROR] Please use the Mass function in the O2DatabasePDG service instead.
[ERROR] See the example of usage in Tutorials/src/usingPDGService.cxx.
[ERROR] Function RecoDecay::getMassPDG is deprecated and will be removed soon.
[ERROR] Please use the Mass function in the O2DatabasePDG service instead.
[ERROR] See the example of usage in Tutorials/src/usingPDGService.cxx.
[ERROR] Function RecoDecay::getMassPDG is deprecated and will be removed soon.
[ERROR] Please use the Mass function in the O2DatabasePDG service instead.
[ERROR] See the example of usage in Tutorials/src/usingPDGService.cxx.
[ERROR] Function RecoDecay::getMassPDG is deprecated and will be removed soon.
[ERROR] Please use the Mass function in the O2DatabasePDG service instead.
[ERROR] See the example of usage in Tutorials/src/usingPDGService.cxx.
[ERROR] Function RecoDecay::getMassPDG is deprecated and will be removed soon.
[ERROR] Please use the Mass function in the O2DatabasePDG service instead.
[ERROR] See the example of usage in Tutorials/src/usingPDGService.cxx.
[ERROR] Function RecoDecay::getMassPDG is deprecated and will be removed soon.
[ERROR] Please use the Mass function in the O2DatabasePDG service instead.
[ERROR] See the example of usage in Tutorials/src/usingPDGService.cxx.
[0 more errors; see full log]
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/11805/75adada89682769795dc04f4c877e6cd7a353708/build_O2_fullCI/pretty.html).

2023-08-27 08:10 UTC, davidrohr commented
the fix for multiple output proxies was merged. Let's try that next week. If it works, we don't need this PR.

2023-10-05 00:53 UTC, closed without merging