cheange done by me
AliceO2Group/AliceO2 pull request #11905
Opened 2023-09-18 05:42 UTC by BhanuThakurani

2023-09-18 08:39 UTC, ddobrigk commented
Hi @BhanuThakurani , can you please edit the name of this PR to something more meaningful? Thank you!

2023-09-28 20:55 UTC, shahor02 requested changes

2023-09-28 20:55 UTC, shahor02 commented on DataFormats/Reconstruction/include/ReconstructionDataFormats/PID.h
> +  static constexpr ID LastExt = Hyperhelium4;
Why are you changing the IDs of existing particles? This is not backward-compatible. Also, with the `NIDsTot = 18` the specific IDs should span 0-17, while you reassign HyperTriton from 13 to 18.

2023-09-28 20:55 UTC, shahor02 commented on Detectors/Vertexing/src/SVertexer.cxx
> +  "log_pT3body.txt", std::ios_base::out | std::ios_base::app);
This is not used anywhere and we should not produce a stray log files in the standard mode

2023-09-28 20:55 UTC, shahor02 commented on Detectors/Vertexing/src/SVertexer.cxx
> +  int ntrP = mTracksPool[POS].size(), ntrN = mTracksPool[NEG].size(), iThread = 0;
Too many modifications below in quite a subtle code and not clear why they are needed, please clarify.

2023-10-06 12:50 UTC, sawenzel commented
There is no reaction to the comments in the this PR. I will close it for now. Please rework it and reopen when ready (good commit message and reasonable PR title).

2023-10-06 12:50 UTC, closed without merging

2023-10-06 13:17 UTC, ddobrigk commented
I think this PR was opened by accident and indeed fine to close. I will discuss with the authors in more detail how to proceed. Thanks!