DPL Analysis: minor cleanups in ASoA
AliceO2Group/AliceO2 pull request #12201
Opened 2023-11-03 11:40 UTC by aalkin

2023-11-03 12:18 UTC, ktf commented
@TimoWilken I think there is something broken with the CI:

```
CMake Error: Generator: execution of make failed. Make command was: /sw/slc8_x86-64/ninja/fortran-v1.8.2.g3b-19/bin/ninja -j 32 install && 
```

is this due to the new container?

2023-11-03 12:20 UTC, TimoWilken commented
Hi @ktf, no, the slc8 container was not changed.

2023-11-03 12:48 UTC, TimoWilken commented
@ktf looks like the builder actually ran out of memory (the peak around 12:50 is when [the log](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/12201/092025d806d30e0ae6df4d02038ab446b2b8e22e/build_O2_o2-dataflow/fullLog.txt) says it finished on `c03e0332`):

![Screenshot_2023-11-03_13-47-59](https://github.com/AliceO2Group/AliceO2/assets/3159813/27b79254-8995-4d98-92b8-2864c2a0c15f)

2023-11-03 14:02 UTC, alibuild commented
Error while checking build/O2/fullCI for 092025d806d30e0ae6df4d02038ab446b2b8e22e at 2023-11-03 15:02:
```
## sw/BUILD/o2codechecker-latest/log
100% tests passed, 0 tests failed out of 1


## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
CMake Error: Generator: execution of make failed. Make command was: /sw/slc8_x86-64/ninja/fortran-v1.8.2.g3b-20/bin/ninja -j 32 install &&
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/12201/092025d806d30e0ae6df4d02038ab446b2b8e22e/build_O2_fullCI/pretty.html).

2023-11-06 15:02 UTC, TimoWilken commented
Hi @aalkin, sorry, this keeps OOMing the Linux CI builders, so I'm marking this as draft.

2023-11-06 15:08 UTC, aalkin commented
@TimoWilken this is very surprising. I see it also fails with mac CI, which I cannot reproduce locally. I'm not sure how this tiny change can cause anything like this.

2023-11-06 15:21 UTC, TimoWilken commented
Hm, e.g. for the first error in the ARM Mac CI:

```
/Volumes/build/alice-ci-workdir/o2/sw/SOURCES/O2/12201/0/Framework/Core/include/Framework/AnalysisDataModel.h:130:1: error: no member named 'FunctionMetadata' in namespace 'o2::framework'
```

`FunctionalMetadata` apparently comes from `Framework/FunctionalHelpers.h`, and you're removing that include, and I can't see another header that includes it transitively in `ASoA.h`.

At least I can see how removing includes might cause problems like this. I don't know how that would cause an OOM on Linux/GCC, though...

2023-11-07 08:23 UTC, ktf requested changes
We should fix at least the missing functional.

2023-11-07 08:23 UTC, ktf commented on Framework/Core/src/ASoA.cxx
> -#include "ArrowDebugHelpers.h"
Why removing this?

2023-11-07 08:23 UTC, ktf commented on Framework/Core/include/Framework/ASoA.h
>  #include <arrow/table.h>
```suggestion
#include <arrow/table.h>
#include <functional>
```

2023-11-07 12:23 UTC, aalkin commented
@TimoWilken I have not been able to find any reason behind OOM, but the issue with missing `<functional>` include is indeed present when compiling with gcc and older clang. Could you please monitor this PR and turn it off if it causes OOM again? Thanks.

2023-11-07 12:35 UTC, TimoWilken commented
Thanks @aalkin, will do! I've also been able to reproduce the OOM locally; I'm running the compilation again now to try and catch which process causes it.

2023-11-07 15:09 UTC, alibuild commented
Error while checking build/O2/fullCI for 95b7de80bf206a24c2cb5cd402ceb46e4bd14d03 at 2023-11-07 16:09:
```
## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
CMake Error: Generator: execution of make failed. Make command was: /sw/slc8_x86-64/ninja/fortran-v1.8.2.g3b-20/bin/ninja -j 32 install &&
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/12201/95b7de80bf206a24c2cb5cd402ceb46e4bd14d03/build_O2_fullCI/pretty.html).

2023-11-07 16:14 UTC, aalkin commented
It seems the changes still cause problem for CI, I will close this for now.

2023-11-07 16:14 UTC, closed without merging