[CTP] Add digit reader workflow
AliceO2Group/AliceO2 pull request #12364
Opened 2023-11-30 13:22 UTC by mfasDa

Needed for QC at simulation level

2023-11-30 13:25 UTC, mfasDa commented
Needed for QC in MC: In MC QC tasks are not attached to the AOD producer workflow but run sequentially with the file readers as data source. In order for QC tasks to subscribe to CTP digits the corresponding reader needs to be provided.

@lietava Please check!

2023-11-30 13:45 UTC, lietava commented
@mfasDa well, ok. Although it is more for @shahor02.

2023-11-30 14:01 UTC, shahor02 requested changes

2023-11-30 14:01 UTC, shahor02 commented on Detectors/CTP/workflowIO/src/digits-reader-workflow.cxx
> +
Please add here 
```

void customize(std::vector<o2::framework::CallbacksPolicy>& policies)
{
  o2::raw::HBFUtilsInitializer::addNewTimeSliceCallback(policies);
}
```

2023-11-30 14:01 UTC, shahor02 commented on Detectors/CTP/workflowIO/src/digits-reader-workflow.cxx
> +    {"configKeyValues", VariantType::String, "", {"Semicolon separated key=value strings"}}};
Add after this
```
o2::raw::HBFUtilsInitializer::addConfigOption(options);
```

2023-11-30 14:43 UTC, mfasDa commented on Detectors/CTP/workflowIO/src/digits-reader-workflow.cxx
> +
Done

2023-11-30 14:43 UTC, mfasDa commented on Detectors/CTP/workflowIO/src/digits-reader-workflow.cxx
> +    {"configKeyValues", VariantType::String, "", {"Semicolon separated key=value strings"}}};
Done

2023-11-30 14:45 UTC, mfasDa commented on Detectors/CTP/workflowIO/src/digits-reader-workflow.cxx
> +
Done

2023-11-30 14:45 UTC, mfasDa commented on Detectors/CTP/workflowIO/src/digits-reader-workflow.cxx
> +    {"configKeyValues", VariantType::String, "", {"Semicolon separated key=value strings"}}};
Done

2023-11-30 18:39 UTC, mfasDa commented
CI errors unrelated

2023-12-01 12:56 UTC, shahor02 approved these changes

2023-12-01 12:56 UTC, merged