SVERTEXER: Recover ITSonly OB tracks for PCM
AliceO2Group/AliceO2 pull request #12417
Opened 2023-12-07 21:18 UTC by f3sch

Not tested. Don't merge!

2023-12-07 21:40 UTC, shahor02 commented on Detectors/Vertexing/src/SVertexer.cxx
> +          bITSOBonly = itsABTracklet.getFirstEntry() > 3;
This is anyway guaranteed by the AB track construction

2023-12-08 10:08 UTC, shahor02 requested changes

2023-12-08 10:08 UTC, shahor02 commented on Detectors/Vertexing/src/SVertexer.cxx
> +          bITSOBonly = itsABTracklet.getFirstEntry() > 3;
The AB tracklet is always in OB and `itsABTracklet.getFirstEntry()` anyway returns not the layer but entry of the 1st cluster in the pool. 
Just use `bITSOBonly = true;`

2023-12-08 13:57 UTC, shahor02 requested changes

2023-12-08 13:57 UTC, shahor02 commented on Detectors/Vertexing/src/SVertexer.cxx
> +          bITSOBonly = itsABTracklet.getFirstEntry() > 3;
@ddobrigk has rightfully noted that the AB track is not ITS only by construction, see the continuation of the comment later.

2023-12-08 13:57 UTC, shahor02 commented on Detectors/Vertexing/src/SVertexer.cxx
> +  bool isITSOBonly = (seedP.bITSOB || seedN.bITSOB);
Below (L670) you interpret `isITSOBonly` as not only (1) ITS hits being only on the OB but also as (2) not having TPC. 
But to set the bITSOB flag it is enough to fulfill (1) only. Either one should check here additionally for `seedP.gid.getSource() == GIndex::ITS ...` or exclude tracks with TPC in the assignment of the `bITSOB` in the `buildT2V`.

2023-12-08 15:04 UTC, f3sch commented
Closed in favor of #12420

2023-12-08 15:04 UTC, closed without merging