Hotfix for PID Hypothesis - switch to disable Canvas
AliceO2Group/AliceO2 pull request #12755
Opened 2024-02-23 15:06 UTC by HorstMa

There was an issue with the last PR #12630  where TCanvas could not be merged. This PR allows to disable the TCanvas generation through the JSON file. This is paired with another PR in QC.

2024-02-23 21:45 UTC, alibuild commented
Error while checking build/O2/fullCI for 0a28b53ba1e917ca872f6aae7c66f4ecce492b9c at 2024-02-23 22:45:
```
## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'


## sw/BUILD/O2-full-system-test-latest/log
task timeout reached .. killing all processes


## sw/BUILD/o2checkcode-latest/log
--
========== List of errors found ==========
++ GRERR=0
++ grep -v clang-diagnostic-error error-log.txt
++ grep ' error:'
++ GRERR=1
++ [[ 1 == 0 ]]
++ mkdir -p /sw/INSTALLROOT/85dca648b06fb873216efd5ea131ca0c1d3a5b5d/slc8_x86-64/o2checkcode/1.0-local110/etc/modulefiles
++ cat
--
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/12755/0a28b53ba1e917ca872f6aae7c66f4ecce492b9c/build_O2_fullCI/pretty.html).

2024-02-26 07:56 UTC, wiechula requested changes

2024-02-26 07:56 UTC, wiechula commented on Detectors/TPC/qc/include/TPCQC/PID.h
> +                  float maxpTPCMIPs = 0.55, int CreateCanvasI = 1)
Naming convention, more below.
```suggestion
                  float maxpTPCMIPs = 0.55, int createCanvasI = 1)
```

2024-02-26 07:56 UTC, wiechula commented on Detectors/TPC/qc/include/TPCQC/PID.h
> +    CreateCanvas = CreateCanvasI;
```suggestion
    mCreateCanvas = createCanvasI;
```

2024-02-26 07:56 UTC, wiechula commented on Detectors/TPC/qc/include/TPCQC/PID.h
> +  bool CreateCanvas = true;      // Decide whether to create the TCanvas Object as it cannot be merged
```suggestion
  bool mCreateCanvas = true;      // Decide whether to create the TCanvas Object as it cannot be merged
```

2024-02-26 07:56 UTC, wiechula commented on Detectors/TPC/qc/src/PID.cxx
> +    if (CreateCanvas) {
```suggestion
    if (mCreateCanvas) {
```

2024-02-26 07:56 UTC, wiechula commented on Detectors/TPC/qc/src/PID.cxx
> +  if (CreateCanvas) {
```suggestion
  if (mCreateCanvas) {
```

2024-02-26 07:56 UTC, wiechula commented on Detectors/TPC/qc/src/PID.cxx
> +      if (CreateCanvas) {
```suggestion
      if (mCreateCanvas) {
```

2024-02-26 07:56 UTC, wiechula commented on Detectors/TPC/qc/src/PID.cxx
> +  if (CreateCanvas) {
```suggestion
  if (mCreateCanvas) {
```

2024-02-26 08:03 UTC, wiechula requested changes

2024-02-26 08:03 UTC, wiechula commented on Detectors/TPC/qc/include/TPCQC/PID.h
> +                  float maxpTPCMIPs = 0.55, int CreateCanvasI = 1)
Naming convention, more below. Also `createCanvasI` is not a cut. So it does not really fit to the function name. Please split it. And restore the previous formatting of `setPIDCuts`.
```suggestion
                  float maxdEdxTot = 70., float minpTPC = 0.05, float maxpTPC = 20., float minpTPCMIPs = 0.45, float maxpTPCMIPs = 0.55)
```

2024-02-26 08:03 UTC, wiechula commented on Detectors/TPC/qc/include/TPCQC/PID.h
> +    CreateCanvas = CreateCanvasI;
```suggestion
}

void setCreateCanvas(bool createCanvas) {
    mCreateCanvas = createCanvas;
    }
```

2024-02-26 14:59 UTC, HorstMa commented
thanks, @wiechula I changed the naming convention and added a separate function.

2024-02-28 07:51 UTC, wiechula approved these changes

2024-02-28 07:53 UTC, wiechula commented
Can be merged from my side, but should be squashed. The failure looks unrelated.

2024-02-28 09:56 UTC, merged