shm-metadata-msg-size parameter mapped
AliceO2Group/AliceO2 pull request #12763
Opened 2024-02-26 10:23 UTC by justonedev1

- parameter mapped
- added simple workflow to test the parameter values

2024-02-26 10:24 UTC, justonedev1 commented
This task was issued by @knopers8

2024-02-26 10:28 UTC, knopers8 commented on Framework/TestWorkflows/src/o2FairMQHeaderSizeTest.cxx
> +
Could you document in a few sentences what is this executable for?

2024-02-26 12:36 UTC, justonedev1 commented on Framework/TestWorkflows/src/o2FairMQHeaderSizeTest.cxx
> +
done

2024-02-26 12:50 UTC, knopers8 submitted a review, later dismissed
Thank you!
@ktf Are you OK with this?

2024-02-29 09:17 UTC, knopers8 commented
> Thank you! @ktf Are you OK with this?

ping @ktf

2024-02-29 09:33 UTC, ktf commented
I think you might need the extra parameter in a few more places, actually. At least that's the case for all the others "shm-" ones.

2024-02-29 09:38 UTC, ktf requested changes
I think you need the parameter to be propagated in a few more places, like the others.

2024-03-08 09:48 UTC, justonedev1 commented
Is this better @ktf ?

2024-03-12 09:17 UTC, ktf commented on Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
> +  LOG(info) << expected;
```suggestion
  LOG(info) << ss.str();
  LOG(info) << expected;
```

no printouts in the tests, please.

2024-03-12 16:07 UTC, alibuild commented
Error while checking build/O2/fullCI for 7ed0eab5a6451d3b5f6ee8d6d006d84feaa32509 at 2024-03-12 17:07:
```
## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'


## sw/BUILD/O2-full-system-test-latest/log
task timeout reached .. killing all processes


## sw/BUILD/o2checkcode-latest/log
--
========== List of errors found ==========
++ GRERR=0
++ grep -v clang-diagnostic-error error-log.txt
++ grep ' error:'
++ GRERR=1
++ [[ 1 == 0 ]]
++ mkdir -p /sw/INSTALLROOT/d72b37390585d526cf80cd9a7a7fa7ab0e67c575/slc8_x86-64/o2checkcode/1.0-local212/etc/modulefiles
++ cat
--
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/12763/7ed0eab5a6451d3b5f6ee8d6d006d84feaa32509/build_O2_fullCI/pretty.html).

2024-03-13 09:15 UTC, justonedev1 commented
@ktf I removed the logging lines and rebased it on current dev branch so CI works. Is there anything else I need to change?

2024-03-18 13:43 UTC, knopers8 commented
@ktf ping

2024-03-19 13:27 UTC, justonedev1 commented
@ktf ping

2024-03-19 13:32 UTC, merged