[EMCAL-1116] Add maximum value for pedestal calib
AliceO2Group/AliceO2 pull request #12958
Opened 2024-03-29 10:19 UTC by jokonig

- In order to not set unreasonable values for the pedestal calibration, a maximum value is introduced
- The value is configurable in the CalibrationParams

2024-04-02 07:35 UTC, mfasDa requested changes
Needs some change: The default value first needs to be 1023 (10 bit, all bits 1), as the ADC works with 10 bit precision. Second, how can 10-bit ADC values exceed the 1023? The maximum ADC value (1023) should be set in case the RMS of the distribution (settable cut) is too high, effectively setting the channel to dead.

2024-04-02 11:02 UTC, mfasDa requested changes
One small change needed

2024-04-02 11:02 UTC, mfasDa commented on Detectors/EMCAL/calibration/include/EMCALCalibration/EMCALCalibExtractor.h
> +  const short mMaxPedestalVal = 1023;       ///< Maximum value for pedestals
should be `static constexr`

2024-04-03 11:26 UTC, jokonig commented on Detectors/EMCAL/calibration/include/EMCALCalibration/EMCALCalibExtractor.h
> +  const short mMaxPedestalVal = 1023;       ///< Maximum value for pedestals
done

2024-04-03 12:38 UTC, mfasDa approved these changes
Looks good now

2024-04-03 12:48 UTC, merged