Separation power for Pions and Electrons
AliceO2Group/AliceO2 pull request #12988
Opened 2024-04-05 08:45 UTC by HorstMa

This PR adds the separation power that can be trended for pions and electrons at the MIP point.

2024-04-05 09:58 UTC, wiechula requested changes

2024-04-05 09:58 UTC, wiechula commented on Detectors/TPC/qc/include/TPCQC/PID.h
> +  TCanvas* getSeparationPower() { return cSeparationPowerCanvas; }
```suggestion
  TCanvas* getSeparationPowerCanvas() { return mSeparationPowerCanvas; }
```

2024-04-05 09:58 UTC, wiechula commented on Detectors/TPC/qc/include/TPCQC/PID.h
> +  TCanvas* cSeparationPowerCanvas;
```suggestion
  TCanvas* mSeparationPowerCanvas = nullptr;
```

2024-04-05 09:58 UTC, wiechula commented on Detectors/TPC/qc/src/PID.cxx
> +#include "TF1.h"
Ist this header used?
```suggestion
```

2024-04-05 09:58 UTC, wiechula commented on Detectors/TPC/qc/src/PID.cxx
> +  cSeparationPowerCanvas = new TCanvas("CSeparationPower", "Separation Power");
```suggestion
  mSeparationPowerCanvas = new TCanvas("CSeparationPower", "Separation Power");
```

2024-04-05 11:02 UTC, alibuild commented
Error while checking build/O2/fullCI for cd14504aec2446cafec30fa66c212d0b6250b120 at 2024-04-05 13:02:
```
## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
input_line_9:168:48: error: use of undeclared identifier 'cSeparationPowerCanvas'
Error: /sw/slc8_x86-64/ROOT/v6-30-01-alice4-6/bin/rootcling: compilation failure (/sw/BUILD/4d6ee0878a064ffb56614948916ac517898352c7/O2/Detectors/TPC/qc/G__O2TPCQC927318bec8_dictUmbrella.h)
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/12988/cd14504aec2446cafec30fa66c212d0b6250b120/build_O2_fullCI/pretty.html).

2024-04-18 20:26 UTC, alibuild commented
Error while checking build/O2/fullCI for aeaa058c76e9f29507a2a26c6db2e65ce251e688 at 2024-04-18 22:26:
```
## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/12988/aeaa058c76e9f29507a2a26c6db2e65ce251e688/build_O2_fullCI/pretty.html).

2024-04-25 07:25 UTC, shahor02 requested changes
@HorstMa please rebase your branch to fresh dev and force push.

2024-04-25 07:45 UTC, wiechula requested changes

2024-04-25 07:45 UTC, wiechula commented on Detectors/TPC/qc/include/TPCQC/PID.h
> +  TCanvas* getSeparationPowerCanvas() { return mSeparationPowerCanvas; }
```suggestion
  TCanvas* getSeparationPowerCanvas() { return mSeparationPowerCanvas.get(); }
```

2024-04-25 07:45 UTC, wiechula commented on Detectors/TPC/qc/include/TPCQC/PID.h
> +  TCanvas* mSeparationPowerCanvas = nullptr;
```suggestion
  std::unique_ptr<TCanvas> mSeparationPowerCanvas;
```

2024-04-25 07:45 UTC, wiechula commented on Detectors/TPC/qc/src/PID.cxx
> +  mSeparationPowerCanvas = new TCanvas("CSeparationPower", "Separation Power");
```suggestion
  mSeparationPowerCanvas.reset(new TCanvas("CSeparationPower", "Separation Power"));
```

2024-04-25 09:48 UTC, wiechula approved these changes

2024-05-22 12:41 UTC, alibuild commented
Error while checking build/O2/fullCI for aa1c8f9ca394d7dee87557963ab8e2364ca0a713 at 2024-05-22 14:41:
```
## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'


## sw/BUILD/O2-sim-challenge-test-latest/log
./sim-challenge.log[ERROR] Workflow crashed - PID 19503 (tof-matcher) did not exit correctly however it's not clear why. Exit code forced to 128.
./sim-challenge.log[ERROR]  - Device tof-matcher: pid 19503 (exit 128)
./sim-challenge.log[ERROR] SEVERE: Device tof-matcher (19503) returned with 128
./midreco.log[14897:MIDRecoWriter]: [12:40:40][ERROR] Some Lifetime::Timeframe data got dropped starting at 1
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/37}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/38}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/40}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/42}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/43}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/45}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/46}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/47}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/48}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/49}
./digi.log[7793:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/37}
./digi.log[7793:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/38}
./digi.log[7793:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/40}
./digi.log[7793:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/42}
./digi.log[7793:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/43}
./digi.log[7793:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/45}
./digi.log[7793:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/46}
./digi.log[7793:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/47}
./digi.log[7793:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/48}
./digi.log[7793:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/49}
./digi.log[7794:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/37}
./digi.log[7794:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/38}
./digi.log[7794:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/40}
./digi.log[7794:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/42}
./digi.log[7794:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/43}
./digi.log[7794:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/45}
./digi.log[7794:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/46}
./digi.log[7794:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/47}
./digi.log[7794:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/48}
./digi.log[7794:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/49}
./digi.log[7795:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/37}
./digi.log[7795:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/38}
./digi.log[7795:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/40}
./digi.log[7795:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/42}
./digi.log[7795:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/43}
./digi.log[7795:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/45}
./digi.log[7795:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/46}
./digi.log[7795:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/47}
./digi.log[7795:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/48}
[0 more errors; see full log]
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/12988/aa1c8f9ca394d7dee87557963ab8e2364ca0a713/build_O2_fullCI/pretty.html).

2024-06-06 13:58 UTC, merged