[FOCAL-78, FOCAL-84] First commit for the geometry helper class for the FOCAL detector
AliceO2Group/AliceO2 pull request #13153
Opened 2024-05-22 14:35 UTC by iarsene

2024-05-22 15:50 UTC, mfasDa requested changes
Some modernizations, + I think some Constructors/Copy Constructors/ Assignment operators can be made default.

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +  }
Use memcpy (more efficient)

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +  }
Use memcpy (more efficient)

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +    mVirtualSegmentComposition()
Default values should be defined in the header file, then this part can go away.

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/include/FOCALBase/Geometry.h
> +  ~Geometry();
They can probably all be default.

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/include/FOCALBase/Composition.h
> +  Composition& operator=(const Composition& comp);
Can be default

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/include/FOCALBase/Composition.h
> +  float mSizeZ;
Define default values here, then you don't need to define them in the constructor implementation and the default constructor will take the values specified here.

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/include/FOCALBase/Geometry.h
> +  std::string mGlobal_Gap_Material;  // gap filling material	       // NOTE: currently not used
Define default values here.

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/include/FOCALBase/Geometry.h
> +  void setParameters(const std::string geoFile);
Use std::string_view (0-copy)

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/include/FOCALBase/Geometry.h
> +  void init(const std::string geoFile);
Use std::string_view (0-copy)

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +  if (filename.compare("default")) {
it is a bit better readable to use
```c++
if(filename != "default") {
  ...
}
```

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +  frontMatterCompDummy.reserve(10);
This can be done in one shot during the construction:
```c++
  std::vector<Composition> padCompDummy(10);
  std::vector<Composition> hCalCompDummy(10);
  std::vector<Composition> pixelCompDummy(10);
  std::vector<Composition> frontMatterCompDummy(10);
  ```
  But, if the size is const, better make them std::array.

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +      }
If you want to check for an empty string, this is a bit better readable:
```c++
if(!tmpStr.length()){
}
```
or
```c++
if(!tmpStr.empty()){
}
```

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +      char* cdata = (char*)command.c_str();
why needed?

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +        padCompDummy.push_back(*(new Composition(material, stack, stack, 0, cx, cy, cz, dx, dy, dz)));
Use std::vector::emplace_back instead:
```c++
padCompDummy.emplace_back(material, stack, stack, 0, cx, cy, cz, dx, dy, dz);
```
This constructs a new object at the end of the vector. The good thing: This optimises out the copy which you would have otherwise.

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +        hCalCompDummy.push_back(*(new Composition(material, stack, stack, 0, cx, cy, cz, dx, dy, dz)));
Again emplace_back

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +        pixelCompDummy.push_back(*(new Composition(material, stack, stack, 0, cx, cy, cz, dx, dy, dz)));
Again emplace_back

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +        frontMatterCompDummy.push_back(*(new Composition(material, stack, stack, 0, cx, cy, cz, dx, dy, dz)));
Again emplace_back

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +      char* cdata = (char*)command.c_str();
Why needed?

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +      char* cdata = (char*)command.c_str();
Why needed?

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +              mVirtualSegmentComposition.push_back(*(new VirtualSegment()));
Again emplace_back

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +              mVirtualSegmentComposition.push_back(*(new VirtualSegment()));
Again emplace_back

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +                                                      mTowerSizeX, mTowerSizeY, tmpComp.SizeZ())));
Again emplace_back

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +                                                              mGlobal_Pad_Size, mGlobal_Pad_Size, tmpComp.SizeZ())));
Again emplace_back

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +              auto padCenter = getGeoPadCenterLocal(itowerX, itowerY, iy, ix);
You could use structured binding to access the content of the tuple directly. Makes the code a bit better readable.

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +                                                        tmpComp.CenterX(), tmpComp.CenterY(), center_z, mTowerSizeX, mTowerSizeY, tmpComp.SizeZ())));
Again emplace_back

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +                                                            mGlobal_PIX_SizeX, mGlobal_PIX_SizeY, tmpComp.SizeZ())));
Again emplace_back

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +                                                     tmpComp.SizeX(), tmpComp.SizeY(), tmpComp.SizeZ())));
Again emplace_back

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +  return false;
Can be done in a simpler way with std::find:
```c++
   return std::find(mDisableTowers.begin(), mDisableTowers.end(), tower) == mDisableTowers.end();
```

2024-05-22 15:50 UTC, mfasDa commented on Detectors/FOCAL/base/src/Geometry.cxx
> +  int segment = std::get<2>(info);
Again, use structured binding for the tuple:
```c++
auto [status, layer, segment] = getVirtualLayerSegment(z);
```

2024-05-22 15:55 UTC, alibuild commented
Error while checking build/O2/fullCI for a185af348084f9b26964aa7380db4ecc9b413348 at 2024-05-22 17:55:
```
## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'


## sw/BUILD/o2checkcode-latest/log
--
========== List of errors found ==========
++ GRERR=0
++ grep -v clang-diagnostic-error error-log.txt
++ grep ' error:'
/sw/SOURCES/O2/13153-slc8_x86-64/0/Detectors/FOCAL/base/src/Composition.cxx:31:57: error: use nullptr [modernize-use-nullptr]
/sw/SOURCES/O2/13153-slc8_x86-64/0/Detectors/FOCAL/base/src/Composition.cxx:45:14: error: use '= default' to define a trivial copy constructor [modernize-use-equals-default]
/sw/SOURCES/O2/13153-slc8_x86-64/0/Detectors/FOCAL/base/src/Composition.cxx:75:14: error: use '= default' to define a trivial destructor [modernize-use-equals-default]
/sw/SOURCES/O2/13153-slc8_x86-64/0/Detectors/FOCAL/base/src/Geometry.cxx:889:36: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/13153-slc8_x86-64/0/Detectors/FOCAL/base/src/Geometry.cxx:891:36: error: statement should be inside braces [readability-braces-around-statements]
++ [[ 0 == 0 ]]
++ exit 1
--
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/13153/a185af348084f9b26964aa7380db4ecc9b413348/build_O2_fullCI/pretty.html).

2024-05-23 08:28 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +  }
done

2024-05-23 08:28 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +  }
done

2024-05-23 08:28 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +    mVirtualSegmentComposition()
done

2024-05-23 08:29 UTC, iarsene commented on Detectors/FOCAL/base/include/FOCALBase/Geometry.h
> +  ~Geometry();
done

2024-05-23 08:29 UTC, iarsene commented on Detectors/FOCAL/base/include/FOCALBase/Composition.h
> +  Composition& operator=(const Composition& comp);
done

2024-05-23 08:29 UTC, iarsene commented on Detectors/FOCAL/base/include/FOCALBase/Composition.h
> +  float mSizeZ;
done

2024-05-23 08:29 UTC, iarsene commented on Detectors/FOCAL/base/include/FOCALBase/Geometry.h
> +  std::string mGlobal_Gap_Material;  // gap filling material	       // NOTE: currently not used
done

2024-05-23 08:29 UTC, iarsene commented on Detectors/FOCAL/base/include/FOCALBase/Geometry.h
> +  void setParameters(const std::string geoFile);
done

2024-05-23 08:29 UTC, iarsene commented on Detectors/FOCAL/base/include/FOCALBase/Geometry.h
> +  void init(const std::string geoFile);
done

2024-05-23 08:30 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +  if (filename.compare("default")) {
done

2024-05-23 08:30 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +  frontMatterCompDummy.reserve(10);
done

2024-05-23 08:31 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +      }
done

2024-05-23 08:36 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +      char* cdata = (char*)command.c_str();
because i need the c_str in several places

2024-05-23 08:38 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +        padCompDummy.push_back(*(new Composition(material, stack, stack, 0, cx, cy, cz, dx, dy, dz)));
ok, done since its also more compact. But this is executed once when the geometry is initialized, so its not so performance sensitive

2024-05-23 08:39 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +        hCalCompDummy.push_back(*(new Composition(material, stack, stack, 0, cx, cy, cz, dx, dy, dz)));
done

2024-05-23 08:40 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +        pixelCompDummy.push_back(*(new Composition(material, stack, stack, 0, cx, cy, cz, dx, dy, dz)));
done

2024-05-23 08:40 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +        frontMatterCompDummy.push_back(*(new Composition(material, stack, stack, 0, cx, cy, cz, dx, dy, dz)));
done

2024-05-23 08:42 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +      char* cdata = (char*)command.c_str();
removed

2024-05-23 08:43 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +      char* cdata = (char*)command.c_str();
removed

2024-05-23 08:46 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +              mVirtualSegmentComposition.push_back(*(new VirtualSegment()));
done

2024-05-23 08:47 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +      char* cdata = (char*)command.c_str();
done

2024-05-23 08:47 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +              mVirtualSegmentComposition.push_back(*(new VirtualSegment()));
done

2024-05-23 08:49 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +                                                      mTowerSizeX, mTowerSizeY, tmpComp.SizeZ())));
done

2024-05-23 08:49 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +                                                              mGlobal_Pad_Size, mGlobal_Pad_Size, tmpComp.SizeZ())));
done

2024-05-23 08:52 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +                                                        tmpComp.CenterX(), tmpComp.CenterY(), center_z, mTowerSizeX, mTowerSizeY, tmpComp.SizeZ())));
done

2024-05-23 08:52 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +                                                            mGlobal_PIX_SizeX, mGlobal_PIX_SizeY, tmpComp.SizeZ())));
done

2024-05-23 08:52 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +                                                     tmpComp.SizeX(), tmpComp.SizeY(), tmpComp.SizeZ())));
done

2024-05-23 08:59 UTC, iarsene commented on Detectors/FOCAL/base/src/Geometry.cxx
> +  return false;
indeed this is a more compact form, but we need the exact opposite logic. Also, this function is not used anywhere so far, so we keep it just in case this will be needed in the future. There is also no setter that disables towers yet.
Implemented as suggested, with correction "==" -> "!="

2024-05-23 12:46 UTC, alibuild commented
Error while checking build/O2/fullCI for c4424ee791b2c93154edefd5a8326274a7475e8a at 2024-05-23 14:46:
```
## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'


## sw/BUILD/o2checkcode-latest/log
--
========== List of errors found ==========
++ GRERR=0
++ grep -v clang-diagnostic-error error-log.txt
++ grep ' error:'
/sw/SOURCES/O2/13153-slc8_x86-64/0/Detectors/FOCAL/base/src/Composition.cxx:45:14: error: use '= default' to define a trivial destructor [modernize-use-equals-default]
++ [[ 0 == 0 ]]
++ exit 1
--
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/13153/c4424ee791b2c93154edefd5a8326274a7475e8a/build_O2_fullCI/pretty.html).

2024-05-23 12:55 UTC, mfasDa submitted a review, later dismissed

2024-05-23 13:22 UTC, alibuild commented
Error while checking build/O2/fullCI for 8519c4644ed35f54818f113eeef0d37f07c5e485 at 2024-05-23 15:22:
```
## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'


## sw/BUILD/o2checkcode-latest/log
--
========== List of errors found ==========
++ GRERR=0
++ grep -v clang-diagnostic-error error-log.txt
++ grep ' error:'
/sw/SOURCES/O2/13153-slc8_x86-64/0/Detectors/FOCAL/base/src/Composition.cxx:45:14: error: use '= default' to define a trivial destructor [modernize-use-equals-default]
++ [[ 0 == 0 ]]
++ exit 1
--
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/13153/8519c4644ed35f54818f113eeef0d37f07c5e485/build_O2_fullCI/pretty.html).

2024-05-24 04:33 UTC, alibuild commented
Error while checking build/O2/fullCI for c37842b10b965a19945496dbc0f528ca3f700694 at 2024-05-24 06:33:
```
## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'


## sw/BUILD/O2-sim-challenge-test-latest/log
./tofMatchTracks.log[ERROR] Workflow crashed - PID 22774 (tof-matcher) did not exit correctly however it's not clear why. Exit code forced to 128.
./tofMatchTracks.log[ERROR]  - Device tof-matcher: pid 22774 (exit 128)
./tofMatchTracks.log[ERROR] SEVERE: Device tof-matcher (22774) returned with 128
./mchreco.log[15790:mch-error-writer]: [04:31:26][ERROR] Some Lifetime::Timeframe data got dropped starting at 1
./mchreco.log[15791:mch-track-writer]: [04:31:26][ERROR] Some Lifetime::Timeframe data got dropped starting at 1
./mchmidMatch.log[18254:muon-track-writer]: [04:31:55][ERROR] Some Lifetime::Timeframe data got dropped starting at 1
./sim-challenge.log[ERROR] Workflow crashed - PID 22774 (tof-matcher) did not exit correctly however it's not clear why. Exit code forced to 128.
./sim-challenge.log[ERROR]  - Device tof-matcher: pid 22774 (exit 128)
./sim-challenge.log[ERROR] SEVERE: Device tof-matcher (22774) returned with 128
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/37}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/38}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/40}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/42}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/43}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/45}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/46}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/47}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/48}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/49}
./digi.log[9526:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/37}
./digi.log[9526:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/38}
./digi.log[9526:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/40}
./digi.log[9526:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/42}
./digi.log[9526:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/43}
./digi.log[9526:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/45}
./digi.log[9526:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/46}
./digi.log[9526:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/47}
./digi.log[9526:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/48}
./digi.log[9526:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/49}
./digi.log[9528:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/37}
./digi.log[9528:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/38}
./digi.log[9528:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/40}
./digi.log[9528:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/42}
./digi.log[9528:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/43}
./digi.log[9528:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/45}
./digi.log[9528:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/46}
./digi.log[9528:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/47}
./digi.log[9528:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/48}
./digi.log[9528:SimReader]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/49}
./digi.log[9543:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/37}
./digi.log[9543:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/38}
./digi.log[9543:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/40}
./digi.log[9543:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/42}
[0 more errors; see full log]
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/13153/c37842b10b965a19945496dbc0f528ca3f700694/build_O2_fullCI/pretty.html).

2024-05-24 08:53 UTC, mfasDa commented
CI error unrelated

2024-05-24 08:54 UTC, mfasDa approved these changes

2024-05-24 08:56 UTC, merged