TPC: dEdx calculation class is extended
AliceO2Group/AliceO2 pull request #13255
Opened 2024-06-28 08:51 UTC by tubagundem

Standalone dEdx calculation class is extended:

- New subthreshold cluster treatment is added.
- Cluster mask is implemented to exclude single, edge, split and subthreshold clusters from dEdx calculation. Also an option to exclude sector boundaries from subthreshold cluster treatment is added.
-  `o2::gpu::GPUO2InterfaceRefit::fillSharedClustersAndOccupancyMap` is added for the function `RefitTrackAsGPU`

2024-07-04 19:08 UTC, wiechula requested changes

2024-07-04 19:08 UTC, wiechula commented on Detectors/TPC/calibration/src/CalculatedEdx.cxx
> +    auto fLandau = new TF1("fLandau", "TMath::Landau(x, 50, 10)", 0, 200);
This is a memory leak, since the function is never deleted. And it is called even for each track ...
I propose to simply make it a member of the class:
```
TF1 mLandau{"fLandau", "TMath::Landau(x, 50, 10)", 0, 200};
```
Also, I would make the range as small as possible to reduce compute time. So instead of 200, use the maximum expected value of minChargeXXX.

2024-07-04 19:08 UTC, wiechula commented on Detectors/TPC/calibration/src/CalculatedEdx.cxx
> +    gRandom->SetSeed(0);
Should go to the constructor, or separate function that must be called before. It does not make sense to call this for every track ...

2024-07-04 19:08 UTC, wiechula commented on Detectors/TPC/calibration/src/CalculatedEdx.cxx
> +  else if (method == 2) {
I'm not sure any more if this makes really sense, since the landau will manly produce values with minCharge:
```
TF1 mLandau{"fLandau", "TMath::Landau(x, 50, 10)", 0, 20};
TH1F h1("h1","",100,0,20);
for (int i=0;i<1000;++i) h1.Fill(mLandau.GetRandom(0, 5));
h1.GetMean();
(double) 4.6884566
h1.Draw();
```
![image](https://github.com/AliceO2Group/AliceO2/assets/11199190/caa9ab28-d2f2-48cd-940b-827d42a93586)

2024-07-04 19:08 UTC, wiechula commented on Detectors/TPC/calibration/src/CalculatedEdx.cxx
> +    map[GEMstack::OROC3gem] = 3;
I don't think a mapping is needed:
```suggestion
   const int stackNumber = static_cast<int>(stack);
```

2024-07-04 19:08 UTC, wiechula commented on Detectors/TPC/calibration/src/CalculatedEdx.cxx
> +    }
Why ist there mainly copy'n'paste of this 4 times below? I think can be done in a more concise way.

2024-07-04 19:08 UTC, wiechula commented on Detectors/TPC/calibration/src/CalculatedEdx.cxx
> +  calibTrackTopology.loadFromFile(TString::Format("%s/TPC/Calib/TopologyGainPiecewise/snapshot.root", localCCDBFolder), "ccdb_object");
```suggestion
  calibTrackTopology.loadFromFile(fmt::format("{}/TPC/Calib/TopologyGainPiecewise/snapshot.root", localCCDBFolder), "ccdb_object");
```

2024-07-04 19:08 UTC, wiechula commented on Detectors/TPC/calibration/src/CalculatedEdx.cxx
> +  TFile* gainMapFile = TFile::Open(TString::Format("%s/TPC/Calib/PadGainFull/snapshot.root", localCCDBFolder));
```suggestion
  std::unique_ptr<TFile> gainMapFile(TFile::Open(fmt::format("{}/TPC/Calib/PadGainFull/snapshot.root", localCCDBFolder).data()));
```

2024-07-04 19:08 UTC, wiechula commented on Detectors/TPC/calibration/src/CalculatedEdx.cxx
> +    std::cout << "Using file: " << gainMapFile->GetName() << std::endl;
```suggestion
    LOGP(info, "Using file: {}", gainMapFile->GetName());
```

2024-07-04 19:08 UTC, wiechula commented on Detectors/TPC/calibration/src/CalculatedEdx.cxx
> +    o2::tpc::CalDet<float>* gainMap = (o2::tpc::CalDet<float>*)gainMapFile->Get("ccdb_object");
Does this really work?
```suggestion
    std::unique_ptr<o2::tpc::CalDet<float>> gainMap(gainMapFile->Get<o2::tpc::CalDet<float>>("ccdb_object");
```

2024-07-04 19:08 UTC, wiechula commented on Detectors/TPC/calibration/src/CalculatedEdx.cxx
> +
The same comments as above apply to all file access below.

2024-07-04 19:08 UTC, wiechula commented on Detectors/TPC/calibration/src/CalculatedEdx.cxx
> +    o2::tpc::CalDet<float>* gainMapResidual = (o2::tpc::CalDet<float>*)gainMapResidualFile->Get("ccdb_object");
The object in `PadGainResidual` is a `std::unordered_map<string,o2::tpc::CalDet<float> >`
You will need to access the member `GainMap` inside.

2024-07-12 09:05 UTC, tubagundem commented
I added two new parameters to limit `minChargeTot` and `minChargeMax` values when handling subthreshold clusters. Sometimes, the algorithm finds subthreshold clusters in high dEdx tracks, but the minimum charge is too high, indicating the cluster might be lost for another reason.

In the screenshot below, you can see the algorithm detects three subthreshold clusters for a high dEdx track, and both `minChargeTot` and `minChargeMax` values are too high. In this case, virtual charges should not be added to the track.

![image](https://github.com/user-attachments/assets/fab76807-b9f9-4a58-a51f-e17bfa2fb1fd)

2024-08-18 01:07 UTC, closed without merging