TPC: improving simulation of distortions in MC
AliceO2Group/AliceO2 pull request #13345
Opened 2024-08-01 14:50 UTC by matthias-kleiner

- adding option to recalculate (merging) the distortions in case of large scaling
- accessing the distortions of the derivative map at the distorted position for better consistency with corrections
- optimizing default parameters for calculating distortions/corrections

2024-08-07 13:02 UTC, wiechula requested changes

2024-08-07 13:02 UTC, wiechula commented on Detectors/TPC/simulation/src/Digitizer.cxx
> +  if (!mSpaceCharge || !mSpaceCharge) {
```suggestion
  if (!mSpaceCharge || !mSpaceChargeDer) {
```

2024-08-07 13:02 UTC, wiechula commented on Detectors/TPC/spacecharge/src/SpaceCharge.cxx
> +  const auto& scScale = (type == Type::Distortions) ? scSCale->mInterpolatorGlobalCorr[side] : scSCale->mInterpolatorGlobalDist[side];
I find using two so similar variable names `scScale` and `scSCale` a bit dangerous. Perhaps you can find a better naming for one of them.

2024-08-07 13:09 UTC, wiechula commented
+async-label async-2023-pbpb-apass4

2024-08-07 15:58 UTC, matthias-kleiner commented
Thanks for the comments @wiechula . I changed the code accordingly

2024-08-07 16:46 UTC, alibuild commented
Error while checking build/O2/fullCI for 39b66dac2da83bc37e266d497ce45636b0e696d9 at 2024-08-07 18:45:
```
## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'


## sw/BUILD/O2-sim-challenge-test-latest/log
./tofMatchTracks.log[ERROR] Workflow crashed - PID 21002 (tof-matcher) did not exit correctly however it's not clear why. Exit code forced to 128.
./tofMatchTracks.log[ERROR]  - Device tof-matcher: pid 21002 (exit 128)
./tofMatchTracks.log[ERROR] SEVERE: Device tof-matcher (21002) returned with 128
./mchreco.log[13749:mch-error-writer]: [16:43:48][ERROR] Some Lifetime::Timeframe data got dropped starting at 1
./mchreco.log[13750:mch-track-writer]: [16:43:48][ERROR] Some Lifetime::Timeframe data got dropped starting at 1
./sim-challenge.log[ERROR] Workflow crashed - PID 21002 (tof-matcher) did not exit correctly however it's not clear why. Exit code forced to 128.
./sim-challenge.log[ERROR]  - Device tof-matcher: pid 21002 (exit 128)
./sim-challenge.log[ERROR] SEVERE: Device tof-matcher (21002) returned with 128
./midreco.log[15669:MIDRecoWriter]: [16:44:17][ERROR] Some Lifetime::Timeframe data got dropped starting at 1
./mchmidMatch.log[16489:muon-track-writer]: [16:44:25][ERROR] Some Lifetime::Timeframe data got dropped starting at 1
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/37}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/38}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/40}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/42}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/43}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/45}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/46}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/47}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/48}
./digi.log[ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/49}
./digi.log[7390:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/37}
./digi.log[7390:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/38}
./digi.log[7390:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/40}
./digi.log[7390:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/42}
./digi.log[7390:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/43}
./digi.log[7390:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/45}
./digi.log[7390:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/46}
./digi.log[7390:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/47}
./digi.log[7390:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/48}
./digi.log[7390:internal-dpl-ccdb-backend]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/49}
./digi.log[7388:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/37}
./digi.log[7388:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/38}
./digi.log[7388:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/40}
./digi.log[7388:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/42}
./digi.log[7388:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/43}
./digi.log[7388:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/45}
./digi.log[7388:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/46}
./digi.log[7388:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/47}
./digi.log[7388:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/48}
./digi.log[7388:internal-dpl-clock]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/49}
./digi.log[7393:TPCDigitizer_0]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/37}
./digi.log[7393:TPCDigitizer_0]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/38}
./digi.log[7393:TPCDigitizer_0]: [ERROR] Found duplicate input binding with different spec.:collisioncontext {SIM/COLLISIONCONTEXT/40}
[0 more errors; see full log]
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/13345/39b66dac2da83bc37e266d497ce45636b0e696d9/build_O2_fullCI/pretty.html).

2024-08-08 07:53 UTC, wiechula approved these changes
Thanks @matthias-kleiner !

2024-08-08 08:35 UTC, wiechula commented
@shahor02 , can you please check and approve.

2024-08-08 09:02 UTC, shahor02 approved these changes

2024-08-08 09:02 UTC, merged

2024-08-26 12:12 UTC, chiarazampolli commented
Label removed, PR is in async-v1-01-16.