Ctpdev: print input and class rates in case of big payload
AliceO2Group/AliceO2 pull request #13518
Opened 2024-09-16 14:20 UTC by lietava

2024-09-16 14:52 UTC, lietava commented
@aferrero2707 - printing inputs and classes for fatal

2024-09-19 14:23 UTC, lietava commented
@aferrero2707 , reminder, please, have a look. It is almost trivial.

2024-09-22 21:07 UTC, aferrero2707 requested changes
@lietava I double-checked the code locally and I confirm it works as expected.
I just left a couple of suggested changes that allow to print the inputs and classes in reverse order, wit the highest rates printed first.

2024-09-22 21:07 UTC, aferrero2707 commented on Detectors/CTP/reconstruction/src/RawDataDecoder.cxx
```suggestion
#include <boost/range/adaptor/reversed.hpp>
```

2024-09-22 21:07 UTC, aferrero2707 commented on Detectors/CTP/reconstruction/src/RawDataDecoder.cxx
> +  for (auto const& r : ratesmap) {
```suggestion
  for (auto const& r : boost::adaptors::reverse(ratesmap)) {
```

2024-09-22 21:07 UTC, aferrero2707 commented on Detectors/CTP/reconstruction/src/RawDataDecoder.cxx
> +  for (auto const& r : ratesmapC) {
```suggestion
  for (auto const& r : boost::adaptors::reverse(ratesmapC)) {
```

2024-09-22 21:07 UTC, aferrero2707 commented on Detectors/CTP/workflow/src/RawDecoderSpec.cxx
> +        LOG(error) << "Input data size bigger than threshold:" << mMaxInputSize << " < " << payloadSize << " ecoding TF and exiting.";
```suggestion
        LOG(error) << "Input data size bigger than threshold: " << mMaxInputSize << " < " << payloadSize << " ecoding TF and exiting.";
```

2024-09-23 14:33 UTC, lietava commented
@shahor02 : please, merge or comment.

2024-09-23 19:39 UTC, shahor02 approved these changes

2024-09-23 19:39 UTC, merged