[TOF] update matcher
AliceO2Group/AliceO2 pull request #13621
Opened 2024-10-23 09:29 UTC by njacazio

2024-10-25 08:45 UTC, njacazio commented
@shahor02 could you please have a look?

2024-10-25 08:45 UTC, njacazio commented
@noferini

2024-10-30 12:39 UTC, shahor02 requested changes

2024-10-30 12:39 UTC, shahor02 commented on DataFormats/Reconstruction/include/ReconstructionDataFormats/MatchInfoTOF.h
>    ClassDefNV(MatchInfoTOF, 6);
Could you increment the class version to 7?

2024-10-30 12:40 UTC, njacazio commented on DataFormats/Reconstruction/include/ReconstructionDataFormats/MatchInfoTOF.h
>    ClassDefNV(MatchInfoTOF, 6);
Done!

2024-11-01 00:27 UTC, alibuild commented
Error while checking build/O2/fullCI for 3432fcdefb3ae76051ed97c7cbba0379be805569 at 2024-11-01 01:27:
```
## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'


## sw/BUILD/O2-sim-challenge-test-latest/log
./sim-challenge.log[FATAL] Alien Token Check failed - Please get an alien token before running with https CCDB endpoint, or alice-ccdb.cern.ch!
./grp.log[FATAL] Alien Token Check failed - Please get an alien token before running with https CCDB endpoint, or alice-ccdb.cern.ch!


## sw/BUILD/o2checkcode-latest/log
--
========== List of errors found ==========
++ GRERR=0
++ grep -v clang-diagnostic-error error-log.txt
++ grep ' error:'
++ GRERR=1
++ [[ 1 == 0 ]]
++ mkdir -p /sw/INSTALLROOT/a64d419bf4ca73f0085bb0f1263589d29abc898e/slc8_x86-64/o2checkcode/1.0-local758/etc/modulefiles
++ cat
--
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/13621/3432fcdefb3ae76051ed97c7cbba0379be805569/build_O2_fullCI/pretty.html).

2024-11-05 11:16 UTC, njacazio commented
Hi @shahor02 this should be ready to merge now

2024-11-05 11:56 UTC, shahor02 approved these changes

2024-11-05 11:56 UTC, merged