AFIT-107: new RCT bad flags for FT0
AliceO2Group/AliceO2 pull request #13698
Opened 2024-11-15 13:33 UTC by afurs

2024-11-15 13:35 UTC, afurs commented
@jotwinow @andreasmolander please review it

2024-11-16 17:16 UTC, jotwinow submitted a review, later dismissed

2024-11-18 09:27 UTC, knopers8 requested changes
Well, I will let @JianLIUhep have the final call, but this contradicts what QC flags are for. The flags should define the effect on the usability of the data for analyzers. The "comment" is used to explain what went wrong. Here you are mistaking cause with effect.

This idea was presented many times for various audiences and I never received objection for this proposal. If you need a bunch of "const strings" for specifying the cause of bad data, I would rather propose that we allow for a set of predefined comments. The flags themselves should stay for the analyzers to programmatically determine whether they can use a given timespan of data or not.

2024-11-18 09:29 UTC, knopers8 commented
Also, all of those flags are detector-specific. Do they have to be? If we continue this road, we will end up with tens or hundreds of flags which mean the same, but for different detectors.

2024-11-18 13:11 UTC, afurs commented
> The "comment" is used to explain what went wrong. Here you are mistaking cause with effect.

Indeed, I exactly put into comments explanation of what went wrong, e.g. `Bad FT0 Data Consistency` -> means that FT0 haven't sent data from some modules - explanation as it is.

> The flags themselves should stay for the analyzers to programmatically determine whether they can use a given timespan of data or not.

I agree, for instance `Bad FT0 Time Ofsset Calibration` -> means that FT0's mean time will be incorrect in AOD -> collision time and z-vertex are incorrect. But FT0's trigger data could be fine, and then analyzer shall decide does he need FT0's time or not.

> Also, all of those flags are detector-specific. Do they have to be? If we continue this road, we will end up with tens or hundreds of flags which mean the same, but for different detectors.

`BadFT0DataConsistency`, `BadFT0HWSettings`, `BadFT0RecoSettings` - also can be used for FV0 and FDD. First two because of common electronics. Third - reco principle almost the same among all three FIT detectors.

`BadFT0TimeOfssetCalibration`, `BadFT0TimeSlewingCalibration` - they are only specific for FT0.

P.S. I got from Elena Botta request to implement bad quality flags for FT0 for RCT

2024-11-18 13:56 UTC, knopers8 commented
> Indeed, I exactly put into comments explanation of what went wrong, e.g. Bad FT0 Data Consistency -> means that FT0 haven't sent data from some modules - explanation as it is.

Apologies, I assume you are familiar with the [documentation](https://github.com/AliceO2Group/AliceO2/tree/dev/DataFormats/QualityControl#quality-control-flag-structure) of this module. By "comment" I meant the comment field of `QualityControlFlag`. I see you even used it yourself to add some details: https://github.com/AliceO2Group/QualityControl/blob/aaf01a6592ad6a026aa31d8b74df5796360c6388/Modules/FIT/FT0/src/FractionCheck.cxx#L109 , which is good.

Would you be able to come up with a phrase which describes how inconsistent FT0 data affects AODs?

> I agree, for instance Bad FT0 Time Ofsset Calibration -> means that FT0's averaged time will be incorrect in AOD -> collision time and z-vertex are incorrect. But FT0's trigger data could be fine, and then analyzer shall decide does he need FT0's time or not.

First of all, please correct the typo, it's "Offset", not "Ofsset". Then, as far as I understand, the effect on data is "Incorrect time offset", while "bad time offset calibration" is the cause. Does this sound reasonable to you?

> BadFT0DataConsistency, BadFT0HWSettings, BadFT0RecoSettings - also can be used for FV0 and FDD. First two because of common electronics. Third - reco principle almost the same among all three FIT detectors.

Why not for any detector? Anyway, the assigned flags are associated with a detector and I can imagine that any detector has hardware that can be set up incorrectly. This being said, `BadHWSettings` and `BadRecoSettings` seem again like causes, not effects. These could be stated in `QualityControlFlag::mComment` (and the corresponding field in RCT).

> P.S. I got from Elena Botta request to implement bad quality flags for FT0 for RCT

That's perfectly fine and I am happy that there is a proposal to extend this list. However, new flags have to be carefully reviewed before adding them, because whatever we will add, it will stay with us for the rest of Run 3&4 at least.

2024-11-18 15:04 UTC, afurs commented
@knopers8 Ok, I got it. Effect as flag, not cause. A have to reconsider my last commit. I guess the most questions will disappear after.

Concerning data inconsistency in FIT, I see several items for FT0's (also can be used for FV0 and FDD):
1. Bad amplitude;
2. Bad time;
3. Bad BCID;
4. Bad trigger signals

2024-11-18 16:05 UTC, JianLIUhep commented
Hi @afurs, 

We’d like to clarify a few points to ensure we’re on the same page.

Our original email was intended to gather information on which of the existing 13 flags are being used (or planned to be used) for each detector. We don’t intend to add new flags unless strictly necessary. These details could be added as comments to the Bad flag, and we could then communicate to PWGs that, for FT0, the "Bad" flag encompasses all four possibilities (amplitude, time, BCID, trigger).

Please don’t hesitate to reach out if you have any further questions.

Thank you,
Jian and Elena

cc @knopers8

2024-11-18 16:57 UTC, afurs commented
Hello @JianLIUhep , ok, I guess I understood your point. Anyway, I provided first version of bad flags related to FT0. After discussion with @knopers8 I realized that maybe better to use list of 4 items which I presented above. For me any variant is OK.

I checked original email again:
`We are interested in understanding if bad flags need to be split in different groups meaning that one group is for runs that are for sure not useful for analyses and another one is for runs that could be anyway of interest.`
I would say that in first version of the code: `BadRecoSettings`, `BadFT0TimeOfssetCalibration` and `BadFT0TimeSlewingCalibration` - can be fixed in next pass after broken one (second group)
In case of `BadHWSettings` and `BadDataConsistency` - depends on certain situation, could be first or second group.

Please let me know which variant you would like to have. Also we can move discussion to the related ticket https://its.cern.ch/jira/browse/AFIT-107

2024-12-04 11:10 UTC, alibuild commented
Error while checking build/O2/fullCI_slc9 for 43099b790dcc1e484d24fda6815d44c4d72ca35b at 2024-12-04 12:10:
```
## sw/BUILD/O2-latest/log
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/13698/43099b790dcc1e484d24fda6815d44c4d72ca35b/build_O2_fullCI_slc9/pretty.html).

2024-12-12 14:27 UTC, alibuild commented
Error while checking build/O2/fullCI for 43099b790dcc1e484d24fda6815d44c4d72ca35b at 2024-12-12 15:27:
```
## sw/BUILD/O2-latest/log
c++: error: unrecognized command-line option '--rtlib=compiler-rt'
c++: error: unrecognized command-line option '--rtlib=compiler-rt'


## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/13698-slc8_x86-64/0/Common/TableProducer/Converters/trackQA002Converter.cxx:25:32: error: 'tracksQA_000' was not declared in this scope; did you mean 'tracksQA_002'?
/sw/SOURCES/O2Physics/13698-slc8_x86-64/0/Common/TableProducer/Converters/trackQA002Converter.cxx:59:32: error: 'tracksQA_001' was not declared in this scope; did you mean 'tracksQA_002'?
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/13698/43099b790dcc1e484d24fda6815d44c4d72ca35b/build_O2_fullCI/pretty.html).

2025-05-12 07:43 UTC, closed without merging