Changes required to display data from TPC
AliceO2Group/AliceO2 pull request #2653
Opened 2019-12-03 21:31 UTC by jmyrcha

2019-12-04 08:48 UTC, jmyrcha commented
It looks, that it did not build not because EventVisualisation - how we can retry a build/O2/o2 test?

2019-12-04 08:57 UTC, sawenzel commented
Can you please fix the codechecker errors:
```
rTPC.h:29:9: error: field declaration 'fMaxEv' does not match naming rule [aliceO2-member-name]
  Int_t fMaxEv;
        ^~~~~~~
        mMaxEv
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/EventVisualisation/Detectors/src/DataReaderTPC.cxx:44:3: error: field reference 'fMaxEv' does not match naming rule [aliceO2-member-name]
  fMaxEv = trackBuffer->size();
  ^~~~~~
  mMaxEv
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/EventVisualisation/Detectors/src/DataReaderTPC.cxx:49:10: error: field reference 'fMaxEv' does not match naming rule [aliceO2-member-name]
  return fMaxEv;
         ^~~~~~~
         mMaxEv
```
A new build will be triggered upon a code change in any case.

2019-12-04 10:31 UTC, sawenzel commented on EventVisualisation/Detectors/include/EventVisualisationDetectors/DataReaderTPC.h
> +>>>>>>> f2dea92bebb772f1eb0800290b722a2a284eb318:EventVisualisation/Detectors/include/EventVisualisationDetectors/DataReaderTPC.h
Leftover from merge. This needs to be fixed.

2019-12-04 17:39 UTC, sawenzel commented on EventVisualisation/DataConverter/include/EventVisualisationDataConverter/VisualisationCluster.h
> +  double Z() { return mCoordinates[2]; }
in general, accessor functions should be `const` annotated. This applies to many functions/changes in this PR

2019-12-04 17:39 UTC, sawenzel commented on EventVisualisation/DataConverter/include/EventVisualisationDataConverter/VisualisationEvent.h
> +  inline int GetMultiplicity() { return mMultiplicity; }
no need to put `inline` keyword; please annotate `const`

2019-12-04 17:41 UTC, sawenzel commented on EventVisualisation/DataConverter/src/VisualisationEvent.cxx
> +
trivial (one line) accessor such as getTrack / getCluster should be provided in the header

2019-12-04 17:43 UTC, sawenzel requested changes
I suggest to improve the code concerning const correctness and inlining small functions.
Would you also be able to attach a screenshot of some TPC data displayed?

2019-12-10 07:05 UTC, sawenzel approved these changes

2019-12-10 07:06 UTC, merged