TPCClusterFinder: Add gain calibration.
AliceO2Group/AliceO2 pull request #4323
Opened 2020-09-10 12:57 UTC by fweig

This PR adds gain correction of the TPC pads in the cluster finder.

@davidrohr I saw about 8-9% performance overhead in the decodeZS kernel from these changes. Using chars instead of short to pack the calibration values seems to have only a negligible effect on runtime.

2020-09-14 08:44 UTC, davidrohr requested changes
Looks ok in general, just some minor comments above + could you add also the respective code to `DumpSettings` and `ReadSettings` in `GPUChainTrackingIO.cxx`.

2020-09-14 08:44 UTC, davidrohr commented on Detectors/TPC/workflow/src/CATrackerSpec.cxx
> +
The file should be set in `GPUSettingsO2` part in `GPUSettingsList.h` avaiable as `confParam` in `CATrackerSpec.cxx`, and it should be optional, as is already the case.

2020-09-14 08:44 UTC, davidrohr commented on GPU/Common/GPUCommonMath.h
> +  GPUd() static T Clamp(const T v, const T lo, const T hi)
Should be GPUdi() for clarity when the implementation is inline.

2020-09-14 08:44 UTC, davidrohr commented on Detectors/TPC/reconstruction/test/testGPUCATracking.cxx
> +#include "TPCBase/Mapper.h"
Just a note: using the mapper is fine in principle, but a lot of the mapper functionality is available in `SliceTracker/GPUTPCGeometry.h`, which is part of the `GPUParam`. I would take as much as possible from there.

2020-09-14 11:26 UTC, fweig commented
Pushed an update that addresses these points. Added a flag `gainCalibFile` to `GPUSettingsO2`. The `TPCCFCalibration` class now uses `GPUTPCGeometry` instead of the tpc mapper.

2020-09-25 12:20 UTC, davidrohr approved these changes
This looks all ok now.
- Results are identical to before when applying a trivial gain correction and still reasonable with gain correction.
- I see a performance impact of ~25-30% during the TPC ZS decoding which translates to a ~1% total performance impact for the GPU processing, which seems reasonable for the gain correction.

@wiechula @matthias-kleiner : You can use the feature by adding to the tpc-reco-workflow command line: `--configKeyValues "GPU_global.gainCalibFile=[filename]"`, while the file should be in the format as the example you sent me.

2020-09-25 12:20 UTC, merged