new interface for 1D and 2D splines
AliceO2Group/AliceO2 pull request #4611
Opened 2020-10-16 07:34 UTC by sgorbuno

new interface for 1D and 2D splines

2020-10-16 08:52 UTC, davidrohr commented
Hi @sgorbuno : Could you explain a bit the changes? I see that you have added more templating for double/float, but in several places you also switched double to float.
I assume this is only for the part that computes the map?

2020-10-16 12:16 UTC, sgorbuno commented
Hi @davidrohr ,  
Right, double is only applied when the map is computed. I realized that there is no reason to use float there.

New splines have 3 different specifications:
1: Spline2D<float,5> -  spline with 5 output dimensions, which are known during compile time
2. Spline2D<float> s(5) - spline with 5 output dimensions, which are only known during runtime
3. Spline2D<float,-10> s(5) - same as 2., but it is known during compile time that N dimensions is limited to 10.
It might be needed to avoid the allocation of variable-size arrays.

I also took care that constructors of one specification are not visible from another specification, but at the same time, the actual code is not duplicated anywhere. In order to do so, I had to create several levels of templates. 

Also before some of the methods had two versions - with and without index-out-of-range check.
I merged them into templates with optional SafetyLevel parameter.

2020-10-16 12:20 UTC, sgorbuno commented
@davidrohr, I forgot to mention - I verified that the new code compiles with AliRoot.

2020-10-16 12:25 UTC, sgorbuno commented
@davidrohr 
To avoid the code duplication for "constexpr int" and "int" cases of N dimensions, I applied such a trick:

  /// An expression getYdim(YisPositiveTbool{},int) is either an integer or a constexpr integer,
  /// depending on the YisPositiveT value
  ///
  typedef std::integral_constant<bool, YisPositiveT> YisPositiveTbool;
  static constexpr int getYdim(std::true_type, int) { return YdimT; }
  static int getYdim(std::false_type, int nYdim) { return nYdim; }

2020-10-22 21:12 UTC, davidrohr requested changes
Hi @sgorbuno : Unfortunately it doesn't compile on the GPU and also it breaks the standalone benchmark. I am attaching a patch to fix the standalone compilation: 
[splines-standalone.patch.tar.gz](https://github.com/AliceO2Group/AliceO2/files/5425835/splines-standalone.patch.tar.gz) .
 I have marked several GPU problems inline (unfortunately the GPU CI is currently not working correctly, normally you should see the errors there.) Some more GPU compilation errors by OpenCLnot marked inline are:
```
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/..//Base/opencl-common/GPUReconstructionOCL.cl:72:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/Base/GPUReconstructionIncludesDevice.h:32:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/SliceTracker/GPUTPCTracker.cxx:26:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCConvert/GPUTPCConvertImpl.h:19:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastTransform.h:21:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:19:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2D.h:19:
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1D.h:162:18: error: use of class template 'Spline1DSpec' requires template arguments; argument deduction not allowed in function prototype
  Spline1D(const Spline1DSpec&) CON_DELETE;
                 ^~~~~~~~~~~~
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1DSpec.h:50:7: note: template is declared here
class Spline1DSpec;
      ^
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/..//Base/opencl-common/GPUReconstructionOCL.cl:72:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/Base/GPUReconstructionIncludesDevice.h:32:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/SliceTracker/GPUTPCTracker.cxx:26:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCConvert/GPUTPCConvertImpl.h:19:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastTransform.h:21:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:19:
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2D.h:98:18: error: use of class template 'Spline2DSpec' requires template arguments; argument deduction not allowed in function prototype
  Spline2D(const Spline2DSpec&) CON_DELETE;
                 ^~~~~~~~~~~~
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h:54:7: note: template is declared here
class Spline2DSpec;
      ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h:244:33: error: type 'o2::gpu::Spline2DSpec<float, 3, true, true, false, false>::SafetyLevel' (aka 'int') cannot be used prior to '::' because it has no members
  template <SafetyLevel SafeT = SafetyLevel::kSafe>
                                ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h:318:12: note: in instantiation of template class 'o2::gpu::Spline2DSpec<float, 3, true, true, false, false>' requested here
  : public Spline2DSpec<DataT, YdimT, true, true, false, false>
           ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2D.h:77:12: note: in instantiation of template class 'o2::gpu::Spline2DSpec<float, 3, false, true, false, false>' requested here
  : public Spline2DSpec<DataT, YdimT, false, (YdimT >= 0), (YdimT == 1), (YdimT == -999999)>
           ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:250:22: note: in instantiation of template class 'o2::gpu::Spline2D<float, 3>' requested here
  return mScenarioPtr[rowInfo.splineScenarioID];
                     ^
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/..//Base/opencl-common/GPUReconstructionOCL.cl:72:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/Base/GPUReconstructionIncludesDevice.h:32:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/SliceTracker/GPUTPCTracker.cxx:26:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCConvert/GPUTPCConvertImpl.h:19:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastTransform.h:21:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:19:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2D.h:20:
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h:373:33: error: type 'o2::gpu::Spline2DSpec<float, 3, false, true, false, false>::SafetyLevel' (aka 'int') cannot be used prior to '::' because it has no members
  template <SafetyLevel SafeT = SafetyLevel::kSafe>
                                ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2D.h:77:12: note: in instantiation of template class 'o2::gpu::Spline2DSpec<float, 3, false, true, false, false>' requested here
  : public Spline2DSpec<DataT, YdimT, false, (YdimT >= 0), (YdimT == 1), (YdimT == -999999)>
           ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:250:22: note: in instantiation of template class 'o2::gpu::Spline2D<float, 3>' requested here
  return mScenarioPtr[rowInfo.splineScenarioID];
                     ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:273:16: error: no member named 'getGridX1' in 'o2::gpu::Spline2D<float, 3>'
  su *= spline.getGridX1().getUmax();
        ~~~~~~ ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:274:16: error: no member named 'getGridX2' in 'o2::gpu::Spline2D<float, 3>'
  sv *= spline.getGridX2().getUmax();
        ~~~~~~ ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:276:10: error: no member named 'interpolateU' in 'o2::gpu::Spline2D<float, 3>'
  spline.interpolateU(splineData, su, sv, dxuv);
  ~~~~~~ ^
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/..//Base/opencl-common/GPUReconstructionOCL.cl:72:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/Base/GPUReconstructionIncludesDevice.h:32:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/SliceTracker/GPUTPCTracker.cxx:26:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCConvert/GPUTPCConvertImpl.h:19:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastTransform.h:21:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:19:
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2D.h:20:
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h:244:33: error: type 'o2::gpu::Spline2DSpec<float, 1, true, true, false, false>::SafetyLevel' (aka 'int') cannot be used prior to '::' because it has no members
  template <SafetyLevel SafeT = SafetyLevel::kSafe>
                                ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h:318:12: note: in instantiation of template class 'o2::gpu::Spline2DSpec<float, 1, true, true, false, false>' requested here
  : public Spline2DSpec<DataT, YdimT, true, true, false, false>
           ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h:395:12: note: in instantiation of template class 'o2::gpu::Spline2DSpec<float, 1, false, true, false, false>' requested here
  : p [...]

2020-10-22 21:12 UTC, davidrohr commented on GPU/TPCFastTransformation/Spline2DSpec.h
> +    const TGridX1& gridX1 = *((const TGridX1*)&mGridX1);
This (and line 300) give compiler warning about aliasing violations
```
In file included from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2D.h:20,
                 from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:19,
                 from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastTransform.h:21,
                 from /home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCConvert/GPUTPCConvertImpl.h:19,
                 from /home/qon/alice/O2/GPU/GPUTracking/SliceTracker/GPUTPCTracker.cxx:26:
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h: In instantiation of ‘void o2::gpu::Spline2DSpec<DataT, YdimT, true, YisPositiveT, YisOneT, YisAbsent>::interpolateU(int, const DataT*, DataT, DataT, DataT*) const [with typename o2::gpu::Spline2DSpec<DataT, YdimT, true, YisPositiveT, YisOneT, YisAbsent>::TBase::SafetyLevel SafeT = o2::gpu::Spline1DContainer<float>::kSafe; DataT = float; int YdimT = 3; bool YisPositiveT = true; bool YisOneT = false; bool YisAbsent = false]’:
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h:377:40:   required from ‘void o2::gpu::Spline2DSpec<DataT, YdimT, false, true, false, false>::interpolateU(const DataT*, DataT, DataT, DataT*) const [with typename o2::gpu::Spline2DSpec<DataT, YdimT, false, true, false, false>::TVeryBase::SafetyLevel SafeT = o2::gpu::Spline1DContainer<float>::kSafe; DataT = float; int YdimT = 3]’
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:276:47:   required from here
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h:290:48: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  290 |     const TGridX1& gridX1 = *((const TGridX1*)&mGridX1);
      |                                                ^~~~~~~
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h:300:48: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  300 |     const TGridX2& gridX2 = *((const TGridX2*)&mGridX2);
```

2020-10-22 21:12 UTC, davidrohr commented on GPU/TPCFastTransformation/Spline1DSpec.h
> +GPUdi() void Spline1DContainer<DataT>::setXrange(DataT xMin, DataT xMax)
CUDA Compilation errors: (unfortunately the CI is currently not working, so I ran it manually)
```
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1DSpec.h(256): warning: a __host__ function("o2::gpu::Spline1DContainer<DataT>::setXrange") redeclared with __device__, hence treated as a __host__ __device__ function

/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1D.h(162): error: argument list for class template "o2::gpu::Spline1DSpec" is missing

/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2D.h(98): error: argument list for class template "o2::gpu::Spline2DSpec" is missing

/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1D.h(166): warning: "o2::gpu::Spline1D<DataT, YdimT>::operator o2::gpu::Spline1D<float, -999999> &() [with DataT=float, YdimT=-999999]" will not be called for implicit or explicit conversions
          detected during:
            instantiation of class "o2::gpu::Spline1D<DataT, YdimT> [with DataT=float, YdimT=-999999]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(70): here
            instantiation of class "o2::gpu::Spline2DContainer<DataT> [with DataT=float]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(226): here
            instantiation of class "o2::gpu::Spline2DSpec<DataT, YdimT, true, YisPositiveT, YisOneT, YisAbsent> [with DataT=float, YdimT=3, YisPositiveT=true, YisOneT=false, YisAbsent=false]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(318): here
            instantiation of class "o2::gpu::Spline2DSpec<DataT, YdimT, false, true, false, false> [with DataT=float, YdimT=3]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2D.h(77): here
            instantiation of class "o2::gpu::Spline2D<DataT, YdimT> [with DataT=float, YdimT=3]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h(250): here

/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1D.h(169): warning: "o2::gpu::Spline1D<DataT, YdimT>::operator const o2::gpu::Spline1D<float, -999999> &() const [with DataT=float, YdimT=-999999]" will not be called for implicit or explicit conversions
          detected during:
            instantiation of class "o2::gpu::Spline1D<DataT, YdimT> [with DataT=float, YdimT=-999999]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(70): here
            instantiation of class "o2::gpu::Spline2DContainer<DataT> [with DataT=float]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(226): here
            instantiation of class "o2::gpu::Spline2DSpec<DataT, YdimT, true, YisPositiveT, YisOneT, YisAbsent> [with DataT=float, YdimT=3, YisPositiveT=true, YisOneT=false, YisAbsent=false]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(318): here
            instantiation of class "o2::gpu::Spline2DSpec<DataT, YdimT, false, true, false, false> [with DataT=float, YdimT=3]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2D.h(77): here
            instantiation of class "o2::gpu::Spline2D<DataT, YdimT> [with DataT=float, YdimT=3]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h(250): here

/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(268): error: expression must have a constant value
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(268): note: the value of variable "maxYdim4"
(249): here cannot be used as a constant
          detected during:
            instantiation of "void o2::gpu::Spline2DSpec<DataT, YdimT, true, YisPositiveT, YisOneT, YisAbsent>::interpolateU(int, const DataT *, DataT, DataT, DataT *) const [with DataT=float, YdimT=3, YisPositiveT=true, YisOneT=false, YisAbsent=false, SafeT=o2::gpu::Spline1DContainer<float>::kSafe]" 
(377): here
            instantiation of "void o2::gpu::Spline2DSpec<DataT, YdimT, false, true, false, false>::interpolateU(const DataT *, DataT, DataT, DataT *) const [with DataT=float, YdimT=3, SafeT=(o2::gpu::Spline1DContainer<float>::SafetyLevel)1]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h(276): here

/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(269): error: expression must have a constant value
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(269): note: the value of variable "maxYdim4"
(249): here cannot be used as a constant
          detected during:
            instantiation of "void o2::gpu::Spline2DSpec<DataT, YdimT, true, YisPositiveT, YisOneT, YisAbsent>::interpolateU(int, const DataT *, DataT, DataT, DataT *) const [with DataT=float, YdimT=3, YisPositiveT=true, YisOneT=false, YisAbsent=false, SafeT=o2::gpu::Spline1DContainer<float>::kSafe]" 
(377): here
            instantiation of "void o2::gpu::Spline2DSpec<DataT, YdimT, false, true, false, false>::interpolateU(const DataT *, DataT, DataT, DataT *) const [with DataT=float, YdimT=3, SafeT=(o2::gpu::Spline1DContainer<float>::SafetyLevel)1]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h(276): here

/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(270): error: expression must have a constant value
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(270): note: the value of variable "maxYdim4"
(249): here cannot be used as a constant
          detected during:
            instantiation of "void o2::gpu::Spline2DSpec<DataT, YdimT, true, YisPositiveT, YisOneT, YisAbsent>::interpolateU(int, const DataT *, DataT, DataT, DataT *) const [with DataT=float, YdimT=3, YisPositiveT=true, YisOneT=false, YisAbsent=false, SafeT=o2::gpu::Spline1DContainer<float>::kSafe]" 
(377): here
            instantiation of "void o2::gpu::Spline2DSpec<DataT, YdimT, false, true, false, false>::interpolateU(const DataT *, DataT, DataT, DataT *) const [with DataT=float, YdimT=3, SafeT=(o2::gpu::Spline1DContainer<float>::SafetyLevel)1]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h(276): here

/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(271): error: expression must have a constant value
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(271): note: the value of variable "maxYdim4"
(249): here cannot be used as a constant
          detected during:
            instantiation of "void o2::gpu::Spline2DSpec<DataT, YdimT, true, YisPositiveT, YisOneT, YisAbsent>::interpolateU(int, const DataT *, DataT, DataT, DataT *) const [with DataT=float, YdimT=3, YisPositiveT=true, YisOneT=false, YisAbsent=false, SafeT=o2::gpu::Spline1DContainer<float>::kSafe]" 
(377): here
            instantiation of "void o2::gpu::Spline2DSpec<DataT, YdimT, false, true, false, false>::interpolateU(const DataT *, DataT, DataT, DataT *) const [with DataT=float, YdimT=3, SafeT=(o2::gpu::Spline1DContainer<float>::SafetyLevel)1]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h(276): here

/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(287): error: expression must have a constant value
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(287): note: the value of variable "maxYdim4"
(249): here cannot be used as a constant
          detected during:
            instantiation of "void o2::gpu::Spline2DSpec<DataT, YdimT, true, YisPositiveT, YisOneT, YisAbsent>::interpolateU(int, const DataT *, DataT, DataT, DataT *) const [with DataT=float, YdimT=3, YisPositiveT=true,  [...]

2020-10-22 21:12 UTC, davidrohr commented on GPU/TPCFastTransformation/Spline1DSpec.h
> +  typedef std::integral_constant<bool, YisPositiveT> YisPositiveTbool;
GPU compilation on OpenCL fails due to usage of the std namespace.
All system headers and usage of `std::` should be masked with `#ifndef GPUCA_GPUCODE_DEVICE`:
```
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1DSpec.h:284:11: error: use of undeclared identifier 'std'
  typedef std::integral_constant<bool, YisPositiveT> YisPositiveTbool;
          ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1DSpec.h:285:32: error: use of undeclared identifier 'std'
  static constexpr int getYdim(std::true_type, int) { return YdimT; }
                               ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1DSpec.h:286:22: error: use of undeclared identifier 'std'
  static int getYdim(std::false_type, int nYdim) { return nYdim; }
                     ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1DSpec.h:291:11: error: use of undeclared identifier 'std'
  typedef std::integral_constant<bool, YisAbsentT> YisAbsentTbool;
          ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1DSpec.h:292:25: error: use of undeclared identifier 'std'
  static int getMaxYdim(std::true_type, int nYdim) { return nYdim; }
                        ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1DSpec.h:293:35: error: use of undeclared identifier 'std'
  static constexpr int getMaxYdim(std::false_type, int) { return abs(YdimT); }
                                  ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1DSpec.h:308:26: error: use of undeclared identifier 'YisPositiveTbool'; did you mean 'YisPositiveT'?
    auto nYdim = getYdim(YisPositiveTbool{}, inpYdim);
                         ^~~~~~~~~~~~~~~~
                         YisPositiveT                                                                                                                                                                                                                                                                                                                      
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1DSpec.h:270:43: note: 'YisPositiveT' declared here
template <typename DataT, int YdimT, bool YisPositiveT, bool YisOneT, bool YisAbsentT>
                                          ^
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline1DSpec.h:323:26: error: use of undeclared identifier 'YisPositiveTbool'; did you mean 'YisPositiveT'?
```

2020-10-24 18:45 UTC, davidrohr commented
@sgorbuno : Please note that the GPU CI is back up, so it should show you the GPU errors. And also the ctest is failing on MacOS.

2020-10-26 10:48 UTC, davidrohr commented
> static constexpr int getYdim(std::true_type, int) { return YdimT; }
> static int getYdim(std::false_type, int nYdim) { return nYdim; }
> 
> And then in the calculations:
> {
> auto nYdim = getYdim(YisPositiveTbool{}, inpYdim);

Hm, I am not 100% sure if this works on the GPU. Apparently getMaxYdim is not treated as constexpr:
```
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(267): error: expression must have a constant value
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/Spline2DSpec.h(267): note: the value of variable "maxYdim4"
(248): here cannot be used as a constant
          detected during:
            instantiation of "void o2::gpu::Spline2DSpec<DataT, YdimT, 0>::interpolateU(int, const DataT *, DataT, DataT, DataT *) const [with DataT=float, YdimT=3, SafeT=o2::gpu::Spline1DContainer<float>::kSafe]" 
(376): here
            instantiation of "void o2::gpu::Spline2DSpec<DataT, YdimT, 1>::interpolateU(const DataT *, DataT, DataT, DataT *) const [with DataT=float, YdimT=3, SafeT=(o2::gpu::Spline1DContainer<float>::SafetyLevel)1]" 
/home/qon/alice/O2/GPU/GPUTracking/Standalone/TPCFastTransformation/TPCFastSpaceChargeCorrection.h(276): here
```

2020-10-26 12:09 UTC, sgorbuno commented
@davidrohr, do you have an actual docker container with Aliroot & GPU drivers installed? I would try to compile for the GPU myself on asustest04 on asustest02.

2020-10-26 14:06 UTC, davidrohr commented
@sgorbuno : You can use davidrohr/slc8-gpu-builder

2020-10-28 10:51 UTC, sgorbuno commented
@davidrohr 
>Hm, I am not 100% sure if this works on the GPU. Apparently getMaxYdim is not treated as constexpr:

The GPU compiler doesn't allow a non-const input to a constexpr function, even when this input is not used.
ok, I found another way.

I'll mark this PR as [WIP] for a while until I fix compiler warnings from the standalone compilation.

2020-10-29 12:23 UTC, davidrohr commented
> typedef std::integral_constant<bool, YisPositiveT> YisPositiveTbool;
> static constexpr int getYdim(std::true_type, int) { return YdimT; }
> static int getYdim(std::false_type, int nYdim) { return nYdim; }
> 
> And then in the calculations:
> {
> auto nYdim = getYdim(YisPositiveTbool{}, inpYdim);
> ...
> }

Perhaps, if you want the variables to be treated as constexpr, should declare them such, e.g. constexpr auto nYdim... (I mean for the maxYdim4 the compiler is complaining about.

2020-10-29 21:10 UTC, sgorbuno commented
@davidrohr, it should be ok now.

I introduced a Switch class in SplineUtil.h for switching between constexpr int and int:

 template <bool ConditionT, int ValTrueT>
  class Switch;

template <int ValTrueT>
class SplineUtil::Switch<true, ValTrueT>
{
 public:
  GPUd() Switch(int /*valFalse*/) {}
  GPUd() static constexpr int get() { return ValTrueT; }
};

template <int ValTrueT>
class SplineUtil::Switch<false, ValTrueT>
{
 public:
  GPUd() Switch(int valFalse) : mValFalse(valFalse) {}
  GPUd() int get() const { return mValFalse; }

 private:
  int mValFalse;
};

Now getNdim() return this Switch: 
 
 template <int NdimT>
  GPUd() static Switch<(NdimT > 0), NdimT> getNdim(int Ndim)
  {
    return Switch<(NdimT > 0), NdimT>(Ndim);
  }

and Switch::get() returns either constepr NdimT or int Ndim, depending on condition (NdimT > 0)


The funny thing is, that this doesn't work:

int A[SplineUtil::getNdim<5>(Ndim).get()];

But this works:

const auto tmp = SplineUtil::getNdim<5>(Ndim);
int A[tmp.get()];

2020-10-29 21:16 UTC, davidrohr commented
> But this works:
> 
> const auto tmp = SplineUtil::getNdim<5>(Ndim);
> int A[tmp.get()];

Interesting. But that is actually what I meant. To be precise you could use
```
constexpr auto tmp = ...
int A[tmp.get()]
```
or
```
constexpr int n = SplineUtil::getNdim<5>(Ndim).get();
int A[n]
```

In that case, you should already get a compiler error even on the host when the expression is not clearly deducible as constexpr.
Or do I miss something?

2020-10-29 21:17 UTC, davidrohr commented
Do I have to recreate the transformation maps, or can I still use the old ones?

2020-10-29 21:24 UTC, sgorbuno commented
@davidrohr, I'm afraid you need to create new maps - I changed class names and the order of the members in the class

2020-10-30 10:46 UTC, davidrohr commented
@sgorbuno : With this PR, I get a segfault on the GPU during the track fit. If you want to debug, use my o2-pbpb-100 event on asustest04. You need to update the tpctransform.dump with the one for the updated transformation. You can run
```
o2-tpc-reco-workflow --infile tpcdigits.root --configKeyValues "GPU_global.dump=1" --output-type clusters,tracks
```
on some random up-to-date O2 simulation, and use the tpctransform.dump which is dumped there

2020-10-30 12:38 UTC, sgorbuno commented
@davidrohr 
> With this PR, I get a segfault on the GPU during the track fit. 

Oh dear, now this.. I just wanted to improve the interface.:)

2020-10-30 12:39 UTC, davidrohr commented
sorry, but don't shoot the messenger! :)

> @davidrohr
> 
> > With this PR, I get a segfault on the GPU during the track fit.
> 
> Oh dear, now this.. I just wanted to improve the interface.:)

2020-10-30 12:49 UTC, davidrohr commented
@sgorbuno : Ah wait, you changed the interface to the splines in general?
I think it fails in the dEdx splines. So I have to recreate them as well I guess.

2020-10-30 13:04 UTC, davidrohr commented
@sgorbuno : I have recreated the dEdx splines with the new version, and that fixes the segfault. So your code seems correct.
However, I see a 0.6% performance degradation in the overall track fit. Not that much, but also not insignificant, given that this is only the interface of the cluster transformation. (Measured on NVIDIA, currently I cannot compile for AMD).
Any idea what we could do? I am not saying we cannot merge it like this, but we are fighting hard to get the tpc processing fast, so I would merge PRs with negative performance impact only if there is a strong reason.

2020-10-30 16:38 UTC, sgorbuno commented
@davidrohr, I need to figure out what causes the difference. I only changed interfaces + I switched to double precision in SplineHelper which  creates splines.  

What do you mean by performance degradation?  The speed?

2020-10-30 16:40 UTC, davidrohr commented
Yes

2020-10-30 16:46 UTC, sgorbuno commented
ok, let me try to fix it

2020-11-02 21:05 UTC, sgorbuno commented
@davidrohr, 

Could you please have a look?  I can compile the GPU reconstruction on asustest04 using your container, but I can not run it.
The executable is looking for libcuda.so.1 which doesn't exist anywhere. 

This is a complete list of what I do on the asustest04 at FIAS:


docker pull davidrohr/slc8-gpu-builder

alias drun='docker run -it --network=host --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --privileged --security-opt seccomp=unconfined -v /home/sgorbunov/aliceGPU:/root/aliceGPU'

drun --name GPU davidrohr/slc8-gpu-builder bash

docker start -i GPU

cd ~/aliceGPU/
git clone https://github.com/sgorbuno/AliceO2 O2
cd O2

git remote add upstream https://github.com/AliceO2Group/AliceO2

git fetch --all
git merge upstream/dev 
cd ..

pip3 install alibuild

aliBuild init --defaults o2 O2

aliBuild build --defaults o2 O2

alienv enter O2/latest CMake/latest fmt/latest
export fmt_DIR=/root/aliceGPU/sw/slc8_x86-64/fmt/latest


mkdir standalone
cd standalone
mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=../. ../../O2/GPU/GPUTracking/Standalone

vim config.cmake :
/*
# This is the configuration file for the standalone build
# Its options do not affect the O2 build !!!!

set(ENABLE_CUDA ON)
set(ENABLE_HIP OFF)
set(ENABLE_OPENCL1 OFF)
set(ENABLE_OPENCL2 OFF)
set(CONFIG_OPENMP 1)
set(CONFIG_VC 1)
set(CONFIG_FMT 1)
set(CONFIG_ROOT 1)
set(CONFIG_O2_EXTENSIONS 1)
set(CONFIG_O2_ITS_TRAITS 1)
set(BUILD_EVENT_DISPLAY 0)
set(CONFIG_GL3W 0)
set(CONFIG_O2 1)
set(BUILD_DEBUG 0)
#set(CUDA_GCCBIN c++-8.3.0)
#set(OCL2_GPUTARGET gfx906)
#set(HIP_AMDGPUTARGET gfx906)
#set(CUDA_COMPUTETARGET 61)
#set(FORCE_OPENCL2_ALL ON)
*/

cmake -DCMAKE_INSTALL_PREFIX=../. ../../O2/GPU/GPUTracking/Standalone

/* this is the output:
-- Detected Compiler: GCC 8
-- Detected CPU: skylake-avx512
-- CUDA found (Version 11.0.194)
-- Building GPU QA
-- GPU: Using OpenMP: 201511
-- Building GPUTracking with CUDA support
-- Configuring done
-- Generating done
-- Build files have been written to: /root/aliceGPU/standalone/build
*/

make -j install

cd ..

./ca

/* This is the error output

The following error occured during dlopen: libcuda.so.1: cannot open shared object file: No such file or directory
Error Opening cagpu library for GPU Tracker (libGPUTrackingCUDA.so)
Error: Could not load GPUReconstruction for specified device: CUDA (2)
Error initializing GPUReconstruction

*/

2020-11-03 07:53 UTC, davidrohr commented
@sgorbuno : You cannot run the tracking from within the gpu builder container. In order to access the GPU and use it, you need a container with the nvidia container runtime or such. Then, the runtime will make the host nvidia libs available in the container automatically.
The gpu builder is only for compilation unfortunately. (Well, it would work if you install the exact same software versions on the server and in the container and then pipe in the /dev/nv... devices into the container I guess.

2020-11-03 07:54 UTC, davidrohr commented
I was using `nvcr.io/nvidia/cuda:10.2-devel" before, I guess there is also a cuda11 version by now. You need the docker option `--runtime nvidia` and the nvidia container runtime packages installed on the server. Unfortunately this is kind of a mess and more complicated than using AMD GPUs in docker.

2020-11-05 13:01 UTC, sgorbuno commented
@davidrohr,  
I didn't manage to run the code on CUDA, but there is good news - I think I see the same 0.6% degradation on a CPU. 
I'll try to identify the problem with the CPU.

2020-11-11 11:34 UTC, sgorbuno commented
Hi @david,
I think my observation was wrong. I reran both versions on asustest02 and asustest04 a few tens of times. 
I would say, there is no difference within the measurement accuracy:

Could you please run it many times on GPU, may be this 0.6% is just a fluctuation?

I don't see how I can debug it without GPU, and there is no difference in the interpolation code. 
The only little difference is at the place where the number of dimensions is provided, but this is calculated in compile-time.

==== Spline2DSpec.h:
 const auto nYdimTmp = SplineUtil::getNdim<YdimT>(inpYdim);
 const int nYdim = nYdimTmp.get();
 const auto maxYdim = SplineUtil::getMaxNdim<YdimT>(inpYdim);
 const int maxYdim4 = 4 * maxYdim.get();

==== Before it was in Spline2D.h:
#if defined(GPUCA_GPUCODE) // constexpr array size for the GPU compiler
  const int nFdim = nFdimT;
#else
  const int nFdim = getFdimensions();
#endif
==================

What I can do - I can put back the GPU ifdef, but it will suppress a possibility to have a variable number of dimensions on GPU and I don't see how it may help. The maxYdim4 is already treated as a constexpr, otherwise, the GPU code won't compile.

Here are my tests: 

asustest02:
old:
TPC Track Merging and Fit Time:  4,722,073 us ( Total Time :      4,824,131 us)
TPC Track Merging and Fit Time:  4,456,977 us ( Total Time :      4,577,562 us)
TPC Track Merging and Fit Time:  4,335,145 us ( Total Time :      4,433,915 us)
TPC Track Merging and Fit Time:  4,862,531 us ( Total Time :      4,961,176 us)
TPC Track Merging and Fit Time:  4,528,494 us ( Total Time :      4,631,862 us)

new:
TPC Track Merging and Fit Time:  4,791,909 us ( Total Time :      4,897,757 us)
TPC Track Merging and Fit Time:  4,281,796 us ( Total Time :      4,382,276 us)
TPC Track Merging and Fit Time:  4,427,586 us ( Total Time :      4,527,873 us)
TPC Track Merging and Fit Time:  5,398,584 us ( Total Time :      5,501,555 us)
TPC Track Merging and Fit Time:  5,109,146 us ( Total Time :      5,245,309 us)
TPC Track Merging and Fit Time:  4,417,075 us ( Total Time :      4,519,468 us)
TPC Track Merging and Fit Time:  4,556,619 us ( Total Time :      4,661,766 us)
TPC Track Merging and Fit Time:  4,432,433 us ( Total Time :      4,533,615 us)

asustest04:
old:
TPC Track Merging and Fit Time:  3,345,601 us ( Total Time :      3,619,063 us)
TPC Track Merging and Fit Time:  3,562,211 us ( Total Time :      3,796,739 us)
TPC Track Merging and Fit Time:  3,295,464 us ( Total Time :      3,536,542 us)
TPC Track Merging and Fit Time:  3,295,672 us ( Total Time :      3,579,062 us)
TPC Track Merging and Fit Time:  3,325,803 us ( Total Time :      3,568,294 us)
TPC Track Merging and Fit Time:  3,281,842 us ( Total Time :      3,530,025 us)

new:
TPC Track Merging and Fit Time:  3,689,700 us ( Total Time :      3,935,502 us)
TPC Track Merging and Fit Time:  3,563,824 us ( Total Time :      3,804,061 us)
TPC Track Merging and Fit Time:  3,289,289 us ( Total Time :      3,532,237 us)
TPC Track Merging and Fit Time:  3,319,146 us ( Total Time :      3,594,432 us)
TPC Track Merging and Fit Time:  3,382,031 us ( Total Time :      3,655,514 us)
TPC Track Merging and Fit Time:  3,345,285 us ( Total Time :      3,610,573 us)
TPC Track Merging and Fit Time:  3,284,763 us ( Total Time :      3,567,346 us)
TPC Track Merging and Fit Time:  3,311,274 us ( Total Time :      3,569,427 us)

TPC Track Merging and Fit Time:  3,372,250 us ( Total Time :      3,628,417 us)
TPC Track Merging and Fit Time:  3,478,895 us ( Total Time :      3,761,587 us)
TPC Track Merging and Fit Time:  3,349,548 us ( Total Time :      3,619,820 us)
TPC Track Merging and Fit Time:  3,360,653 us ( Total Time :      3,628,502 us)
TPC Track Merging and Fit Time:  3,310,419 us ( Total Time :      3,577,973 us)
TPC Track Merging and Fit Time:  3,323,974 us ( Total Time :      3,593,507 us)

2020-11-11 11:58 UTC, davidrohr commented
@sgorbuno : I was running it repeatedly and the performance decrease was reproducible.

You can actually test on asustest04 bare metal, you just need an up-to-date CUDA installation in your home folder (which is quite annoying, but required until the system is updated). You can basically use mine if you want, just put /home/drohr/cuda/bin in the path, and remove whatever you have from /usr/local/cuda*

Your CPU results are fluctuating a lot. Perhaps this is due to multithreading. For checking the performance effect, perhaps it would make sense to run with --debug 1 --omp 1 and then check only the time of the merger track fit.

I tried to have a look, but this PR changes many files. It was not immediately clear to me what affects the actual interpolation code and what changes are only for creating the maps.
I am quite busy this week, but if needed I can have a closer look next week and try to find out where the performance difference comes from.

2020-11-11 15:53 UTC, davidrohr commented
@sgorbuno : The change with the braces after if clauses etc. was merged, could you rebase?

2020-11-11 21:46 UTC, sgorbuno commented
> @sgorbuno : The change with the braces after if clauses etc. was merged, could you rebase?

ok, did it!

2020-11-12 19:27 UTC, davidrohr commented
@sgorbuno : I tried again with this commit and dev and now the GPU performance before and after is 100% identical.
No idea what changed. Anyhow, this can be merged now.

@matthias-kleiner : This changes the interface for the dEdx splines, you'll have to regenerate the spline object files.
For my tests, I am now using the default object generated when no file with splines is provided.
Could you generate a new reasonable splines file and sent it to me, just so I can test with the full reasonable setup?

2020-11-12 19:28 UTC, davidrohr approved these changes

2020-11-12 19:56 UTC, sgorbuno commented
@davidrohr 
> I tried again with this commit and dev and now the GPU performance before and after is 100% identical.

Great!

2020-11-12 22:30 UTC, davidrohr commented
@TimoWilken : It seems the build/O2/o2 failed again here, probably for the same reason?

2020-11-12 22:41 UTC, TimoWilken commented
@davidrohr it's getting weird:
```
ERROR: Error on 'git ls-remote --heads https://github.com/google/re2': fatal: unable to access 'https://github.com/google/re2/': transfer closed with outstanding read data remaining
```
I'll let it try again; I'm hoping it'll have built properly by tomorrow.

2020-11-13 08:05 UTC, merged