Only consider Bz in propagator if specific flag is set
AliceO2Group/AliceO2 pull request #4615
Opened 2020-10-16 11:41 UTC by martenole

@davidrohr With this change the computation time for `GPUTPCCompressionKernels_step0attached` decreases about 20% while the entropy increases by 1.4% (both averaged over a few tries). Not sure if this should be merged.

2020-10-16 12:03 UTC, davidrohr commented
OK, weird, I'll check this. Wouldn't have expected so much of an effect, but I would not merge it when the entropy increases by 1.5%

2020-10-26 17:39 UTC, davidrohr requested changes

2020-10-26 17:39 UTC, davidrohr commented on GPU/GPUTracking/Merger/GPUTPCGMPropagator.cxx
> +    if (!t0.PropagateToXBzLight(trackX, Bz, dLp)) {
@martenole : Here is a typo, the check should not re inverted. Can you please remove the `!` and retry. I did a quick check here and then it looks OK.

2020-10-27 08:18 UTC, martenole commented
@davidrohr Thank you for spotting this! With the fix the difference is is pretty much negligible. Both entropy and computing speed stay basically constant.

2020-10-27 08:20 UTC, davidrohr commented
Okay, it became faster before because the tracks were just abandoned. Then more clusters were compressed as differences instead of track model, thus the entropy increased. But now, with the fix, it should be at least somewhat faster, isn't it?

2020-10-27 08:33 UTC, martenole commented
Actually, I checked again with `--PROCompKernels 1` and the run time is 392,854 us without this commit and 398,592 us with it. So it becomes even slightly slower. Maybe because of the additional conditional clause?
The propagation of the physical track model seems to be very fast in any case.

2020-10-27 15:04 UTC, davidrohr commented
Yes, it shouldn't make much difference, but the additional if must not make it slower.
Did you try multiple times? With the ompKernels there is anyway quite some variation in the time.
Could you retry with --omp 1 (this will set the number of threads to 1, basically disabling all openmp)

2020-10-27 16:55 UTC, martenole commented
I found another typo :/ Since the physical track parameter `t0` is already rotated, the magnetic field at the new alpha needs to be queried and not at the old alpha. But this should only have an impact on the entropy, not the compute time.

The other thing is when I use the `GetBzBase` method directly instead of `GetBz` I get a very tiny speed improvement with the `PropagateToXBzLight` method in comparison with the `GetBxByBz` and `PropagateToXBxByBz` method. But with --omp 1 the difference is of the same order as the dispersion of the time when I retry the calculation multiple times. So the compute times agree within their uncertainty

2020-10-28 16:04 UTC, davidrohr commented
For reference, I have compared the tracking QA before and after this PR and the output is basically identical.
However, doing some timing measurements, it seems to me that actually it becomes slower with this PR, but I cannot understand why. WIll have to check in more detail. I cannot understand how it can possibly get slower. It should be faster or perhaps equally fast if this operation takes close to zero time.

2020-10-29 12:29 UTC, davidrohr commented
ok, so the inconclusive results I had yesterday were due to bogus CPU frequency scaling. I retested today, and don't see any significant difference on the CPU, but if at all, it i minimally faster. On the GPU, I see a 1.5% performance increase during the track fit. Resolution does change, and logically this fix is correct. So let's get it merged.

2020-10-29 12:29 UTC, davidrohr approved these changes
should be squashed at merging

2020-10-29 12:54 UTC, martenole commented
Ok. Should I squash it or is this done automatically?

2020-10-29 12:55 UTC, davidrohr commented
I'll do it when merging, you don't have to do anything, just waiting for the CI.

2020-10-29 13:00 UTC, martenole commented
Thanks! So all I learned now is that `GPUTPCGMPhysicalTrackModel::PropagateToXBzLightNoUpdate` is extremely fast, because when the 3D magnetic field is taken into account this function is called twice instead of only once which is the case if only Bz is considered and for that we see this very tiny speedup only..

2020-10-29 16:42 UTC, davidrohr commented
@TimoWilken : the fullCI build failed with
```
c++: fatal error: Killed signal terminated program cc1plus
```
Can it be that it still runs out of memory?
Could you perhaps also catch these type of errors and write something in the html log, people will usually not understand what happened otherwise.

2020-10-29 17:32 UTC, davidrohr commented
@TimoWilken : The html log shows the 
```
o2checkcode results
sw/BUILD/O2-latest/log
```
even when no o2checkcode was running. Perhaps ideally in such cases I would just leave out the o2checkcode?

2020-10-29 17:34 UTC, davidrohr commented
error unrelated, merging.

2020-10-29 17:34 UTC, merged