Raw data and CTF for FDD
AliceO2Group/AliceO2 pull request #4659
Opened 2020-10-22 11:18 UTC by mbroz84

Raw data format, raw reader and Raw2Digits for FDD togehter with CTF classes. All based on current FV0 implementation.

2020-10-23 14:11 UTC, shahor02 requested changes
Hi @mbroz84 

Thanks! Looks fine, please see a few minor comments below. Could you please amend this PR by
1) a unit test for CTF encoding/decoding, you can mostly borrow the code from e.g. https://github.com/AliceO2Group/AliceO2/blob/dev/Detectors/CTF/test/test_ctf_io_fv0.cxx
and make sure that the original and decoding digits are the same.
2) add FT0 to https://github.com/AliceO2Group/AliceO2/blob/dev/Detectors/CTF/workflow/src/CTFReaderSpec.cxx, https://github.com/AliceO2Group/AliceO2/blob/dev/Detectors/CTF/workflow/src/CTFWriterSpec.cxx and https://github.com/AliceO2Group/AliceO2/blob/dev/Detectors/CTF/workflow/src/ctf-reader-workflow.cxx
Again, you need just to copy/paste the entries of e.g. FV0

2020-10-23 14:11 UTC, shahor02 commented on DataFormats/Detectors/FIT/FDD/include/DataFormatsFDD/LookUpTable.h
> +  static constexpr int mLinkTCM = Nmodules;
constants should be capitalized.

2020-10-23 14:11 UTC, shahor02 commented on Detectors/FIT/FDD/simulation/src/Digits2Raw.cxx
> +    uint32_t linkId = uint32_t(iPmLink);
feeId is actually ``uint16_t`` and the linkId is ``uint8_t``, see 
``RawFileWriter::registerLink(uint16_t fee, uint16_t cru, uint8_t link, uint8_t endpoint, std::string_view outFileNameV)``

2020-10-23 14:11 UTC, shahor02 commented on Detectors/FIT/FDD/simulation/src/Digits2Raw.cxx
> +  mWriter.registerLink(uint64_t(sTcmLink), sCruId, sTcmLink, sEndPointId, outFileLink);
idem

2020-11-03 16:47 UTC, shahor02 commented
@mbroz84 just to ping that there your response is pending on this PR

2020-11-03 19:10 UTC, AllaMaevskaya submitted a review, later dismissed

2020-11-04 09:43 UTC, mbroz84 commented
Sorry for delay, requested changes should be in the last commit.

2020-11-04 21:51 UTC, shahor02 commented
@mbroz84 Thanks! everything looks fine but the test_ctf_io_fdd you added fails on the macos, see the output in https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/4659/8eb75ba486c75be50e0f0f3b0dfa7f46fc89f522/build_AliceO2_O2_o2_macOS/fullLog.txt

Note that you can run the test yourself by going to build dir. and running like
````
shahoian@alicers02:~/alice/sw/BUILD/O2-latest/O2$ ./stage/tests/o2-test-ctf-fdd
````

2020-11-10 08:55 UTC, shahor02 approved these changes

2020-11-10 08:56 UTC, merged