PWGHF: Adressing comments to the pull request #4727
AliceO2Group/AliceO2 pull request #4734
Opened 2020-10-30 22:07 UTC by DelloStritto

2020-10-31 17:31 UTC, vkucera requested changes
I don't see the change from `hf_cand_prong3::InvMassLc()` to `hf_cand_prong3::InvMassLcToPKPi()` and `hf_cand_prong3::InvMassLcToPiKP()`.

2020-11-01 11:30 UTC, DelloStritto commented
Hi @vkucera. I'm working to add the LcpiKp but this will change a lot of files. So, if you agree, i would merge this pull request with minor fixes and then I would open a dedicated one to add the LcpiKp

2020-11-01 12:38 UTC, vkucera commented
@DelloStritto OK, then.

2020-11-02 07:49 UTC, jgrosseo approved these changes

2020-11-02 07:49 UTC, merged