TableMaker task updated to use configurables for system type, event and track selections
AliceO2Group/AliceO2 pull request #5206
Opened 2021-01-17 16:23 UTC by iarsene

TableMaker:
1) Event and track selections can be specified via configurables selecting predefined cuts in the CutsLibrary.
2) A special configurable for the minimum pt of the lepton is added to allow switching between the quarkonia and lmee analyses.
3) The task can now be run on either pp or PbPb by specifying the isPbPb parameter. In the case of pp, the centrality task has to be taken out from the pipe.
4) Histogram definition is now using the predefined histogram groups from the HistogramLibrary. Configurables should be added in the future to control the level of histogramming detail.

2021-01-18 07:36 UTC, jgrosseo commented
Could the list of runs come from a CCDB object? Everything should be ready to do that already. You can check out the "globalEfficiency" tutorial.

2021-01-18 13:03 UTC, iarsene commented
In principle yes, if these run lists exist already then one can save having all the lists added manually in the utility function. I think this would be nice to interface with what the DPG will provide at some point.

2021-01-18 14:52 UTC, jgrosseo requested changes
As just discussed on mattermost, the hard coded run lists should be moved to CCDB. A better solution needs further discussion...

2021-01-19 07:54 UTC, jgrosseo approved these changes

2021-01-19 08:55 UTC, merged