Changed log message from WARNING to DEBUG.
AliceO2Group/AliceO2 pull request #5414
Opened 2021-02-09 08:07 UTC by pbuehler

It happens that messages with empty payload arrive at the aod-writer. These messages are skipped. However, so far a WARNING log was created which seems to have caused some confusion for users. The log message is hence changed from WARNING to DEBUG.
The fact that messages with empty payload are passed to the writer might however need further investigation.

2021-02-09 14:43 UTC, jgrosseo approved these changes

2021-02-10 06:40 UTC, ktf requested changes
Rather than demoting it, can we please print only the first one?

2021-02-10 06:41 UTC, ktf commented
Or only the message 1, 10, 100, 1000... etc?

2021-02-10 08:08 UTC, jgrosseo commented
I think it is completely normal behavior to have an empty table in a filtering. Or is this message covering a different case?

2021-02-10 09:31 UTC, ktf commented
Empty table, yes, empty payload, I am not sure. I missed this is just in the writer though. So I guess it's fine.

2021-02-10 09:31 UTC, merged