PWGHF: rapidity cut apply in Jpsi task
AliceO2Group/AliceO2 pull request #5473
Opened 2021-02-15 08:15 UTC by zhangbiao-phy

Change eta cut with rapidity cut for Jpsi task

2021-02-18 16:27 UTC, vkucera requested changes
Hi @zhangbiao-phy , some minor fixes. Otherwise looks ready to me.

2021-02-18 16:27 UTC, vkucera commented on Analysis/Tasks/PWGHF/taskJpsi.cxx
> +     {"hPtGenSig", "2-prong candidates (matched);#it{p}_{T}^{gen.} (GeV/#it{c});entries", {HistType::kTH1F, {{100, 0., 10.}}}},
`(matched)` -> `(rec. matched)`

2021-02-18 16:27 UTC, vkucera commented on Analysis/Tasks/PWGHF/taskJpsi.cxx
> +        auto indexMother = RecoDecay::getMother(particlesMC, candidate.index0_as<aod::BigTracksMC>().label_as<soa::Join<aod::McParticles, aod::HfCandProng2MCGen>>(), 443, true);
Add documentation comment:
`// Get the corresponding MC particle.`

2021-02-18 16:27 UTC, vkucera commented on Analysis/Tasks/PWGHF/taskJpsi.cxx
> +          //Printf("MC Gen.: Y rejection: %g", RecoDecay::Y(array{particle.px(), particle.      py(), particle.pz()}, RecoDecay::getMassPDG(particle.pdgCode())));
`particle.      py()` -> `particle.py()`

2021-02-18 16:31 UTC, zhangbiao-phy commented
> Hi @zhangbiao-phy , some minor fixes. Otherwise looks ready to me.

Hi @vkucera, Thanks a lot! I will fix it now.

2021-02-18 16:50 UTC, vkucera approved these changes
Thanks a lot, for the lightning-fast fix.
@ginnocen This looks ready to me.

2021-02-19 11:13 UTC, ginnocen approved these changes

2021-02-20 10:48 UTC, merged