PWGHF: Add prompt and feeddown histos to the Lc->pKpi task
AliceO2Group/AliceO2 pull request #5889
Opened 2021-04-08 16:15 UTC by DelloStritto

2021-05-04 23:32 UTC, vkucera commented
There are some conflicts.

2021-05-11 20:48 UTC, ginnocen commented
Hi Luigi, is this still up to date?

2021-05-12 07:38 UTC, DelloStritto commented
> Hi Luigi, is this still up to date?

Hi GianMichele, there are some conflicts. I will resolve them.

2021-05-18 18:27 UTC, vkucera commented
@DelloStritto Any updates?

2021-05-18 21:57 UTC, DelloStritto commented
> @DelloStritto Any updates?

Hi @vkucera . Sorry for the delay. I fixed the conflicts. Now everything should be fine.

2021-05-25 19:31 UTC, vkucera requested changes

2021-05-25 19:31 UTC, vkucera commented on Analysis/Tasks/PWGHF/taskLc.cxx
>       {"hCPARecBg", "3-prong candidates (rec. unmatched);cosine of pointing angle;entries", {HistType::kTH1F, {{110, -1.1, 1.1}}}},
Can you please adjust the histogram titles? (See `taskD0.cxx`)

2021-05-25 19:31 UTC, vkucera commented on Analysis/Tasks/PWGHF/taskLc.cxx
> +        if (candidate.originMCRec() == Prompt) {
Please use explicit namespace qualifier: `OriginType::Prompt` instead of `Prompt`.

2021-05-26 08:23 UTC, DelloStritto commented on Analysis/Tasks/PWGHF/taskLc.cxx
>       {"hCPARecBg", "3-prong candidates (rec. unmatched);cosine of pointing angle;entries", {HistType::kTH1F, {{110, -1.1, 1.1}}}},
Done!

2021-05-26 10:56 UTC, vkucera approved these changes, later dismissed
Thanks

2021-06-02 08:01 UTC, vkucera approved these changes

2021-06-02 08:02 UTC, vkucera commented
@ginnocen Ready. Can you approve, please?

2021-06-02 08:03 UTC, ginnocen approved these changes

2021-06-02 08:06 UTC, vkucera commented
@jgrosseo @iarsene All green and approved. Can you please merge?

2021-06-02 08:57 UTC, jgrosseo approved these changes

2021-06-02 09:01 UTC, merged