[WIP][EMCAL-518,EMCAL-694] Split digitizer into SDigitizer and FEEDigitizer
AliceO2Group/AliceO2 pull request #5896
Opened 2021-04-09 12:29 UTC by hahassan7

The Sdigitisation in EMCAL now have the following workflow:
-     Sum up energy from all hits in the same tower belonging to the same collision
-     Sample time response and distribute energy to up to 15 time samples
-     Fill ring buffer with the energy of the time samples
-     Get last 15 time samples when readout window is closed

Also the old digitizer has been split into FEEDigitizer and SDigitizer.

2021-04-12 13:02 UTC, mfasDa requested changes
Hi Hadi, it goes in the right direction but there seems to be still some confusion: The SDigitizer works on single event level, therefore it does not need time handling (except the average SDigit time  obtained from the hit times). As such it takes a vector of hits and input and creates a vector of SDigits as output (where SDigits are of Digits type). The whole time hanlding (open/close readout, set busy) can be kept in the digitizer task and the SDigitizer does not need any knowledge of it.

2021-04-12 13:02 UTC, mfasDa commented on Detectors/EMCAL/simulation/src/SDigitizer.cxx
> +      o2::emcal::Hit SHit = std::accumulate(std::next(Hits.begin()), Hits.end(), Hits.front());
Last argument must be the initial value for the sum, which should be a null-entry. It could be a simple digit created with a default constructor, where the energy is 0.

2021-04-12 13:02 UTC, mfasDa commented on Detectors/EMCAL/simulation/src/SDigitizer.cxx
> +      auto digit = hitToDigit(hit);
Not sure a function is really needed here it was needed once we did the time sampling here but the code of htiToDigit can be put here directly

2021-04-12 13:02 UTC, mfasDa commented on Detectors/EMCAL/simulation/src/SDigitizer.cxx
> +  Double_t energy = hit.GetEnergyLoss() / constants::EMCAL_ADCENERGY;
I think at SDigit level we might want to stay with the energy directly and go to amplitudes during the digitization

2021-04-12 13:02 UTC, mfasDa commented on Detectors/EMCAL/simulation/src/SDigitizer.cxx
> +      mRingBuffer.addDigit(id, d, mEventTime);
Not sure we need the ring buffer in the SDigitizer, it is something we need in the FEEDigitizer. SDigit level is much simpler as it just accumulates the energy which is later digitized.

2021-04-12 13:02 UTC, mfasDa commented on Detectors/EMCAL/simulation/include/EMCALSimulation/SDigitizer.h
> +  o2::emcal::DigitsWriteoutBuffer mRingBuffer = o2::emcal::DigitsWriteoutBuffer(); // Ring buffer for writing digits and labels per tower
I don't think we need this here. It is something needed in the FEEDigitizer

2021-04-12 13:02 UTC, mfasDa commented on Detectors/EMCAL/simulation/include/EMCALSimulation/SDigitizer.h
> +  bool isLive() const { return (mEventTime < mLiveTime); }
This is all not needed here, it can be handled purely in the DigitizerTask

2021-04-12 13:02 UTC, mfasDa commented on Detectors/EMCAL/simulation/include/EMCALSimulation/SDigitizer.h
> +  void fillOutputContainer(std::vector<Digit>& digits, o2::dataformats::MCTruthContainer<o2::emcal::MCLabel>& labels);
Can be absorbed in the process function

2021-04-12 13:02 UTC, mfasDa commented on Detectors/EMCAL/simulation/src/SDigitizer.cxx
> +}
The whole function can be significantly simplified: The SDigitizer operates on single event level, there is no time ordering needed. That is part of the FEE digitizer. As output container a simple std::vector is sufficient, where of course the position in the std::vector and the LabelContainer must match. I would propose to sort according to the tower ID,.

2021-05-02 21:35 UTC, hahassan7 commented on Detectors/EMCAL/simulation/src/SDigitizer.cxx
> +}
Done

2021-05-02 21:35 UTC, hahassan7 commented on Detectors/EMCAL/simulation/include/EMCALSimulation/SDigitizer.h
> +  void fillOutputContainer(std::vector<Digit>& digits, o2::dataformats::MCTruthContainer<o2::emcal::MCLabel>& labels);
Done

2021-05-02 21:35 UTC, hahassan7 commented on Detectors/EMCAL/simulation/include/EMCALSimulation/SDigitizer.h
> +  bool isLive() const { return (mEventTime < mLiveTime); }
Done

2021-05-02 21:37 UTC, hahassan7 commented on Detectors/EMCAL/simulation/include/EMCALSimulation/SDigitizer.h
> +  o2::emcal::DigitsWriteoutBuffer mRingBuffer = o2::emcal::DigitsWriteoutBuffer(); // Ring buffer for writing digits and labels per tower
The ring buffer class was crashing when filling, so we decided to use normal vector instead. We will take care of this class later when working of the pileup simulation.

2021-05-02 21:37 UTC, hahassan7 commented on Detectors/EMCAL/simulation/src/SDigitizer.cxx
> +      mRingBuffer.addDigit(id, d, mEventTime);
Done

2021-05-02 21:38 UTC, hahassan7 commented on Detectors/EMCAL/simulation/src/SDigitizer.cxx
> +  Double_t energy = hit.GetEnergyLoss() / constants::EMCAL_ADCENERGY;
The conversion was moved to the (FEE)Digitizer, mainly when sampling the digits the energy will be converted to ADC.

2021-05-02 21:38 UTC, hahassan7 commented on Detectors/EMCAL/simulation/src/SDigitizer.cxx
> +      auto digit = hitToDigit(hit);
Done

2021-05-02 21:46 UTC, hahassan7 commented on Detectors/EMCAL/simulation/src/SDigitizer.cxx
> +      o2::emcal::Hit SHit = std::accumulate(std::next(Hits.begin()), Hits.end(), Hits.front());
The problem in operator+ of the Hit class it sums only the energy and copy all the other parameters from the first Hit object in the sum. So if the first object is zero, then in the summed Hit all the parameters will be zero except the energy. So the first element in the sum is the first object in the vector.

2021-05-07 12:40 UTC, mfasDa approved these changes, later dismissed
Looks basically OK to me. I think we can go ahead with the merging process.

2021-05-07 18:24 UTC, ktf commented
```
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/SOURCES/O2/5896/0/Detectors/EMCAL/simulation/src/Digitizer.cxx: In member function 'void o2::emcal::Digitizer::sampleSDigit(const o2::emcal::Digit&)':
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/SOURCES/O2/5896/0/Detectors/EMCAL/simulation/src/Digitizer.cxx:142:12: error: 'hit' was not declared in this scope
  142 |   energy = hit.GetEnergyLoss() / constants::EMCAL_ADCENERGY;
```

genuine error, please fix it.

2021-05-26 11:13 UTC, hahassan7 commented
Failed tests are not due to this commit. So I think it can be merged now.

2021-05-26 13:02 UTC, shahor02 commented
@hahassan7 the fullCI breaks for other reason, could you run it locally to make sure the new digitizers are ok?
Just run in some tmp directory
````
alienv load O2/latest AEGIS/latest
ulimit -n 3000
$O2_ROOT/prodtests/full_system_test.sh
````
and make sure it ends w/o error messages.

2021-05-26 15:47 UTC, hahassan7 commented
Hi @shahor02, the above test failed at FT0:
command o2-ft0-digi2raw --file-per-link -o raw/FT0 had nonzero exit code 134
`Running: TIME="#walltime %e"  ./ft0raw.log_tmp.sh
[FATAL] could not create output directory raw/FT0/
For later analysis we write a core dump to core_dump_19593
[/Users/hadi/alice/sw/osx_x86-64/FairLogger/v1.9.1-local1/lib/libFairLogger.1.9.1.dylib] fair::Logger::~Logger() (no debug info)
[/Users/hadi/alice/sw/osx_x86-64/O2/EMCAL-694-local1/bin/o2-ft0-digi2raw] digi2raw(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, unsigned int, bool, int) /Users/hadi/alice/sw/SOURCES/O2/EMCAL-694/0/Detectors/FIT/FT0/simulation/src/digi2raw.cxx:0
[/Users/hadi/alice/sw/osx_x86-64/O2/EMCAL-694-local1/bin/o2-ft0-digi2raw] main /Users/hadi/alice/sw/SOURCES/O2/EMCAL-694/0/Detectors/FIT/FT0/simulation/src/digi2raw.cxx:82
[/usr/lib/system/libdyld.dylib] start (no debug info)
./ft0raw.log_tmp.sh: line 1: 19593 Abort trap: 6           o2-ft0-digi2raw --file-per-link -o raw/FT0
TASK-EXIT-CODE: 134
`

2021-05-26 16:08 UTC, shahor02 commented
Hm, very strange, this part has never failed before. Are you sure your disk is not full? Can you try to execute manually 
````
o2-ft0-digi2raw --file-per-link -o raw/FT0
````
from this directory?

2021-05-26 16:11 UTC, hahassan7 commented
It works when executed manually. I will try to rerun the whole test again.

2021-05-26 16:16 UTC, shahor02 commented
Thanks, if you rerun in the same dir. it will continue from the point it has failed before

2021-05-26 17:26 UTC, hahassan7 commented
Hi @shahor02, now failed in another test:
command /Users/hadi/alice/sw/osx_x86-64/O2/EMCAL-694-local1/prodtests/full-system-test/dpl-workflow.sh had nonzero exit code 1
I attached the log file here.
[reco_NOGPU.log](https://github.com/AliceO2Group/AliceO2/files/6548605/reco_NOGPU.log)

2021-05-26 17:31 UTC, shahor02 commented
strange, let me test your brunch myself...

2021-05-26 18:17 UTC, shahor02 commented
@hahassan7 for me it worked w/o problems, merging.

2021-05-26 18:18 UTC, merged