KrBoxClusterFinder: New Param Class and a few small Updates
AliceO2Group/AliceO2 pull request #5919
Opened 2021-04-13 07:28 UTC by HauenderPhilip

2021-04-13 13:44 UTC, wiechula submitted a review, later dismissed

2021-04-16 07:23 UTC, HauenderPhilip commented
Hey,
the copyright notice still seems to cause some troubles. But after checking everything again twice, I can not find any mistakes. Any idea what's wrong?

2021-04-30 17:30 UTC, wiechula submitted a review, later dismissed
@davidrohr , @shahor02 , from my side this can be merged.

2021-04-30 17:41 UTC, shahor02 requested changes
Hi @HauenderPhilip 

Could you add to https://github.com/HauenderPhilip/AliceO2/blob/dev/Detectors/TPC/reconstruction/src/TPCReconstructionLinkDef.h the same lines as https://github.com/HauenderPhilip/AliceO2/blob/90733bc7a90e1a245763ac3e5a575ee7e60bee76/Detectors/TPC/reconstruction/src/TPCReconstructionLinkDef.h#L37-L38 but for KrBoxClusterFinderParam ?

2021-05-03 17:13 UTC, shahor02 approved these changes

2021-05-03 17:13 UTC, merged