channel offsets in reconstruction
AliceO2Group/AliceO2 pull request #6115
Opened 2021-05-09 12:00 UTC by AllaMaevskaya

2021-05-10 00:23 UTC, shahor02 requested changes

2021-05-10 00:23 UTC, shahor02 commented on Detectors/FIT/FT0/reconstruction/include/FT0Reconstruction/CollisionTimeRecoTask.h
> +    auto caliboffsets = mgr.get<o2::ft0::FT0ChannelTimeCalibrationObject>("FT0/Calibration/ChannelTimeOffset");
One should not set-up and query the CCDB for every bc! Do this once per TF in your device run(). Soon the CCDB objects you need will be provided by the DPL processing context.

2021-05-11 15:12 UTC, AllaMaevskaya commented
Is it correct now?

2021-05-11 15:47 UTC, shahor02 commented on Detectors/FIT/FT0/reconstruction/src/CollisionTimeRecoTask.cxx
> +    int offsetChannel = mCalibOffset->mTimeOffsets.at(inChData[ich].ChId);
`mTimeOffsets.at()` access is slower than `mTimeOffsets[]`, since the channel ID is well defined, use `[]`.

2021-05-11 15:47 UTC, shahor02 commented on Detectors/FIT/FT0/workflow/src/ReconstructionSpec.cxx
> +  LOG(INFO) << " set-up CCDB";
yes, this should be ok, though will change once the support of the CCDB by the DPL will be in place

2021-05-14 07:26 UTC, AllaMaevskaya commented
error is not related to my code

2021-05-14 12:03 UTC, shahor02 approved these changes

2021-05-14 12:04 UTC, merged