[MFT] Add a geometry misaligner
AliceO2Group/AliceO2 pull request #6251
Opened 2021-05-26 20:16 UTC by robincaron13

This PR contains the geometry misaligner class, which is able to misalign the existing MFT geometry. Basic shifts and rotations are allowed on: half-cone, disk, ladder, sensor. 
These functions have been tested through simple simulations (o2-sim-serial -m MFT -e TGeant3 -n 1). The resulting misaligned geometry can be available as a simple output root file (just after closing the geometry with 'gGeoManager->RefreshPhysicalNodes()' after applying misalignments).

2021-05-28 07:58 UTC, shahor02 commented
@robincaron13 the errors reported by FullCI are real:
````
========== List of errors found ==========
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/SOURCES/O2/6251/0/Detectors/ITSMFT/MFT/simulation/src/GeometryMisAligner.cxx:174:21: error: use '= default' to define a trivial destructor [modernize-use-equals-default]
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/SOURCES/O2/6251/0/Detectors/ITSMFT/MFT/simulation/src/GeometryMisAligner.cxx:190:9: error: statement should be inside braces [readability-braces-around-statements]
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/SOURCES/O2/6251/0/Detectors/ITSMFT/MFT/simulation/src/GeometryMisAligner.cxx:202:9: error: statement should be inside braces [readability-braces-around-statements]
````

2021-06-02 09:58 UTC, rpezzi requested changes
@robincaron13 , thanks for your contribution with detailed comments. 
Some things have to be clarified:
1. configurable options to enable the misaligner and  its configuration. 
2. the need of another geometry file.

2021-06-02 09:58 UTC, rpezzi commented on Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
> +  MisalignGeometry();
Hi @robincaron13 , notice that any simulation is calling MisalignGeometry() and saving `o2sim_geometry_misaligned.root`. This method should be called only in special circumstances, thus a configurable parameter is desirable.

2021-06-02 09:58 UTC, rpezzi commented on Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
> +  aGMA.SetSensorAngMisAlig(0., 0., 0., 0., 0., 0.);  // Sensors rotated on Z, X, Y axis
These parameters should be configurable, otherwise one needs to recompile O2 to produce any misalignment.

2021-06-02 09:58 UTC, rpezzi commented on Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
> +  gGeoManager->Export("o2sim_geometry_misaligned.root");
if this file is relevant only for the MFT, its filename should refer to it. Also, this file may not contain the final geometry, since other detectors may not be ready at this point. The usual `o2sim_geometry.root` won't contain the complete detector including misalignment?

2021-06-02 10:01 UTC, shahor02 commented on Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
> +  MisalignGeometry();
The geometry misalignment will be handled centrally, I will open a PR today or tomorrow. The Detector should always produce an ideal geometry.

2021-06-02 14:40 UTC, rpezzi commented on Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
> +  MisalignGeometry();
Hi @shahor02 , 
So we drop calling `MisalignGeometry()` here, but keep its implementation on `Detector.cxx`?

2021-06-02 15:08 UTC, shahor02 commented on Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
> +  MisalignGeometry();
The geometry should be not misaligned on the construction level. Instead, the "misaligner" should provide a vector of AlignParam objects, which are fed to `o2::base::GeometryManager::applyAlignment` method, which modifies ideal geometry. 
Note that I've updated many classes, so the interface changed, should push it after some more work: the PR https://github.com/AliceO2Group/AliceO2/pull/6287 will be amended by https://github.com/shahor02/AliceO2/commits/pr_algpar1.

2021-06-03 16:14 UTC, shahor02 commented
please see https://github.com/AliceO2Group/AliceO2/pull/6287 , particularly the https://github.com/AliceO2Group/AliceO2/blob/b778332365c064825e78a6bc7ad0cecdfcbb0ee7/Detectors/Base/README.md
Essentially, the misaligner shall generate a `vector<AlignParam>`, with the output similar to that of https://github.com/AliceO2Group/AliceO2/blob/b778332365c064825e78a6bc7ad0cecdfcbb0ee7/Detectors/ITSMFT/ITS/macros/test/ITSMisaligner.C

2021-06-07 14:09 UTC, shahor02 commented
Hi @robincaron13 
What is the context of this PR? I see you pushed changes after my https://github.com/AliceO2Group/AliceO2/pull/6287 and loaded some objects on the test ccdb, but your Detector still contains the Misalign method and the Misaligner seem to apply the alignment to the geom instead of just producing a vector of params.

2021-06-08 22:16 UTC, robincaron13 commented on Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
> +  MisalignGeometry();
Thanks for your messages and the updated classes. Now this line has been droped.

2021-06-08 22:19 UTC, robincaron13 commented on Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
> +  aGMA.SetSensorAngMisAlig(0., 0., 0., 0., 0., 0.);  // Sensors rotated on Z, X, Y axis
Thanks, sorry for the late reply, now I added the associated configurable parameters (using the MFTBaseParam.h).

2021-06-08 22:22 UTC, robincaron13 commented on Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
> +  gGeoManager->Export("o2sim_geometry_misaligned.root");
I droped this line, since the misaligner should only produce an output file containing `vector<AlignParam>`.

2021-06-09 14:10 UTC, javierecc commented
Hi @shahor02, All,
I agree that the MisAligner should only produce a CCDB entry to be used later. Some changes are still needed in my opinion, we will come back.
I have however one remark about the Misaligner applying the alignments. This is indeed not the code to be used to apply the produced misalignments during a simulation, but we need to apply "temporarily" the misalignments to the geometry to produce reasonable misalignments. The reason is:
- AlignParam store parameters in global coordinates
- Generating misalignments in global coordinates is not practical because the same value will not have the same effect depending on the position of the element
- Thus, I would prefer to generate misalignments in local coordinates 
- AlignParam need the geometry when setting its parameters in local coordinates
- For hierarchical geometries as the MFT we need to first misalign the mother volume and propagate it to the geometry before misaligning the daughter volume so that the calculated global misalignment of the daughter volume makes sense

Does that make sense?
Cheers,
Javier

2021-06-09 14:26 UTC, shahor02 commented
Hi @javierecc 

> This is indeed not the code to be used to apply the produced misalignments during a simulation, but we need to apply "temporarily" the misalignments to the geometry to produce reasonable misalignments. The reason is:

Sorry, I did not understand the point about the temporary misalignment, could you elaborate?

>     * AlignParam store parameters in global coordinates
> 
Yes, as it was done in the Aliroot, the meaning of parameters should be the same.

>     * Generating misalignments in global coordinates is not practical because the same value will not have the same effect depending on the position of the element
> 
>     * Thus, I would prefer to generate misalignments in local coordinates

You can extract them in local frame, the AlignParam constructor will take care of moving them to the global one.

>     * AlignParam need the geometry when setting its parameters in local coordinates

Does this pose a problem?
> 
>     * For hierarchical geometries as the MFT we need to first misalign the mother volume and propagate it to the geometry before misaligning the daughter volume so that the calculated global misalignment of the daughter volume makes sense
> 

This is taken care by the way the alignment is applied: AlignParam::applyToGeometry: the GeometryManager::applyAlignment
sorts the params in the level decreasing order and calls the `AlignParam::applyToGeometry` in this order.
In short, this is supposed to be an exact copy of what we had in the AliRoot. Is there a reason to change this?

2021-06-09 14:29 UTC, shahor02 commented
PS: there is a format problem

2021-06-09 15:32 UTC, javierecc commented
Hi @shahor02
On 9 Jun 2021 at 16:27 +0200, Ruben Shahoyan ***@***.***>, wrote:
	Hi @javierecc
	This is indeed not the code to be used to apply the produced misalignments during a simulation, but we need to apply "temporarily" the misalignments to the geometry to produce reasonable misalignments. The reason is:
Sorry, I did not understand the point about the temporary misalignment, could you elaborate?
Delta^g = G Delta^l G^-1, with G = M L, where M is the transformation of the mother volume and L the transformation of the daughter volume inside the mother volume.

So if the transformation G is not the same when you produce Delta^g than when you apply it to your geometry you won’t get the intended result. And that is what would happen if you produce the Delta^g from Delta^l using and ideal geometry but apply it to a geometry that you are misaligning hierarchically as we are doing.
Note that I agree, AlignParam is correctly implemented (and it was already like that in AliRoot) and that the application of the misalignment parameters is correct also. I’m just saying that we should pay attention to it when generating misalignments from Delta_l. We need to first apply the misalignment to the mother volume before getting Delta^g from Delta^l for a daughter volume. But this should be done in the misalignment generation code.
		* AlignParam store parameters in global coordinates
Yes, as it was done in the Aliroot, the meaning of parameters should be the same.
Agree.
		* Generating misalignments in global coordinates is not practical because the same value will not have the same effect depending on the position of the element

* Thus, I would prefer to generate misalignments in local coordinates
You can extract them in local frame, the AlignParam constructor will take care of moving them to the global one.
Agree, but you need to have the right geometry for that
		* AlignParam need the geometry when setting its parameters in local coordinates
Does this pose a problem?
No, indeed.
		* For hierarchical geometries as the MFT we need to first misalign the mother volume and propagate it to the geometry before misaligning the daughter volume so that the calculated global misalignment of the daughter volume makes sense
This is taken care by the way the alignment is applied: AlignParam::applyToGeometry: the GeometryManager::applyAlignment
sorts the params in the level decreasing order and calls the AlignParam::applyToGeometry in this order.
Right, but for that the misalignment parameters need to have been produced properly following the same sorting and with the same misaligned transformations for the mother volumes.
	 In short, this is supposed to be an exact copy of what we had in the AliRoot. Is there a reason to change this?
Also agree. There is no reason to change. We were already doing what I describe in the misaligner code for muon.

In short, AlignParam has no problem. Our misalignment generation code needs to take care of generating the misalignments of the mother volumes and apply them before generating the misalignment of the daughter volumes. I said “temporarily", because once all misalignment parameters are generated and stored in the CCDB we forget about it and just let the framework take the CCDB and handle the misalignments.

Hope it is clearer and makes sense.
Cheers,
Javier
	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-09 16:01 UTC, shahor02 commented
Hi @javierecc 

I know what is the difference between the global and local deltas, I was confused with your "temporary alignment". 
We always were doing the new alignment incrementally to existing one (as far as I understand, this is what you call "temporary") and extracted corrections were added on top of this initial alignment (obviously, this is not a simple addition).
The AlignParams created by any (mis)alignment code should be applicable to ideal geometry (which can be always loaded by setting the `Aligner.mDetectors` to "none").

So, all what you say is correct, but I don't understand your comment `this is indeed not the code to be used to apply the produced misalignments during a simulation`, does not it create full misalignment?

2021-06-09 19:57 UTC, javierecc commented
Hi @shahor02,

Good then we all agree and there was just some misunderstanding. 
The comment "this is indeed not the code to be used to apply the produced misalignments during a simulation" was related to the initial version in which, as a workaround, we were generating misalignments and applying them on the flight during creation of the geometry. That was a workaround because the reading of misalignments from CCDB was not yet in place. Now it is and thus this misaligner code should just be used to produce a CCDB entry.  
Robin made must of the needed changes, but some fixes are still needed. We will come back to this.

Cheers,
Javier

2021-06-09 20:18 UTC, shahor02 commented
Hi @javierecc 
ok, now understood :)
Cheers,
 Ruben

2021-06-17 07:12 UTC, rpezzi approved these changes, later dismissed

2021-07-12 08:04 UTC, rpezzi approved these changes

2021-07-12 08:04 UTC, rpezzi commented
Hello, this PR should be good to go. CI failures are not related. Please merge.

2021-07-14 14:41 UTC, merged