Fix in stored vectors size, resize them and pad with 0s
AliceO2Group/AliceO2 pull request #6476
Opened 2021-06-20 21:56 UTC by shahor02

2021-06-23 16:08 UTC, MichaelLettrich commented
@shahor02 Can you have a look at #6509 ? I think this should fix the memory sanitizer issues and improve the readability of the encoder code a bit.

2021-06-23 16:17 UTC, MichaelLettrich requested changes
See comment.

2021-06-23 16:17 UTC, MichaelLettrich commented on DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/EncodedBlocks.h
> +    std::copy(srcBegin, srcEnd, std::back_inserter(vtmp));
`std::back_inserter()` creates a `std::back_insertion_iterator` which will append at the end of the vector. If I read this correctly, you resize to size + padding in  line 866, which means you're ending up with a vector whith size + padding zeroes and the original payload n `vtmp`, so `storeData` will always store zeros.

2021-06-29 10:29 UTC, shahor02 commented
superseded by https://github.com/AliceO2Group/AliceO2/pull/6509, closing

2021-06-29 10:29 UTC, closed without merging