Adding Preshower detector (PSR) for ALICE3 simulation
AliceO2Group/AliceO2 pull request #6519
Opened 2021-06-24 20:11 UTC by an15ms157

This PR creates a simple 8 layered preshower detector named PSR. This is a cylindrical detector of length 100 cm whose shower layers are made up of Pb (0.5 cm) and the detector layers are made up of Si (45 microns). PSR is based on the ITSMFT classes and the code is structurally similar to that of FT3. Each layer is made of a monolithic silicon disk with a thin sensitive layer for hit generation. Silicon chip thickness is tuned to match the layer x/X0 to allow a minimal evaluation of material budget effects.

One should get a file o2sim_HitsPSR.root by running
$ o2-sim -m PSR -e TGeant3 -g boxgen -n 10

2021-07-09 09:21 UTC, mconcas commented
ok, now that codechecker is fine the next step is to reabase your branch on  the AliceO2/dev one. Since the `pragma cheker` is something that has been added in relatively recent times wrt your PR opening.

2021-07-09 09:42 UTC, an15ms157 commented
I have made the changes.

2021-07-09 10:04 UTC, mconcas requested changes
To me looks pretty good, some inline comments

2021-07-09 10:04 UTC, mconcas commented on Detectors/Base/src/MaterialManager.cxx
> +  LOG(INFO) << "Changes for build";
Perhaps a DEBUG print you forgot?

2021-07-09 10:04 UTC, mconcas commented on Detectors/Upgrades/ALICE3/FT3/simulation/src/Detector.cxx
> -  for (Int_t direction : {0, 1}) {
This is not really clear to me, why these changes in FT3 whould affact the PSR? @rpezzi is it fine to you?

2021-07-09 10:04 UTC, mconcas commented on Detectors/Upgrades/ALICE3/PSR/README.md
> +# PostLS4EndCaps
This is minor, but I think should be changed to desccribe PSR

2021-07-09 10:05 UTC, an15ms157 commented on Detectors/Base/src/MaterialManager.cxx
> +  LOG(INFO) << "Changes for build";
Ah!! yes

2021-07-14 09:51 UTC, mconcas commented
@an15ms157 : do you have any update on this? Could you also rebase on `dev` branch? So that the git history is linear? Thanks

2021-07-22 14:48 UTC, mconcas commented
Hi @an15ms157, you should rebase the modifications you want to merge on the dev branch. The history must be linear, e.g. no merging commits and branching. Could you please do that?

2021-07-23 08:16 UTC, an15ms157 commented
Hello @mconcas 
I am not sure that I have as of yet managed to make the required changes. So, I have tried to make a new local branch, clump all the content to a single commit and push it to my fork. Here is it: https://github.com/an15ms157/AliceO2/tree/mydev
Is it possible that I run another PR with this different branch? In case if such is possible and it is sucessful, I will keep that one and remove this PR.

2021-07-23 08:47 UTC, mconcas commented
> Hello @mconcas
> I am not sure that I have as of yet managed to make the required changes. So, I have tried to make a new local branch, clump all the content to a single commit and push it to my fork. Here is it: https://github.com/an15ms157/AliceO2/tree/mydev
> Is it possible that I run another PR with this different branch? In case if such is possible and it is sucessful, I will keep that one and remove this PR.

Hi @an15ms157: I had a look to your new branch and it seems to be ok, please proceed with a new PR. Thanks.

2021-07-23 09:51 UTC, an15ms157 commented
> > Hello @mconcas
> > I am not sure that I have as of yet managed to make the required changes. So, I have tried to make a new local branch, clump all the content to a single commit and push it to my fork. Here is it: https://github.com/an15ms157/AliceO2/tree/mydev
> > Is it possible that I run another PR with this different branch? In case if such is possible and it is sucessful, I will keep that one and remove this PR.
> 
> Hi @an15ms157: I had a look to your new branch and it seems to be ok, please proceed with a new PR. Thanks.
Here is a link to my new PR: https://github.com/AliceO2Group/AliceO2/pull/6727

2021-07-23 09:52 UTC, closed without merging