A simple github action to check pragma once rule
AliceO2Group/AliceO2 pull request #6592
Opened 2021-07-06 08:25 UTC by sawenzel

We disallow `#pragma once` and check it with this github action.

2021-07-06 08:26 UTC, sawenzel commented
@TimoWilken : Could you please take a look if this looks reasonable? Eventually, we might make a combined action, encapsulating multiple of these simple checks.

2021-07-06 08:36 UTC, TimoWilken requested changes
Looks good, but I think you can remove a bunch of stuff to make this faster.

2021-07-06 08:36 UTC, TimoWilken commented on .github/workflows/pragmaonce.yml
> +        git grep "#pragma once" | grep "\.h"; if [ $? -eq "0" ]; then exit 1; fi; exit 0
I think this line could just be
```bash
git grep -l '#pragma once' -- '*.h' && exit 1
```

2021-07-06 08:36 UTC, TimoWilken commented on .github/workflows/pragmaonce.yml
> +        sudo apt install -y git
According to [the docs](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#tools), git is already installed in the container, so we don't need this step at all -- removing it should speed up the check.

2021-07-06 08:36 UTC, TimoWilken commented on .github/workflows/pragmaonce.yml
> +        fetch-depth: 0
We're only checking the latest commit, so we don't need to fetch everything. You should be able to remove the `fetch-depth` option for a speedup.

2021-07-06 08:36 UTC, TimoWilken commented on .github/workflows/pragmaonce.yml
> +        ALIBUILD_GITHUB_TOKEN: ${{secrets.ALIBUILD_GITHUB_TOKEN}}
Unneeded, right?

2021-07-06 08:41 UTC, TimoWilken approved these changes

2021-07-06 08:42 UTC, merged

2021-07-06 08:42 UTC, TimoWilken commented
Thanks, merged.

2021-07-09 11:39 UTC, vkucera commented
@sawenzel @TimoWilken It seem that this action is reporting unrelated files.
See:
* https://github.com/AliceO2Group/AliceO2/pull/6615/checks?check_run_id=3024121465
* https://github.com/AliceO2Group/AliceO2/pull/6619/checks?check_run_id=3028476422

Also, there is no information in the log about what to do to fix the errors.

2021-07-09 11:53 UTC, sawenzel commented
@vkucera : This happens when the PR is not rebased on dev (the developer has an old state). Feel free to improve the action.