Add dynamic columns for daughter prongs
AliceO2Group/AliceO2 pull request #6690
Opened 2021-07-20 12:21 UTC by ddobrigk

2021-07-20 12:33 UTC, ddobrigk commented
@a-mathis @jgrosseo here are the dynamic columns for the prong information. Please check for any obvious typos :-D Thanks!

2021-07-22 08:42 UTC, jgrosseo commented
It does not seem to compile in the fullCI...

2021-07-22 08:42 UTC, jgrosseo commented on Analysis/DataModel/include/AnalysisDataModel/StrangenessTables.h
> +DECLARE_SOA_DYNAMIC_COLUMN(NegativePt, negativept, //!
Please add a documenting line after //! (everywhere actually ;-))

2021-07-26 08:52 UTC, jgrosseo requested changes
See inline comments

2021-07-26 14:18 UTC, sartozza commented
@ddobrigk @jgrosseo may I ask you the status on this PR?
Just to know in case I need to update the V0 selection task.
Thanks!

2021-07-27 07:23 UTC, ddobrigk commented
@sartozza @jgrosseo documentation added, please check if more is needed! 
...ah wait: my documentation fails clang-format... sigh. One moment.

2021-07-27 08:02 UTC, ddobrigk commented
Now fixed! Please let me know if further action is required :-D

2021-07-27 13:56 UTC, jgrosseo commented
I fear yet...
mac is not happy
`/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6690/0/Analysis/DataModel/include/AnalysisDataModel/StrangenessTables.h:158:52: error: no member named 'NegPx' in namespace 'o2::aod::v0data'
                       v0data::NegativeEta<v0data::NegPx, v0data::NegPy, v0data::NegPz>,
                                           ~~~~~~~~^
`

2021-07-27 15:18 UTC, ddobrigk commented
@jgrosseo, we'll get there :-D Now my mac, at least, is happy! 

Sorry for missing this mishap (I guess doing code in a beach city is by definition more error-prone, so I should probably avoid it :-D)

2021-07-28 06:57 UTC, ddobrigk commented
@jgrosseo the new error seems to be something I am innocent of... Can you please take a look? Thanks!

2021-07-28 11:55 UTC, jgrosseo approved these changes

2021-07-28 11:55 UTC, merged