PWGLF: Add task for ID RAA
AliceO2Group/AliceO2 pull request #6704
Opened 2021-07-21 13:16 UTC by lewis206

Task for the identified RAA measurement for the Summer Student Project.

2021-07-22 08:29 UTC, jgrosseo commented on Analysis/Tasks/PWGLF/CMakeLists.txt
> +o2_add_dpl_workflow(raameasurement
Let's not have measurement in the name. If this is identified RAA, maybe call it identified-raa

2021-07-22 08:31 UTC, jgrosseo approved these changes

2021-07-22 08:31 UTC, jgrosseo requested changes
Just change the file name

2021-07-22 11:03 UTC, lewis206 commented
Yes, you're right. I changed it. Thanks a lot for the spotting of that.

2021-07-23 12:22 UTC, jgrosseo commented
Unfortunately, the copyright notice seems to be the old one (it was changed recently):
`/sw/SOURCES/O2/6704-slc8_x86-64/0//Analysis/Tasks/PWGLF/identifiedraa.cxx:1:1: error: missing or malformed copyright notice`
Please update from any file currently in the repository.

2021-07-30 14:16 UTC, jgrosseo approved these changes, later dismissed

2021-08-03 14:24 UTC, lewis206 commented
Hi, I finally fixed everything. Would be nice if you could give the okay now. Thanks!

2021-08-03 14:27 UTC, jgrosseo approved these changes
Very good!

2021-08-03 14:27 UTC, merged