TPC dEdx calibration values for each GEM stack
AliceO2Group/AliceO2 pull request #6736
Opened 2021-07-23 21:42 UTC by badarots

In this pull request, I extended the TPC dE/dx calibration code to compute values for each GEM stack.
I also renamed some classes, again, sorry, to keep the namings more consistent. Now we have the following:

- `CalibdEdxHistos` is now the class the holds the dE/dx histograms. One for each GEM stack.
- `CalibdEdx` is the class the holds the calibration values extracted from the histograms.
- `CalibdEdxBase` is a templated base class that groups the common functionalities of the two above.
- `CalibratordEdx` is the time slot calibrator.

@wiechula let me know if you agree with my changes.

In `CalibdEdxBase` derived classes we have two arrays storing the Tot and Max dE/dx values for each GEM stack, 144 entries per array. The stack data are layout in the following way:

```
|         A Side          |         C Side           |
 IROC, OROC1, OROC2, OROC3, IROC, OROC1, OROC2, OROC3
```

And, for example, we can access the Tot data of the IROC 12 stack of A side with this call:
    
    CalibdEdxBase::getTotEntry(12, ReadoutType::IROC, TPCSide::A)

`CalibdEdxHistos` is reponsible to find out the GEM stacks crossed by a track. It do so finding the angle phi of the track using the following call in a "TrackTPC" object:

    TrackTPC::getOuterParam().getXYZGloAt(stack_center, 0.5, ok).Phi()

To get the calibration value from the histograms we construct a `CalibdEdx` object using as input a `CalibdEdxHistos`

    CalibdEdx calibOutput(CalibdEdxHistos)
    
During construction, the center of mass of every histogram is computed and stored in the same layout mentioned earlier.

This is a plot with if dEdx histograms and computed MIP position of every GEM stack (600 pp events).

![dedx](https://user-images.githubusercontent.com/39627366/126844236-c22a4727-e7fa-4038-b948-87a1ba3a52db.png)

2021-07-26 13:51 UTC, wiechula requested changes
Some minor comments and a more conceptual one.
As layout I would propose somethink like
* CalibdEdxDataContainer -> Data storage for either histograms or floats per stack (now CalibdEdxBase)
* CaliddEdx -> standalone calibration class, something like
```c++
class CalibdEdx {

void fill();
void finalize(); 
...


private:
  CalibdEdxDataContainer<FastHisto<float>> mHistos;
  CalibdEdxDataContainer<float> mCalibrationData;
}

```
* CalibratordEdx -> Using CalibdEdx as calibration class
* As processors I would propose to implement two
  - one standalone CalibdEdxSpec
  - one time frame processor CalibratordEdxSpec

Please also have a look at https://github.com/AliceO2Group/AliceO2/pull/6693

2021-07-26 13:51 UTC, wiechula commented on Detectors/TPC/calibration/include/TPCCalibration/CalibdEdxBase.h
> +  };
This is duplication of information already available here
https://github.com/AliceO2Group/AliceO2/blob/dev/DataFormats/Detectors/TPC/include/DataFormatsTPC/Defs.h

2021-07-26 13:51 UTC, wiechula commented on Detectors/TPC/calibration/include/TPCCalibration/CalibdEdxBase.h
> +  static const size_t totalStacks = 18 * 8;
Please check information in 
https://github.com/AliceO2Group/AliceO2/blob/dev/DataFormats/Detectors/TPC/include/DataFormatsTPC/Defs.h
```suggestion
static const size_t totalStacks = SECTORSPERSIDE * SIDES * GEMSTACKSPERSECTOR;```
```
your `stacksPerTurn` is `SECTORSPERSIDE`

2021-07-26 13:51 UTC, wiechula commented on Detectors/TPC/calibration/include/TPCCalibration/CalibdEdxBase.h
> + protected:
```suggestion
 private:
```

2021-07-26 13:51 UTC, wiechula commented on Detectors/TPC/calibration/src/CalibratordEdx.cxx
> +  LOG(INFO) << "Finalizing slot " << slot.getTFStart() << " <= TF <= " << slot.getTFEnd();
Please change all logging message to `fmt::format` style using `LOGP(info|error|warning, "", ...)`
```suggestion
  LOGP(info, "Finalizing slot {} <= TF <= {}" , slot.getTFStart(), slot.getTFEnd());
```

2021-08-02 03:22 UTC, badarots commented
@wiechula I modified the class layout and changed the log type. The two CalibdEdxSpec and CalibratordEdxSpec are still missing but I will create them shortly.

We talked about adding a fill histogram function in the DataContainer class. I tried some ideas and didn't like the result.

One reason I didn't add the fill function is that I thought about start using a multidimensional histogram to keeping track of the GEM stacks, instead of keeping an array of 1D histograms. I can define a hist. with the following dimensions:

dEdx data (~100 bins)
Sectors (18 bins)
Type (4 bins)
Side (2 bins)
Charge type: Tot and Max (2 bins) -> maybe split into 2 histograms?

The nice thing about using the dimensions to separate the gem stacks data is that it is trivial to get rid/merge any of those dimensions using the project method of a THn or boost histogram. And it will be very easy to add more.

What do you think about this? Should I swap the array of FastHistos for a dense multidim. histogram?

2021-08-12 15:19 UTC, wiechula requested changes
@badarots , very nice! A few comments to be considered.

2021-08-12 15:19 UTC, wiechula commented on Detectors/TPC/calibration/src/CalibdEdx.cxx
> +    switch (stack) {
You could consider getting rid of the switch by adding before the `for` loop:
```
std::vector<float> dEdxTot{dEdx.dEdxTotIROC, dEdx.dEdxTotOROC1, dEdx.dEdxTotOROC2, dEdx.dEdxTotOROC3};
// same for Max
```
And here simply do
```
mTotHist(dEdxTot[stack], sector, side, stack);
// same for Max
```

2021-08-12 15:19 UTC, wiechula commented on Detectors/TPC/calibration/src/TPCCalibrationLinkDef.h
> +#pragma link C++ class o2::tpc::CalibdEdxDataContainer<o2::tpc::FastHisto<float>> + ;
Is the FastHisto option still used?

2021-08-12 15:19 UTC, wiechula commented on Detectors/TPC/workflow/src/CalibdEdxSpec.cxx
>  #include "Framework/Task.h"
I think this file should be called `CalibratordEdxSpec.cxx`, since it runs the `Calibrator`. We should have a separate workflow to directly run the `Calib` called `CalibdEdxSpec.cxx`

2021-09-17 00:47 UTC, closed without merging