TPC QC: Update of the Tracks task
AliceO2Group/AliceO2 pull request #6824
Opened 2021-08-09 12:05 UTC by stheckel

o Changing p_T plots to logPtBinning
o Adding plots for neg. and pos. tracks, separately
o Adding ratios neg./pos. tracks, created at endOfCycle

2021-08-12 07:10 UTC, wiechula requested changes
@stheckel , thanks for the update! I would remove the commented hists, they are not needed. Please run clang-format afterwards.

2021-08-12 07:10 UTC, wiechula commented on Detectors/TPC/qc/src/Tracks.cxx
> +  //mHist1D.emplace_back("hPt", "Transverse momentum;p_T", 200, 0., 10.);                                               //| mHist1D[5]
```suggestion
```

2021-08-12 07:10 UTC, wiechula commented on Detectors/TPC/qc/src/Tracks.cxx
> +  //mHist2D.emplace_back("h2DNClustersPt", "Number of clusters vs. p_T;p_T;# TPC clusters", 200, 0., 10., 160, -0.5, 159.5);                     //| mHist2D[3]
```suggestion
```

2021-08-13 09:51 UTC, stheckel commented on Detectors/TPC/qc/src/Tracks.cxx
> +  //mHist1D.emplace_back("hPt", "Transverse momentum;p_T", 200, 0., 10.);                                               //| mHist1D[5]
Yes, agreed.

2021-08-13 09:52 UTC, stheckel commented on Detectors/TPC/qc/src/Tracks.cxx
> +  //mHist2D.emplace_back("h2DNClustersPt", "Number of clusters vs. p_T;p_T;# TPC clusters", 200, 0., 10., 160, -0.5, 159.5);                     //| mHist2D[3]
Yes.

2021-08-14 12:53 UTC, wiechula approved these changes

2021-08-14 14:00 UTC, wiechula commented
@shahor02 , looks like the failing test in macos is unrelated. From my side this can be merged.

2021-08-14 21:37 UTC, merged