EMCAL DCS DP processing
AliceO2Group/AliceO2 pull request #6979
Opened 2021-09-06 17:32 UTC by mpoghos

2021-09-06 18:01 UTC, shahor02 approved these changes, later dismissed
conditionally approving to trigger CI

2021-09-07 08:14 UTC, mfasDa requested changes
Several files are not properly formatted - please run `clang-format -i ...` on the file. Also please change the commit message header to 

```
[EMCAL-556] EMCAL DCA DP processing
```

and specify in the message body which datapoints are implemented - I want to see the commit message in this format before approval.

The code has no documentation, even very few comments, which is not helpful but for the moment not a blocker from approval.

Otherwise the code looks good I would say.

2021-09-07 08:14 UTC, mfasDa commented on Detectors/EMCAL/calib/src/EMCDCSProcessor.cxx
> +	}
Misformated. Also lines below. Please run clang-format -I on that file.

2021-09-08 20:19 UTC, mfasDa approved these changes, later dismissed
Looks good now!

2021-09-09 08:45 UTC, mfasDa submitted a review, later dismissed

2021-09-10 17:33 UTC, shahor02 approved these changes
conditionally approving to restart CI

2021-09-11 11:10 UTC, mfasDa commented
@shahor02 Is the approval mandatory to start the CI? In this case, is the approval from me as codeowner sufficient?

2021-09-11 11:15 UTC, shahor02 commented
Hi @mfasDa 
Approval is needed for the 1st 1st-timer commit. I guess the codeowner approval should work, you can try if you find another 1st-timer

2021-09-11 11:28 UTC, mpoghos commented
Hi @shahor02 and @mfasDa 
Do you understand why the build/AliceO2/O2/o2/macOS test filed? I think nothing related to my commit. is this a blocker for merging?

2021-09-11 12:10 UTC, shahor02 commented
yes, it is unrelated

2021-09-11 12:11 UTC, merged

2021-09-13 08:10 UTC, mfasDa commented
@shahor02 Thanks for the reply! I already did the approval at the very first stage so it seems the code owner approval is not sufficient.