CCDB path as argument to reconstruction
AliceO2Group/AliceO2 pull request #7106
Opened 2021-09-23 17:19 UTC by AllaMaevskaya

2021-09-25 15:43 UTC, shahor02 requested changes

2021-09-25 15:43 UTC, shahor02 commented on Detectors/FIT/FT0/workflow/include/FT0Workflow/ReconstructionSpec.h
> +  ReconstructionDPL(bool useMC, std::string ccdbpath) : mUseMC(useMC), mCCDBpath(ccdbpath) {}
could you change all such arguments to `const std::string& ccdbpath`?

2021-09-25 15:43 UTC, shahor02 commented on Detectors/FIT/macros/uploadLookUpTable.C
> -/*
could this code be removed, if obsolete?

2021-09-28 09:09 UTC, AllaMaevskaya commented
I did all what you requested

2021-09-28 09:13 UTC, shahor02 commented
Hi @AllaMaevskaya 

The FullCI fails with error:
````
[16926:ft0-reconstructor]: [ERROR] error parsing options of o2-ft0-reco-workflow: option '--ccdb-path' is ambiguous and matches different versions of '--ccdb-path'
````
Could you rename the option to `--ccdb-path-ft0` ?

2021-09-30 13:17 UTC, AllaMaevskaya commented
build/O2/fullCI error is unrelated

2021-10-02 08:31 UTC, AllaMaevskaya commented
Is it OK now?

2021-10-02 14:27 UTC, shahor02 approved these changes

2021-10-02 14:27 UTC, merged