[EMCAL-548] Using raw fitter to convert digits to cells
AliceO2Group/AliceO2 pull request #7160
Opened 2021-09-29 14:36 UTC by hahassan7

As the digitiser now digitises hits with time information the digits->cell converter must also do the raw fitting in the same way as the raw->cell converter. The steps include:
    Separation of ALTRO bunches and adding the time stamps
    filtering of all labels belonging to digits in the same ALTRO bunch
    Performing the raw fit on the ALTRO bunch in the same way as in data

The Handling of MC labels is not done yet.

2021-10-12 08:58 UTC, mfasDa requested changes
AltroBunch, ChannelDigits, ChannelData and SRUDigitContainer are commonly used in RawWriter and CellConverter, thus they need to be extracted from the two classes in a separate header in order to prevent symbol duplication.

Otherwise fine

2021-10-12 08:58 UTC, mfasDa commented on Detectors/EMCAL/workflow/include/EMCALWorkflow/CellConverterSpec.h
> +};
I think they are already defined somewhere else, probably in the raw writer, therefore we would get a duplication of symbols. I guess it is code duplication so better extract them in a separate file and use them for both.

2021-10-17 07:27 UTC, ktf commented
@pzhristov there seems to still be some issues with LLVM / Clang.

```
/sw/slc8_x86-64/GCC-Toolchain/v10.2.0-alice2-1/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /sw/slc8_x86-64/arrow/v5.0.0-alice2-2/lib/libgandiva.so.500.0.0: undefined reference to `llvm::createNewGVNPass()'
/sw/slc8_x86-64/GCC-Toolchain/v10.2.0-alice2-1/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /sw/slc8_x86-64/arrow/v5.0.0-alice2-2/lib/libgandiva.so.500.0.0: undefined reference to `llvm::Type::getInt128Ty(llvm::LLVMContext&)'
/sw/slc8_x86-64/GCC-Toolchain/v10.2.0-alice2-1/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /sw/slc8_x86-64/arrow/v5.0.0-alice2-2/lib/libgandiva.so.500.0.0: undefined reference to `llvm::createTargetTransformInfoWrapperPass(llvm::TargetIRAnalysis)'
collect2: error: ld returned 1 exit status
[716/3372] Building CXX object Framework/Utils/CMakeFiles/O2test-dplutils-DPLRawPageSequencer.dir/test/test_DPLRawPageSequencer.cxx.o
[717/3372] Building CXX object Framework/Core/CMakeFiles/O2test-framework-TableBuilder.dir/test/test_TableBuilder.cxx.o
```

2021-10-17 07:47 UTC, pzhristov commented
> @pzhristov there seems to still be some issues with LLVM / Clang.
> 
> ```
> /sw/slc8_x86-64/GCC-Toolchain/v10.2.0-alice2-1/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /sw/slc8_x86-64/arrow/v5.0.0-alice2-2/lib/libgandiva.so.500.0.0: undefined reference to `llvm::createNewGVNPass()'
> /sw/slc8_x86-64/GCC-Toolchain/v10.2.0-alice2-1/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /sw/slc8_x86-64/arrow/v5.0.0-alice2-2/lib/libgandiva.so.500.0.0: undefined reference to `llvm::Type::getInt128Ty(llvm::LLVMContext&)'
> /sw/slc8_x86-64/GCC-Toolchain/v10.2.0-alice2-1/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /sw/slc8_x86-64/arrow/v5.0.0-alice2-2/lib/libgandiva.so.500.0.0: undefined reference to `llvm::createTargetTransformInfoWrapperPass(llvm::TargetIRAnalysis)'
> collect2: error: ld returned 1 exit status
> [716/3372] Building CXX object Framework/Utils/CMakeFiles/O2test-dplutils-DPLRawPageSequencer.dir/test/test_DPLRawPageSequencer.cxx.o
> [717/3372] Building CXX object Framework/Core/CMakeFiles/O2test-framework-TableBuilder.dir/test/test_TableBuilder.cxx.o
> ```

Strange, this reappeared suddenly. During the last days we haven't seen it.

2021-10-17 07:54 UTC, pzhristov commented
@ktf Can we check if arrow was compiled with -DLLVM_ROOT=${CLANG_ROOT}?

2021-10-31 12:16 UTC, davidrohr commented
the CI is now green, what is the status of this PR?

2021-11-01 15:10 UTC, hahassan7 commented
This pull request can be merged now.

2021-11-01 15:25 UTC, mfasDa approved these changes
Looks good now, PR can be merged.

2021-11-01 15:26 UTC, mfasDa commented
Would also be in favour of merging ...

2021-11-01 15:30 UTC, shahor02 approved these changes

2021-11-01 15:30 UTC, merged