Match itstpcqc
AliceO2Group/AliceO2 pull request #7228
Opened 2021-10-06 21:58 UTC by chiarazampolli

To run:

`o2-global-track-cluster-reader --track-types "TPC,ITS-TPC" | o2-itstpc-match-qc -b`

For now it does not implement the cyclic saving of histograms that we have in QC. 
To be done: attach a QC task that publishes the output to the QCG.

2021-10-07 13:05 UTC, shahor02 requested changes
There are some genuine errors in the failed CIs

2021-10-07 13:05 UTC, shahor02 commented on Detectors/GlobalTracking/CMakeLists.txt
> +	  src/ITSTPCMatchingQCParams.cxx
formatting again slipped

2021-10-07 13:05 UTC, shahor02 commented on Detectors/GlobalTracking/CMakeLists.txt
> +  include/GlobalTracking/MatchTOF.h include/GlobalTracking/MatchCosmics.h include/GlobalTracking/MatchCosmicsParams.h include/GlobalTracking/MatchITSTPCQC.h include/GlobalTracking/ITSTPCMatchingQCPar
here too

2021-10-07 13:05 UTC, shahor02 commented on Detectors/GlobalTracking/src/MatchITSTPCQC.cxx
> +  mTimeResVsPt = new TH2F("mTimeResVsPt", "Time resolution vs Pt; Pt; time res", 100, 0.f, 20.f, 100, 0.f, 2.f);
Should not histos boundaries be defined by the cuts?

2021-10-07 13:05 UTC, shahor02 commented on Detectors/GlobalTracking/src/MatchITSTPCQC.cxx
> +  o2::base::Propagator::Instance()->getNominalBz();
This will create a problem in real processing, where the geometry and grp files are not in current dir. 
Usually, we set the paths via ConfigurableParam, e.g. 
```
-configKeyValues "NameConf.mDirGRP=/home/epn/odc/files;NameConf.mDirGeom=/home/epn/odc/files;NameConf.mDirCollContext=/home/epn/odc/files;NameConf.mDirMatLUT=/home/epn/odc/files;keyval.input_dir=/home/epn/odc/files;keyval.output_dir=/dev/null;HBFUtils.nHBFPerTF=128"
```
Doing this in QC seems to be impossible. 
BTW, why do you need field and geometry? Eventually, we will do some progatations for DCA checks etc., then it will be needed, but at the moment the seem not to be used.

2021-10-07 17:55 UTC, chiarazampolli commented on Detectors/GlobalTracking/src/MatchITSTPCQC.cxx
> +  o2::base::Propagator::Instance()->getNominalBz();
Hi Ruben, 
Actually it is my bad, I forgot then to initialize the Bz, sorry. But this is why I need it, because Bz is needed in the track selection, for the DCA cut. 
Yes, in fact I wanted to ask you. Shouldn't we read it from the CCDB?

2021-10-07 18:24 UTC, shahor02 commented on Detectors/GlobalTracking/src/MatchITSTPCQC.cxx
> +  o2::base::Propagator::Instance()->getNominalBz();
in general yes, but at the moment we are reading it from files, and I guess for MC we will be doing this (at least non-anchored ones). We should talk to @Barthelemy to allow at least ConfigurableParams in the qc.

2021-10-07 21:29 UTC, chiarazampolli commented on Detectors/GlobalTracking/CMakeLists.txt
> +	  src/ITSTPCMatchingQCParams.cxx
I honestly don't understand what I did wrong, I just used the formatting that was already there. I am anyway trying to improve it, not sure it is the correct way (is there some documentation? an example?)

2021-10-07 21:29 UTC, chiarazampolli commented on Detectors/GlobalTracking/CMakeLists.txt
> +  include/GlobalTracking/MatchTOF.h include/GlobalTracking/MatchCosmics.h include/GlobalTracking/MatchCosmicsParams.h include/GlobalTracking/MatchITSTPCQC.h include/GlobalTracking/ITSTPCMatchingQCPar
Done

2021-10-07 21:39 UTC, shahor02 commented on Detectors/GlobalTracking/CMakeLists.txt
> +	  src/ITSTPCMatchingQCParams.cxx
I suspect your editor uses tabs, which are then substituted by spaces, producing a shift

2021-10-07 21:41 UTC, chiarazampolli commented
The error on o2-dataflow-cs8 seems not related to my PR:
```
The following tests FAILED:
	 32 - multinode_test (Timeout)
Errors while running CTest
## End sw/BUILD/QualityControl-latest/log
```

2021-10-07 22:36 UTC, chiarazampolli commented on Detectors/GlobalTracking/src/MatchITSTPCQC.cxx
> +  o2::base::Propagator::Instance()->getNominalBz();
For now I am using the NameConf for the GRP and geom file names. In QC (see https://github.com/AliceO2Group/QualityControl/pull/878), I will pass them in the json file, as the other parameters.

2021-10-07 22:43 UTC, chiarazampolli commented on Detectors/GlobalTracking/CMakeLists.txt
> +	  src/ITSTPCMatchingQCParams.cxx
You were right, I could not see with emacs. Now it is fixed.

2021-10-11 21:18 UTC, shahor02 approved these changes
failures unrelated, merging

2021-10-11 21:18 UTC, merged