Workflow to write to file the MID digits decoded from raw data
AliceO2Group/AliceO2 pull request #7248
Opened 2021-10-08 13:28 UTC by dstocco

Writing decoded data to file is useful for debugging.

2021-10-09 10:06 UTC, aphecetche approved these changes

2021-10-09 10:08 UTC, aphecetche requested changes

2021-10-09 10:08 UTC, aphecetche commented on Detectors/MUON/MID/Workflow/src/decoded-digits-writer-workflow.cxx
> +// Copyright CERN and copyright holders of ALICE O2. This software is
@dstocco that's the old copyright. must be changed to new one...

2021-10-10 08:30 UTC, dstocco commented
All failures seem unrelated (multinode_test)

2021-10-10 11:09 UTC, merged