add TOF match checker
AliceO2Group/AliceO2 pull request #7289
Opened 2021-10-12 16:09 UTC by noferini

2021-10-12 16:14 UTC, noferini commented
@julekm (@shahor02)
This is a draft PR where I implemented a first prototype of tof matcher checker to show how to retrive TOF matching info.
This can be usefull also for the event display.
It is just a draft because few methods are missing.
In particular for the moment you can work only with ITS-TPC--TOF tracks.
In any case the dpl is general (just few utils for inputs are missing).

2021-10-14 14:58 UTC, noferini commented
Dear all,
I added all the pieces to deal with all possible matches (fix in our reader and RecoContainer).
I needed to change the MC output name to stay within the limits of the length allowed for the name.
MCMATCHTOF_ -> MCMTC_
This may be relevant for @chiarazampolli which is working in matching QC.
The checker currently works on TPC and ITS-TPC tracks.
For TPC-TRD and ITS-TPC-TRD tracks the RecoContainer now provides matching infos but not tracks (it not clear to me why).
I will investigate about this issue

2021-10-15 09:45 UTC, noferini commented
I added all the needed methods.
Now also matching with TPC-TRD and ITS-TPC-TRD can be inspected with the RecoContainer utils.
You can start the review...

2021-10-16 23:34 UTC, shahor02 requested changes
Hi @noferini 
looks nice, just few comments below.

2021-10-16 23:34 UTC, shahor02 commented on DataFormats/Detectors/GlobalTracking/include/DataFormatsGlobalTracking/RecoContainerCreateTracksVariadic.h
> +      // no need to check isUsed: by construction this ITS-TPC was not used elsewhere
this check is indeed not needed, since being the longest tracks, the ITSTPCTRDTOF cannot be used in any other track.
Also, could you please fix the comments: these are not ITS-TPC tracks.

2021-10-16 23:34 UTC, shahor02 commented on DataFormats/Detectors/GlobalTracking/include/DataFormatsGlobalTracking/RecoContainerCreateTracksVariadic.h
> +      // no need to check isUsed: by construction this ITS-TPC was not used elsewhere
here too the wrong comment comes from the copy/paste

2021-10-16 23:34 UTC, shahor02 commented on DataFormats/Detectors/GlobalTracking/src/RecoContainer.cxx
>    }
You updated `requestTOFMatches` takes as its 1st argument the `GTrackID::mask_t` rather than `GTrackID`, I thing you should do:
```
if (src[GTrackID::ITSTPCTRDTOF] || src[GTrackID::ITSTPCTOF] || src[GTrackID::TPCTRDTOF] ) {
  requestTOFMatches(src, useMC); 
  requestTOFClusters(false);
}
```

2021-10-16 23:34 UTC, shahor02 commented on DataFormats/Detectors/GlobalTracking/src/RecoContainer.cxx
>    }
and remove this

2021-10-16 23:34 UTC, shahor02 commented on Detectors/GlobalTrackingWorkflow/src/TOFMatchChecker.cxx
> +  }
why all these checks are needed? Instead, you can check if `gid` contains TOF: 
```
if (!gid.includesDet(DetID::TOF)) {
  return;
}
```

2021-10-16 23:34 UTC, shahor02 commented on Detectors/TOF/workflowIO/src/TOFMatchedReaderSpec.cxx
> +  ddMCMatchTOF[3] = new o2::header::DataDescription{"MCMTC_ITSTPCTRD"};
better avoid global variables and `new`, instead define in the TOFMatchedReader class
```
public:
 static constexpr DDMatchInfo[4] = {"MTC_TPC", "MTC_ITSTPC", "MTC_TPCTRD", "MTC_ITSTPCTRD"};
```
and use them both here and in the `run()`. The same for `ddMCMatchTOF`

2021-10-18 10:14 UTC, noferini commented on DataFormats/Detectors/GlobalTracking/include/DataFormatsGlobalTracking/RecoContainerCreateTracksVariadic.h
> +      // no need to check isUsed: by construction this ITS-TPC was not used elsewhere
done

2021-10-18 10:14 UTC, noferini commented on DataFormats/Detectors/GlobalTracking/src/RecoContainer.cxx
>    }
done

2021-10-18 10:14 UTC, noferini commented on DataFormats/Detectors/GlobalTracking/src/RecoContainer.cxx
>    }
done

2021-10-18 10:14 UTC, noferini commented on Detectors/GlobalTrackingWorkflow/src/TOFMatchChecker.cxx
> +  }
done

2021-10-18 10:15 UTC, noferini commented on Detectors/GlobalTrackingWorkflow/src/TOFMatchChecker.cxx
> +  }
done. It was needed before to fix other methods. Now removed

2021-10-18 10:15 UTC, noferini commented on Detectors/TOF/workflowIO/src/TOFMatchedReaderSpec.cxx
> +  ddMCMatchTOF[3] = new o2::header::DataDescription{"MCMTC_ITSTPCTRD"};
done

2021-10-18 10:15 UTC, noferini commented on DataFormats/Detectors/GlobalTracking/include/DataFormatsGlobalTracking/RecoContainerCreateTracksVariadic.h
> +      // no need to check isUsed: by construction this ITS-TPC was not used elsewhere
done

2021-10-18 10:16 UTC, noferini commented
I moved also almost all INFO -> DEBUG in TOF workflow

2021-10-18 10:24 UTC, shahor02 approved these changes

2021-10-19 07:11 UTC, noferini commented
FAILED: stage/tests/o2-test-framework-ExternalFairMQDeviceWorkflow 
It seems not related to this PR

2021-10-19 07:43 UTC, merged