DPL: if all the inputs are sporadic, then also the outputs will be
AliceO2Group/AliceO2 pull request #7605
Opened 2021-11-14 09:28 UTC by ktf

This is done to avoid having to change the lifetime of
all the devices which run on sampled and unsampled data alike.

2021-11-14 18:23 UTC, davidrohr commented
Does this work recursively? I.e. if device A gets sporadic outputs since all its inputs are sporadic, and device B receives messages from device A, the inputs of device B will only B all sporadic after the outputs of device A were adjusted. In that case also the outputs of device B must be adjusted. Does this PR work that way?

2021-11-14 20:10 UTC, ktf commented
I am actually not completely sure. At the point the adjustTopology is invoked, I think the devices are topologically sorted, so it should work as you want, but I would need to check.

2021-11-15 13:07 UTC, ktf commented
Works fine on hyperloop.

2021-11-15 13:08 UTC, ktf commented
Works fine on hyperloop.

2021-11-15 15:32 UTC, davidrohr requested changes
@ktf : This seems to work for the sporadic inputs, but it still does not work for QC. The problem seems to be that QC gets an QC/TIMER-***/0 input from the internal dpl clock.
I think the check `allSporadic` has to ignore that, and then it also has to check that there is at least one real sporadic input.

Currently, the QC tasks are still sending summaries to the internal DPL clock (see attached plot)
![qc](https://user-images.githubusercontent.com/9131638/141809060-45cf56b5-6286-4ea2-b044-1f702053c6e7.png)

2021-11-15 16:31 UTC, ktf commented
I think this implements the changes you asked for although I am not 100% sure of the logic.

2021-11-18 21:49 UTC, davidrohr approved these changes
Passes the FST on the EPN if rate throttling is not enabled, i.e. doesn't break anything.
The incorrect summary messages are gone, but the test with rate throttling still gets stuck. I think we can merge this and keep serching for the next problem.

2021-11-19 07:20 UTC, merged