[EMCAL-565][WiP]: Add calibrator structure.
AliceO2Group/AliceO2 pull request #7631
Opened 2021-11-16 14:26 UTC by hjbossi

- Work in progress to add the calibrator structure.

2021-11-18 08:19 UTC, mfasDa commented
@hjbossi There are still merge conflicts that need to be resolved before testing - did you rebase to dev before pushing?

2021-11-22 15:24 UTC, hjbossi commented
Hi @mfasDa - the merge conflicts should be resolved. Let me know if you have any other comments!

2021-11-22 15:41 UTC, mfasDa requested changes
Still not ready for merge. There are still leftovers from the manual merge + there are files added that should not be added. Before merging please rebase again to dev in order to incorporate the changes from @jokonig .

2021-11-22 15:41 UTC, mfasDa commented on Common/Utils/CMakeLists.txt
> +=======
Merge conflicts not resolved.

2021-11-22 15:41 UTC, mfasDa commented on dpl-config.json
> +}
File must not enter at all

2021-11-22 15:41 UTC, mfasDa commented on Detectors/EMCAL/workflow/src/RecoWorkflow.cxx
> +  allowedIO[InputType::BoostHisto] = std::vector<OutputType>{OutputType::BadChannelMap};
Not needed in reco workflow, the calibration params are handled via the internal CCDB interface. I guess you mixed up something with the calibrator workflow.

2021-11-22 15:41 UTC, mfasDa commented on Detectors/EMCAL/workflow/include/EMCALWorkflow/RecoWorkflow.h
> +                         BadChannelMap     ///< EMCAL bad channel map
Not needed in reco workflow, the calibration params are handled via the internal CCDB interface. I guess you mixed up something with the calibrator workflow.

2021-11-22 16:19 UTC, mfasDa requested changes

2021-11-22 16:19 UTC, mfasDa commented on Detectors/EMCAL/calibration/src/EMCALChannelData.cxx
> +void EMCALChannelData::buildHitAndEnergyMean(double emin, double emax)
Needs to move to the CalibExtractor, mEsumHisto should no longer be a class member but a return object.

2021-11-22 16:19 UTC, mfasDa commented on Detectors/EMCAL/calibration/src/EMCALChannelData.cxx
> +void EMCALChannelData::buildHitAndEnergyMeanScaled(double emin, double emax)
Also need to go to the CalibExtractor.

2021-11-22 16:19 UTC, mfasDa commented on Detectors/EMCAL/calibration/src/EMCALChannelData.cxx
> +      mEsumHistoScaled(cell, Esum / (Nsum)); //..average energy per hit
No class member but local variable which serves as return value

2021-11-22 16:19 UTC, mfasDa commented on Detectors/EMCAL/calibration/src/EMCALSlotCalibLinkDef.h
> +#endif
Needs to go as well.

2021-11-22 18:03 UTC, mfasDa submitted a review, later dismissed
OK now from my side

2021-11-26 22:10 UTC, mfasDa commented
Should be fine now. @sawenzel @shahor02 Can you please merge when the tests pass?

2021-11-29 15:10 UTC, mfasDa approved these changes

2021-11-29 15:12 UTC, mfasDa commented
@sawenzel Do you think this could be merged now?

2021-12-01 09:55 UTC, merged