DPL Analysis: introduce filter selection caching
AliceO2Group/AliceO2 pull request #7726
Opened 2021-11-24 12:01 UTC by aalkin

* Renamed `FilteredPolicy` to `FilteredBase` to better describe its role.
* `Filtered<>` now uses span to handle the selection, backed either by internal cache or external buffer. 
* Framework-managed `Filtered` and `Partition` now have their selections and gandiva filters cached by the framework per data frame, improving performance in cases where they are used in several `process()` functions
* Derived `Filtered` objects (sum or intersection) switch to internal cache automatically
* Combinations with filters will use internal caches
* Fixed bug in Combinations where temporary `Filtered` objects were not owned

2021-11-25 08:19 UTC, ktf requested changes
Seems to break the tests.

2021-11-25 14:00 UTC, aalkin commented
Now it passes tests, but breaks tasks in O2Physics that use combinations, investigating.

2021-11-26 22:53 UTC, aalkin commented
@ktf the latest change fixes the remaining issues.

2021-11-29 10:11 UTC, ktf commented
Seems to fail systematically on hyperloop https://alimonitor.cern.ch/train-workdir/tests/0001/00016096/stdout.log

2021-11-30 16:27 UTC, aalkin commented
@ktf should be working now: apparently when I removed `const` in various places, I've also removed `&` which lead to selection cache not being updated. Seeing as everything else was already working, could you test this on hyperloop without waiting for CI?

2021-11-30 23:24 UTC, ktf commented
Tested on hyperloop. Merging.

2021-11-30 23:25 UTC, merged