Better cuts for calibration and reconstruction
AliceO2Group/AliceO2 pull request #7902
Opened 2021-12-24 10:59 UTC by AllaMaevskaya

2021-12-24 16:27 UTC, AllaMaevskaya commented
Would be very good to use it in apass2

2021-12-24 22:24 UTC, chiarazampolli commented
Hi Alla,

apass2 is already running, and probably almost completed.

chiara

2021-12-25 07:02 UTC, AllaMaevskaya commented
OK, I hope will be apass3 :)

2022-01-07 20:02 UTC, shahor02 requested changes

2022-01-07 20:02 UTC, shahor02 commented on Detectors/FIT/FT0/calibration/src/FT0ChannelTimeTimeSlotContainer.cxx
> +    //    } else {
could you remove commented code?

2022-01-07 20:02 UTC, shahor02 commented on Detectors/FIT/FT0/calibration/src/FT0ChannelTimeTimeSlotContainer.cxx
> +    mHistogram[ich] = new TH1F(Form("hTime%i", ich), "time", NUMBER_OF_HISTOGRAM_BINS, -HISTOGRAM_RANGE, HISTOGRAM_RANGE);
you are allocating data members with new but have no destructor to delete them, since the slots created/deleted during processing, this will lead to run-time memory leak. Either use std::array<std::unique_ptr<TH1F>, 208> or at least add a proper destructor. Also, we already had a lot of confusion with different hardcoded number of channels, could you use uniquely defined const?

2022-01-07 20:02 UTC, shahor02 commented on Detectors/FIT/FT0/calibration/src/FT0ChannelTimeTimeSlotContainer.cxx
> +    LOG(info) << " entries " << mEntriesPerChannel[iCh] << " " << prev->mEntriesPerChannel[iCh];
this might be too verbose

2022-01-07 20:02 UTC, shahor02 commented on Detectors/FIT/FT0/calibration/testWorkflow/FT0TFProcessor-Workflow.cxx
> -*/
remove obsolete code

2022-01-08 17:01 UTC, shahor02 requested changes

2022-01-08 17:01 UTC, shahor02 commented on Detectors/FIT/FT0/calibration/src/FT0ChannelTimeTimeSlotContainer.cxx
> +    mHistogram[ich].reset(static_cast<TH1F*>(other.mHistogram[ich]->Clone()));
Clone is very expensive operation, please use simply a copy constructor:
```
mHistogram[ich].reset(new TH1F(*other.mHistogram[ich].get()));
```

2022-01-08 17:01 UTC, shahor02 commented on Detectors/FIT/FT0/calibration/src/FT0ChannelTimeTimeSlotContainer.cxx
> +    mHistogram[ich].reset(static_cast<TH1F*>(other.mHistogram[ich]->Clone()));
idem

2022-01-10 09:55 UTC, merged