Improving sensitive hit creation for FT0 in Detector.cxx
AliceO2Group/AliceO2 pull request #7961
Opened 2022-01-18 08:27 UTC by zovarga

- The Detector::ProcessHits(FairVolume* v) function had too many string comparisons which made it slow. The comparison was modified to be based on integer IDs instead.
- The calculation of some quantities (etot, enDep, parentID) were moved inside the relevant if() statement block (i.e. when the particle is a photon), so they are only calculated when necessary.

2022-01-18 14:39 UTC, sawenzel commented on Detectors/FIT/FT0/simulation/src/Detector.cxx
> +  Int_t volMTO = fMC->VolId("0MTO");
these should be cached as data members inside the Detector class to avoid calling `VolId` again and again.

2022-01-18 14:40 UTC, sawenzel requested changes
Looks good. Please still address the comment concerning caching volume ids as data members.

2022-01-19 10:10 UTC, AllaMaevskaya submitted a review, later dismissed

2022-01-20 15:01 UTC, zovarga commented
Thank you for the review, I implemented the requested changes.

2022-01-21 08:11 UTC, sawenzel commented on Detectors/FIT/FT0/simulation/include/FT0Simulation/Detector.h
> +  int mtoVolID = -1;
please note that class member variables need to follow the `mFooBar` notation.

2022-01-21 09:10 UTC, sawenzel approved these changes

2022-01-21 10:39 UTC, sawenzel commented
@ktf @TimoWilken : There is a weird alibuild error here:
```
++ alibuild-generate-module --bin --lib
/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SPECS/osx_arm64/TBB/v2021.5.0-local1/TBB.sh: line 13: alibuild-generate-module: command not found
```
I have seen this locally as well this morning.

2022-01-21 10:56 UTC, TimoWilken commented
Looks like TBB should depend on alibuild-recipe-tools!

2022-01-21 10:58 UTC, sawenzel commented
@TimoWilken : Right. But why did all the tests in alidist pass? It appears to be a bit platform-dependent at least.

2022-01-21 11:02 UTC, TimoWilken commented
Maybe the build order changed, and something else that depends on alibuild-recipe-tools was built before TBB. In that case, even though TBB doesn't explicitly depend on a-r-t, it would have it available. In this case, TBB was built before anything that pulls in a-r-t, so a-r-t wasn't available.

2022-01-21 13:54 UTC, merged