dEdx topology correction: using threshold and qTot as input for qTot correction
AliceO2Group/AliceO2 pull request #8120
Opened 2022-02-11 10:25 UTC by matthias-kleiner

- adding scaling of topology correction

2022-02-18 14:38 UTC, wiechula requested changes

2022-02-18 14:38 UTC, wiechula commented on DataFormats/Detectors/TPC/include/DataFormatsTPC/CalibdEdxTrackTopologyPol.h
> +    const float corr = chargeT == ChargeType::Tot ? getCorrectionqTot(region, tanTheta, sinPhi, z, threshold, charge) : getCorrectionqMax(region, tanTheta, sinPhi, z, relPad, relTime);
Readability braces
```suggestion
    const float corr = (chargeT == ChargeType::Tot) ? getCorrectionqTot(region, tanTheta, sinPhi, z, threshold, charge) : getCorrectionqMax(region, tanTheta, sinPhi, z, relPad, relTime);
```

2022-02-19 13:01 UTC, matthias-kleiner commented on DataFormats/Detectors/TPC/include/DataFormatsTPC/CalibdEdxTrackTopologyPol.h
> +    const float corr = chargeT == ChargeType::Tot ? getCorrectionqTot(region, tanTheta, sinPhi, z, threshold, charge) : getCorrectionqMax(region, tanTheta, sinPhi, z, relPad, relTime);
Thanks, fixed it along with some other minor changes

2022-02-19 14:26 UTC, matthias-kleiner commented
The following file contains the new splines and polynomials for the correction [dedx_corrections.zip](https://github.com/AliceO2Group/AliceO2/files/8102329/dedx_corrections.zip)

[dE/dx vs tgl after correction with splines](https://github.com/AliceO2Group/AliceO2/files/8102332/tgl_spline.pdf)
[dE/dx vs tgl after correction with polynomials](https://github.com/AliceO2Group/AliceO2/files/8102334/tgl_pol.pdf)

2022-02-20 16:44 UTC, wiechula approved these changes

2022-02-20 17:09 UTC, merged