Hmpid dcsccdb improvments
AliceO2Group/AliceO2 pull request #8167
Opened 2022-02-16 12:55 UTC by fapfap69

2022-02-17 08:45 UTC, shahor02 requested changes
Hi @fapfap69 

Please see comments below, also, the PR fails due to the clang-format.

Cheers,
 Ruben

2022-02-17 08:45 UTC, shahor02 commented on Detectors/HMPID/workflow/src/PedestalsCalculationSpec.cxx
> +  long maxTimeStamp = o2::ccdb::getFutureTimestamp(60 * 60 * mDcsCcdbAliveHours * 1);
This should be an absolute end-validity time in ms, i.e. `maxTimeStamp = minTimeStamp + 3600L * DcsCcdbAliveHours * 1000;`

2022-02-17 08:45 UTC, shahor02 commented on Detectors/HMPID/workflow/src/PedestalsCalculationSpec.cxx
> +  long maxTimeStamp = o2::ccdb::getFutureTimestamp(60 * 60 * 24 * (5 * 365)); // 5 years
same here

2022-02-18 11:48 UTC, fapfap69 commented
@shahor02 I did the clang-format fix, now seems that all checks passed

2022-02-18 12:33 UTC, shahor02 approved these changes

2022-02-18 12:33 UTC, merged