[O2-2748] Enable Compiler Warnings
AliceO2Group/AliceO2 pull request #8194
Opened 2022-02-21 15:33 UTC by MichaelLettrich

Enable most warnings in `- Wall` and `-Wextra` in O2, but make sure they don't lead to compile errors even if `-Werror` is enabled. 

DO NOT MERGE - this tests the different behaviors on clang and GCC.

2022-02-21 16:26 UTC, TimoWilken commented
Looks like clang on Mac gets confused. Disabling the `unknown-warning-option` warning should silence this, if it's fine to have some of these only on Linux?

2022-02-21 16:30 UTC, MichaelLettrich commented
@TimoWilken thanks for noticing. It looks like this is a clang vs gcc missmatch of some warnings. I'll add the `-Wno-unknown-warning-option` to the cmake.

2022-03-18 10:54 UTC, ktf commented
What do we plan to do with this? I am against keeping this open indefinitely until people act on them.

2022-03-18 10:54 UTC, ktf requested changes
Either someone is tasked to fix the errors or this will be closed.

2022-03-18 11:02 UTC, MichaelLettrich commented
Hi, I'm taking care of it till the next WP3 meeting.

2022-03-18 11:12 UTC, davidrohr commented
Shouldn't we generally disable `-Wpre-c++17-compat` ? We don't need pre c++17 compatibility?

2022-03-21 16:02 UTC, MichaelLettrich commented
@ktf  this should be it. 
As discussed with Timo, we would introduce the  `ALIBUILD_O2_WARNINGS` environment variable, which enables building O2 with a selected set of warnings, but not trearing them as errors. 
I enabled building with warnings for the CI, just to make sure it works on all platforms, I will remove the last commit before merging.

2022-03-22 16:27 UTC, MichaelLettrich commented
@ktf the CI passed and the warnings generated by Clang were comparable to the ones generated by GCC. As requested by you, warnings are disabled by default and are enabled by setting the environment variable `ALIBUILD_ENABLE_WARNINGS`. This is ready to merge. Please review and merge if you think this is OK.

2022-03-23 09:11 UTC, merged