macros to populate and read the GRP DCS config entry
AliceO2Group/AliceO2 pull request #8317
Opened 2022-03-11 11:25 UTC by chiarazampolli

2022-03-11 21:03 UTC, chiarazampolli commented
Hello @aphecetche , @wiechula , @mpoghos , @syano0822, @shahor02 ,

This should fix the issue with the fact that ADAPOS Is now sending DPVAL instead of RAW types (@wiechula, @martenole  : you might need to fix this in your ongoing development for DCS DataPoints processing).

I tested the changes in GRP + getValue function of DataPointCompositeObject, and it worked. 

Chiara

2022-03-14 10:04 UTC, chiarazampolli commented
Changed to WIP to see how today's test behave.

Chiara

2022-03-14 21:05 UTC, chiarazampolli commented
Working with today's tests for MFT, TOF, MCH, EMCAL, GRP, so moving to ready for review.

2022-03-17 20:32 UTC, shahor02 commented
Hi @chiarazampolli there are conflicts to resolve...

2022-03-17 20:36 UTC, chiarazampolli commented
Hi @shahor02 , 

Yes, because meanwhile also detectors committed similar fixes :-) 
I will take care, I need also to move the GRP CCDB object from Calib to Config, as we discussed today. 

Chiara

2022-03-17 21:02 UTC, chiarazampolli commented
@shahor02 , conflicts solved. 
I think that this PR is ready, after the tests are passed.

2022-03-19 17:25 UTC, chiarazampolli commented
Hi @shahor02 , 
At your convenience, could you check this PR?
Thanks!
Chiara

2022-03-19 18:12 UTC, shahor02 requested changes

2022-03-19 18:12 UTC, shahor02 commented on Detectors/GRP/calibration/src/GRPDCSDPsProcessor.cxx
> +  o2::calibration::Utils::prepareCCDBobjectInfo(mLHCInfo, mccdbLHCIFInfo, "GLO/Config/LHCIF", md, mStartValidity, mStartValidity + 3 * 3600000); // valid for 3 days
It is 3 hours, not 3 days, can you change it to mStartValidity + 24L*3*3600000;  ? (Note `L`)
Same comment for the lines below.

2022-03-19 19:32 UTC, chiarazampolli commented on Detectors/GRP/calibration/src/GRPDCSDPsProcessor.cxx
> +  o2::calibration::Utils::prepareCCDBobjectInfo(mLHCInfo, mccdbLHCIFInfo, "GLO/Config/LHCIF", md, mStartValidity, mStartValidity + 3 * 3600000); // valid for 3 days
Yes, sorry, I forgot to do 24*, and copied pasted. I will fix it.
Why 24L33600000? Why twice “3”?

chiara

2022-03-19 20:15 UTC, chiarazampolli commented on Detectors/GRP/calibration/src/GRPDCSDPsProcessor.cxx
> +  o2::calibration::Utils::prepareCCDBobjectInfo(mLHCInfo, mccdbLHCIFInfo, "GLO/Config/LHCIF", md, mStartValidity, mStartValidity + 3 * 3600000); // valid for 3 days
Or did you mean 24L*3600000?

2022-03-19 20:23 UTC, chiarazampolli commented on Detectors/GRP/calibration/src/GRPDCSDPsProcessor.cxx
> +  o2::calibration::Utils::prepareCCDBobjectInfo(mLHCInfo, mccdbLHCIFInfo, "GLO/Config/LHCIF", md, mStartValidity, mStartValidity + 3 * 3600000); // valid for 3 days
Ok it is for the 3 days, now i got it. Sorry, long day…

2022-03-19 20:39 UTC, shahor02 commented on Detectors/GRP/calibration/src/GRPDCSDPsProcessor.cxx
> +  o2::calibration::Utils::prepareCCDBobjectInfo(mLHCInfo, mccdbLHCIFInfo, "GLO/Config/LHCIF", md, mStartValidity, mStartValidity + 3 * 3600000); // valid for 3 days
Github has swallowed `*`, I meant `24L*3*3600000`

2022-03-19 20:48 UTC, chiarazampolli commented on Detectors/GRP/calibration/src/GRPDCSDPsProcessor.cxx
> +  o2::calibration::Utils::prepareCCDBobjectInfo(mLHCInfo, mccdbLHCIFInfo, "GLO/Config/LHCIF", md, mStartValidity, mStartValidity + 3 * 3600000); // valid for 3 days
Yes, yes, I implemented it like that. I thought it meant something special initially :-) 
Marking as resolved.

2022-03-20 07:34 UTC, shahor02 approved these changes

2022-03-20 07:35 UTC, merged