Switch to CCDB fetcher; Fix energy calibrator;
AliceO2Group/AliceO2 pull request #8454
Opened 2022-03-28 09:38 UTC by peressounko

2022-03-29 05:20 UTC, peressounko commented
Dear @shahor02, could you please have a look at this PR?

2022-03-29 11:11 UTC, shahor02 requested changes
Hi @peressounko 

What is the reason to keep `useCCDB` options? The standard way should be to have  reasonable default objects overridden by specific objects and always use CCDB.
Then, I see that you are controlling the 1st update of CCDB objects by `mHasCalib`. Why don't you use the finaliseCCDB method, which is called each time the object is updated?
It is much more universal, see e.g.:
https://github.com/AliceO2Group/AliceO2/blob/ba7db323bd148725212e318980612998d9e4e5ef/Detectors/ITSMFT/common/workflow/src/STFDecoderSpec.cxx#L253-L267
with the check triggered by 
https://github.com/AliceO2Group/AliceO2/blob/ba7db323bd148725212e318980612998d9e4e5ef/Detectors/ITSMFT/common/workflow/src/STFDecoderSpec.cxx#L242-L249
called from
https://github.com/AliceO2Group/AliceO2/blob/ba7db323bd148725212e318980612998d9e4e5ef/Detectors/ITSMFT/common/workflow/src/STFDecoderSpec.cxx#L137

2022-03-29 11:11 UTC, shahor02 commented on Detectors/PHOS/calib/include/PHOSCalibWorkflow/PHOSEnergyCalibrator.h
> +  const std::vector<uint32_t>& getCollectedDigits() { return mDigits; }
this should be const method

2022-03-29 11:11 UTC, shahor02 commented on Detectors/PHOS/calib/include/PHOSCalibWorkflow/PHOSEnergyCalibrator.h
> -  ClassDefNV(PHOSEnergySlot, 1);
You've suppressed  the ClassDef for this class but did not remove it from the `Detectors/PHOS/calib/src/PHOSCalibWorkflowLinkDef.h`

2022-03-29 11:11 UTC, shahor02 commented on Detectors/PHOS/calib/src/PHOSEnergyCalibDevice.cxx
> +    const o2::phos::BadChannelsMap* badMap = badMapPtr.get();
why not simply 
```
auto badMapPtr = pc.inputs().get<o2::phos::BadChannelsMap*>("bdmap");
mCalibrator->setBadMap(badMapPtr.get());
```
You don't need to check if the object is not fetched, the DPL fetcher will produce Fatal in that case.

2022-03-29 11:11 UTC, shahor02 commented on Detectors/PHOS/calib/src/PHOSEnergyCalibrator.cxx
> +          LOG(error) << "Too many clusters per event:" << i - firstCluInEvent << ", apply more strict selection; clusters with same indexes will appear";
if this should attract attention in the infologger, please use `LOG(important)`. `error` is for the algorithmic errors.

2022-03-30 05:55 UTC, peressounko commented
Dear @shahor02, thank you for careful reading, I am implementing your suggestions. Concerning reading or not CCDB objects, there are 2 arguments: 1) with my connection it takes ~50% of time to check if there is a new objects and clusterization itself. I did not make real timing, but looked at the speed of output. We need object once at the very beginning but fetcher checks it again and again. Probably, with finaliseCCDB one can avoid it - I am checking. 2) We need possibility to apply empty bad map e.g. for re-calculation of bad map. Normally fetcher will provide the most recent and complete bad map. So, for clusterizer at EPN for QC and calibration we will need one map, for cluterizer for AOD analysis - another (stricter) bad map and calibration. I will think, should we provide two kinds of bad map "definitely bad" and "one for physics analysis".

2022-03-30 07:14 UTC, shahor02 commented
Hi @peressounko 
The DPL fetcher will anyway check the validity of the object (w/o fetching it if the cached one is still valid) for every TF, this is required behaviour. The finaliseCCDB (where you can do assignments) will be called only when the new object is fetched, effectively only once for long-lived objects.
For the empty maps: ok, if for certain operations you need to disable loading the object, this justifies the switch.

2022-03-30 07:34 UTC, peressounko commented
Dear @shahor02, should we then return to BasicCCDBManager to get object once instead of fetching it each TF?

2022-03-30 09:08 UTC, shahor02 commented
> Dear @shahor02, should we then return to BasicCCDBManager to get object once instead of fetching it each TF?

Why? The DPL fetcher does not fetch the object at every TF. In the normal mode, when you need calibration from the CCDB, you should use DPL fetcher and delegate all updates to finaliseCCDB.
In the calibration mode, where you don't need external objects, you should simply not subscribe to these objects, like you already do in https://github.com/AliceO2Group/AliceO2/blob/5dcd383353f1de0919898e96199d044d97b5b962/Detectors/PHOS/calib/src/PHOSEnergyCalibDevice.cxx#L126-L129 *AND* do not quere the data provided by these inputs.
E.g. in the ITS, when I don't need certain object, I have this check:
https://github.com/AliceO2Group/AliceO2/blob/a686cf43c7fd57e5b91a21213ee43b3326d13e48/Detectors/ITSMFT/common/workflow/src/STFDecoderSpec.cxx#L299-L302
followed by the check https://github.com/AliceO2Group/AliceO2/blob/a686cf43c7fd57e5b91a21213ee43b3326d13e48/Detectors/ITSMFT/common/workflow/src/STFDecoderSpec.cxx#L246-L248 done for every TF. Note that it is `pc.inputs().get...` for the CCDB input which triggers finaliseCCDB (provided that the object was updated by the fetcher).

2022-03-30 12:09 UTC, peressounko commented
Dear @shahor02, it there any difference in terms of performance between current implementation where I once pick up (permanent) calib object checking with switch mHasCalib and approach with finaliseCCDB which you implemented e.g. in CTFDecoderSpec? Fetcher will anyway check updates of calib Object in both cases? If there is no diff, I would prefer current implementation.

2022-03-30 13:36 UTC, shahor02 commented
@peressounko it is important to use DPL fetcher to minimize the number of connections. As for using finaliseCCDB or taking the object only once from `pc.inputs().get...`, this is up to you.

2022-03-31 11:37 UTC, peressounko commented
Dear @shahor02, I think we can commit current version. It uses Fetcher or no CCDB access at all. I implemented other your comments

2022-03-31 12:28 UTC, merged

2022-03-31 18:31 UTC, sawenzel commented
This PR leads to crashes in unanchored MC (and will likely affect GRID productions). See for instance https://mattermost.web.cern.ch/aliperf-pdp/pl/bp1p6jzjijgudr3fot3gx54c9a. It would be good providing a default object on CCDB to which we can always fall-back.