Fixing updating of TPC calibs from CCDB
AliceO2Group/AliceO2 pull request #8475
Opened 2022-03-30 13:56 UTC by matthias-kleiner

- moving TPC code to separate functions

2022-03-30 14:03 UTC, wiechula commented
@davidrohr , wouldn't it in general be nicer to convert the workflow to a class inheriting from `Task`? This might look more structured.

2022-03-30 18:03 UTC, davidrohr commented on GPU/Workflow/src/GPUWorkflowSpec.cxx
> +void setCalibsTPC(ProcessAttributes* processAttributes);
perhaps we can find a better name here, like `storeUpdatedCalibsTPCPtrs` instead of `setCalibsTPC` to make it clear what happens here.

2022-03-30 18:03 UTC, davidrohr requested changes
This is exactly what I meant in the mail exchange, except for one minor comment on a misleading function name below.

2022-03-31 07:09 UTC, matthias-kleiner commented
> This is exactly what I meant in the mail exchange, except for one minor comment on a misleading function name below.

Okay, thanks for checking the code. I renamed the function and squashed the commits

2022-03-31 11:41 UTC, davidrohr commented
> @davidrohr , wouldn't it in general be nicer to convert the workflow to a class inheriting from `Task`? This might look more structured.

Yes, I agree, but I'd try to get this in first, then we can try to change it perhaps. But migrating to a task was not a priority yet, since I don't see any benefit except for being more in line with other workflows. Note this one was developed before this task class was available.

2022-03-31 11:42 UTC, merged