[EMCAL-566]: Optimized EMCal time calibration
AliceO2Group/AliceO2 pull request #8556
Opened 2022-04-11 20:34 UTC by jokonig

- Writing to the ccdb now implemented (and checked using the test-ccdb)
- Included EMCALCalibParams to steer when the calibration should be
triggered. Can be done on the basis of entres in the histogram or the
number of events obtained from the EMCAL trigger record
- Fixed resetting of the histograms after the calibration is
triggered

2022-04-12 13:34 UTC, mfasDa requested changes
Hi @jokonig, looks mostly good. One thing to change is to remove steering of the EMCALCalibParams via the workflow arguments - as the class inherits from O2ConfigurableParam the framework will take care of this step.

2022-04-12 13:34 UTC, mfasDa commented on Detectors/EMCAL/calibration/testWorkflow/EMCALChannelCalibratorSpec.h
> +    minNEvents = ic.options().get<int>("minNEvents");
Not needed

2022-04-12 13:34 UTC, mfasDa commented on Detectors/EMCAL/calibration/testWorkflow/emc-channel-calib-workflow.cxx
> +  specs.emplace_back(getEMCALChannelCalibDeviceSpec(minNEntries, minNEvents, strCalibType, strFilePath));
Not needed

2022-04-12 13:34 UTC, mfasDa commented on Detectors/EMCAL/calibration/testWorkflow/emc-channel-calib-workflow.cxx
> +                                       {"minNumEvents", VariantType::Int, 10000, {"minimum number of events to trigger calibration"}},
Not needed

2022-04-19 08:50 UTC, mfasDa submitted a review, later dismissed
One small cleanup needed but that doesn't harm and can be done in a second iteration, should not hold the merging.

2022-04-19 09:02 UTC, mfasDa commented on Detectors/EMCAL/calibration/testWorkflow/emc-channel-calib-workflow.cxx
> +                                       {"minNumEvents", VariantType::Int, 10000, {"minimum number of events to trigger calibration"}},
This was probably overlooked

2022-04-19 09:24 UTC, jokonig commented on Detectors/EMCAL/calibration/testWorkflow/emc-channel-calib-workflow.cxx
> +                                       {"minNumEvents", VariantType::Int, 10000, {"minimum number of events to trigger calibration"}},
yes I overlooked that... I removed it.

2022-04-20 07:39 UTC, mfasDa commented
I set the PR to WIP waiting for the changes also from @hjbossi to include also the BCM chain.

2022-04-21 07:40 UTC, mfasDa approved these changes, later dismissed
I think we better merge this now and handle the changes from @hjbossi in a separate PR, otherwise we will by now get too many rebases

2022-04-22 08:35 UTC, merged