[WIP] TPC QC: make IDC plots (v. 1)
AliceO2Group/AliceO2 pull request #8572
Opened 2022-04-13 09:41 UTC by tklemenz

2022-04-13 09:43 UTC, tklemenz commented
This is the first version of the IDCs visualization for QC.

Fourier coefficients are not yet included (timestamp -1 for getting the data from the CCDB is not working for them for now) and there is a fit missing to the radial IDC0 distribution. 
This will come in a later update.

2022-04-13 09:46 UTC, tklemenz commented
Clang format gives an error at the moment, that is why the check is failing.

`clang-format-6.0 -style=file -i IDCs.cxx`
`YAML:52:19: error: unknown key 'DeriveLineEnding'`
`DeriveLineEnding: true`
`Error reading /home/tklemenz/AliSoftware/QualityControl/.clang-format: Invalid argument`

I will investigate.

2022-05-05 14:43 UTC, tklemenz commented
The issue with clang-format is fixed and the Fourier Coefficients are now included.

2022-05-10 13:46 UTC, wiechula requested changes

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/include/TPCCalibration/IDCCCDBHelper.h
> +
Why do you need these functions twice, once in the private and then wrapped here in the public part? Can't you simply move the definitions from the private part here?

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/include/TPCCalibration/IDCDrawHelper.h
> +  static TH2Poly* drawSide(const IDCDraw& idc, const o2::tpc::Side side, const std::string zAxisTitle);
If you plan to use `TH2Poly` in QC one has to be very careful, I think. These will be huge ...

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCCCDBHelper.cxx
> +  hCside2D = IDCDrawHelper::drawSide(drawFun, Side::C, zAxisTitle);
```suggestion
  auto hAside2D = IDCDrawHelper::drawSide(drawFun, Side::A, zAxisTitle);
  auto hCside2D = IDCDrawHelper::drawSide(drawFun, Side::C, zAxisTitle);
```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCCCDBHelper.cxx
> +  hCside1D = IDCDrawHelper::drawSide(drawFun, fmt::format("{}", type.data()).data(), Side::C, nbins1D, xMin1D, xMax1D);
```suggestion
  auto hAside1D = IDCDrawHelper::drawSide(drawFun, fmt::format("{}", type.data()).data(), Side::A, nbins1D, xMin1D, xMax1D);
  auto hCside1D = IDCDrawHelper::drawSide(drawFun, fmt::format("{}", type.data()).data(), Side::C, nbins1D, xMin1D, xMax1D);
```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCCCDBHelper.cxx
> +
```suggestion
  hAside2D->SetBit(TObject::kCanDelete);
  hCside2D->SetBit(TObject::kCanDelete);
  hAside1D->SetBit(TObject::kCanDelete);
  hCside1D->SetBit(TObject::kCanDelete);

```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCCCDBHelper.cxx
> +  TH2F* hCside2D = nullptr;
```suggestion
```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCCCDBHelper.cxx
> +  hAside2D->GetXaxis()->SetTitle("x (mm)");
Our default unit is `cm`, please adapt the code.

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCCCDBHelper.cxx
> +  hCside2D = new TH2F("h_IDC0_radialProfile_Cside", "IDC0: Radial profile (C-Side)", 155, xBins, nbinsY, yMin, yMax);
```suggestion
  auto hCside2D = new TH2F("h_IDC0_radialProfile_Cside", "IDC0: Radial profile (C-Side)", radialBinning.size()-1, radialBinning.data(), nbinsY, yMin, yMax);
```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCCCDBHelper.cxx
> +
```suggestion

  hAside2D->SetBit(TObject::kCanDelete);
  hCside2D->SetBit(TObject::kCanDelete);
```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCCCDBHelper.cxx
> +  hCside1D->SetBit(TObject::kCanDelete);
```suggestion
  canv->SetBit(TObject::kCanDelete);
```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCDrawHelper.cxx
> +  std::string sideName = side == Side::A ? "A" : "C";
readability braces
```suggestion
  std::string sideName = (side == Side::A) ? "A" : "C";
```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/include/TPCCalibration/IDCDrawHelper.h
> +  static void drawRadialProfile(const IDCDraw& idc, TH2F* hist, const o2::tpc::Side side, const int nbinsY, const float yMin, const float yMax);
```suggestion
  static void drawRadialProfile(const IDCDraw& idc, TH2F& hist, const o2::tpc::Side side, const int nbinsY, const float yMin, const float yMax);
```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCCCDBHelper.cxx
> +  IDCDrawHelper::drawRadialProfile(drawFun, hCside2D, Side::C, nbinsY, yMin, yMax);
```suggestion
  IDCDrawHelper::drawRadialProfile(drawFun, *hAside2D, Side::A, nbinsY, yMin, yMax);
  IDCDrawHelper::drawRadialProfile(drawFun, *hCside2D, Side::C, nbinsY, yMin, yMax);
```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCDrawHelper.cxx
> +void o2::tpc::IDCDrawHelper::drawRadialProfile(const IDCDraw& idc, TH2F* hist, const o2::tpc::Side side, int nbinsY, float yMin, float yMax)
```suggestion
void o2::tpc::IDCDrawHelper::drawRadialProfile(const IDCDraw& idc, TH2F& hist, const o2::tpc::Side side)
```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCDrawHelper.cxx
> +void o2::tpc::IDCDrawHelper::drawIDCZeroStackCanvas(const IDCDraw& idc, const o2::tpc::Side side, const std::string_view type, int nbins1D, float xMin1D, float xMax1D, TCanvas* outputCanvas, int inte
```suggestion
void o2::tpc::IDCDrawHelper::drawIDCZeroStackCanvas(const IDCDraw& idc, const o2::tpc::Side side, const std::string_view type, int nbins1D, float xMin1D, float xMax1D, TCanvas& outputCanvas, int integrationInterval)
```
And required changes below.

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/include/TPCCalibration/IDCDrawHelper.h
> +  static void drawIDCZeroStackCanvas(const IDCDraw& idc, const o2::tpc::Side side, const std::string_view type, const int nbins1D, const float xMin1D, const float xMax1D, TCanvas* outputCanvas, int i
```suggestion
  static void drawIDCZeroStackCanvas(const IDCDraw& idc, const o2::tpc::Side side, const std::string_view type, const int nbins1D, const float xMin1D, const float xMax1D, TCanvas& outputCanvas, int integrationInterval);
```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCDrawHelper.cxx
> +TH2Poly* o2::tpc::IDCDrawHelper::drawSide(const IDCDraw& idc, const o2::tpc::Side side, const std::string zAxisTitle)
call this function in the one above.

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCDrawHelper.cxx
> +          }
```suggestion
  const auto padNum = Mapper::getGlobalPadNumber(irow, ipad, region);
  const float padX = mapper.padCentre(padNum).x();
  hist.Fill(padX, idc.getIDC(sector, region, irow, padTmp));
```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCCCDBHelper.cxx
> +  hAside2D = new TH2F("h_IDC0_radialProfile_Aside", "IDC0: Radial profile (A-Side)", 155, xBins, nbinsY, yMin, yMax);
I added a function for the binning to the Painter: https://github.com/AliceO2Group/AliceO2/pull/8772
Once it is merged you can use it:
```suggestion
  const auto radialBinning = painter::getRowBinningCM();
  
  auto hAside2D = new TH2F("h_IDC0_radialProfile_Aside", "IDC0: Radial profile (A-Side)", radialBinning.size()-1, radialBinning.data(), nbinsY, yMin, yMax);
```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCDrawHelper.cxx
> +  const int gap2 = 21;
```suggestion
const mapper& = Mapper::instance();
```

2022-05-10 13:46 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCDrawHelper.cxx
> +          }
```suggestion
          if (region < 4) {
            hIROC->Fill(idc.getIDC(sector, region, irow, padTmp));
          } else if (region < 6) {
            hOROC1->Fill(idc.getIDC(sector, region, irow, padTmp));
          } else if (region < 8) {
            hOROC2->Fill(idc.getIDC(sector, region, irow, padTmp));
          } else {
            hOROC3->Fill(idc.getIDC(sector, region, irow, padTmp));
         }
```

2022-05-10 15:36 UTC, tklemenz commented on Detectors/TPC/calibration/src/IDCCCDBHelper.cxx
> +  hCside1D->SetBit(TObject::kCanDelete);
I think this should stay as it is.

2022-05-10 16:28 UTC, tklemenz commented
I implemented everything except the binning, where I wait for the PR in the painter to be merged. 
@wiechula  Also please check the one comment above.

2022-05-12 13:15 UTC, wiechula commented on Detectors/TPC/calibration/src/IDCCCDBHelper.cxx
> +  hCside1D->SetBit(TObject::kCanDelete);
Yes, sure. My bad!

2022-05-12 13:18 UTC, wiechula requested changes
https://github.com/AliceO2Group/AliceO2/pull/8772 was merged, please change your code as suggested.

2022-05-13 13:35 UTC, wiechula approved these changes

2022-05-13 13:37 UTC, tklemenz commented
Should I leave WIP until the PR it depends on is merged?

2022-05-13 13:50 UTC, wiechula commented
Isn't it already merged?

2022-05-13 13:51 UTC, tklemenz commented
Ah, my bad. I looked at the wrong PR. So I remove it.

2022-05-13 13:55 UTC, wiechula commented
@shahor02 , @davidrohr , can this be merged?

2022-05-17 10:34 UTC, wiechula commented
can this be merged?

2022-05-17 10:36 UTC, merged