o2-eve: calorimeters display, fixes in json serialisation
AliceO2Group/AliceO2 pull request #8755
Opened 2022-05-08 14:18 UTC by jmyrcha

2022-05-08 15:40 UTC, pnwkw requested changes

2022-05-08 15:40 UTC, pnwkw commented on EventVisualisation/View/src/Initializer.cxx
> -    if (detName == "TPC" || detName == "MCH" || detName == "MID" || detName == "MFT") { // don't load MUON+MFT and AD and standard TPC to R-Phi view
An accidental regression during merge?

2022-05-08 16:46 UTC, jmyrcha commented on EventVisualisation/View/src/Initializer.cxx
> -    if (detName == "TPC" || detName == "MCH" || detName == "MID" || detName == "MFT") { // don't load MUON+MFT and AD and standard TPC to R-Phi view
fixed

2022-05-12 10:48 UTC, shahor02 approved these changes

2022-05-12 10:48 UTC, merged