TRD fixes for tracklets in trap 2 raw
AliceO2Group/AliceO2 pull request #8778
Opened 2022-05-10 21:10 UTC by bazinski

Tracklets are being dropped from trap2raw.
Checking the hex dumps of the raw data they are there now, and events are correctly aligned to 256 bits.
Still waiting for fst to finish.

2022-05-11 09:06 UTC, tdietel commented on Detectors/TRD/simulation/src/Trap2CRU.cxx
> +    if (trackletcounter > 0) { // dont write header if there are no tracklets.
This looks like it was a proper bug.. Do we know why it wasn't noticed?

2022-05-11 09:07 UTC, tdietel approved these changes, later dismissed
Looks straightforward, we can go ahead with the merge if the tests pass.

2022-05-11 09:08 UTC, bazinski commented on Detectors/TRD/simulation/src/Trap2CRU.cxx
> +    if (trackletcounter > 0) { // dont write header if there are no tracklets.
Good question. Basically the mcmheader would be written but never the mcmdata, which caused the data to not be aligned.

2022-05-11 09:21 UTC, martenole commented
No, this does not yet fix the error I saw. Just tried again to do the MC->raw conversion and now both the numbers of digits and the number of tracklets are not the same in the raw TF as in MC. This is the output of the raw reader:
```
[781142:trd-datareader]: [11:18:50][INFO] TRD Translator Task run
[781142:trd-datareader]: [11:18:50][WARN] rdh bounds fail offsetToNext:8192 rdh 0x0x7fcba0826bc0 bufsize:11872 payload start: 0x0x7fdba19ac068 mHBFoffset32 9840
[781142:trd-datareader]: [11:18:50][ERROR] Error processing heart beat frame ... good luck
[781142:trd-datareader]: [11:18:50][WARN] rdh bounds fail offsetToNext:8192 rdh 0x0x7fcba0ab7340 bufsize:18464 payload start: 0x0x7fdba19ac068 mHBFoffset32 10464
[781142:trd-datareader]: [11:18:50][ERROR] Error processing heart beat frame ... good luck
[781142:trd-datareader]: [11:18:50][WARN] rdh bounds fail offsetToNext:8192 rdh 0x0x7fcba0ce76c0 bufsize:16768 payload start: 0x0x7fdba19ac068 mHBFoffset32 10424
[781142:trd-datareader]: [11:18:50][ERROR] Error processing heart beat frame ... good luck
[781142:trd-datareader]: [11:18:50][WARN] rdh bounds fail offsetToNext:8192 rdh 0x0x7fcba0dc75c0 bufsize:11040 payload start: 0x0x7fdba19ac068 mHBFoffset32 8272
[781142:trd-datareader]: [11:18:50][ERROR] Error processing heart beat frame ... good luck
[781142:trd-datareader]: [11:18:50][WARN] rdh bounds fail offsetToNext:8192 rdh 0x0x7fcba108d340 bufsize:16384 payload start: 0x0x7fdba19ac068 mHBFoffset32 10512
[781142:trd-datareader]: [11:18:50][ERROR] Error processing heart beat frame ... good luck
[781142:trd-datareader]: [11:18:50][WARN] rdh bounds fail offsetToNext:8192 rdh 0x0x7fcba10d9980 bufsize:11808 payload start: 0x0x7fdba19ac068 mHBFoffset32 10184
[781142:trd-datareader]: [11:18:50][ERROR] Error processing heart beat frame ... good luck
[781142:trd-datareader]: [11:18:50][WARN] rdh bounds fail offsetToNext:8192 rdh 0x0x7fcba117b940 bufsize:10848 payload start: 0x0x7fdba19ac068 mHBFoffset32 8424
[781142:trd-datareader]: [11:18:50][ERROR] Error processing heart beat frame ... good luck
[781142:trd-datareader]: [11:18:50][WARN] rdh bounds fail offsetToNext:8192 rdh 0x0x7fcba11c72c0 bufsize:14208 payload start: 0x0x7fdba19ac068 mHBFoffset32 9552
[781142:trd-datareader]: [11:18:50][ERROR] Error processing heart beat frame ... good luck
[781142:trd-datareader]: [11:18:50][WARN] rdh bounds fail offsetToNext:8192 rdh 0x0x7fcba121b2c0 bufsize:17248 payload start: 0x0x7fdba19ac068 mHBFoffset32 10728
[781142:trd-datareader]: [11:18:50][ERROR] Error processing heart beat frame ... good luck
[781142:trd-datareader]: [11:18:50][INFO] Digits: 73432, Tracklets: 8755, DataRead in: 3.002 MB, Rejected: 0.029 MB for TF 1 in 22 ms

```

2022-05-11 09:22 UTC, bazinski commented
@martenole my fst is failing to run, so based it off the contents of the raw files. Will come ask what I am doing wrong with fst.

2022-05-13 09:02 UTC, martenole requested changes
Reviewing with "Request changes" so that this does not get merged yet.

2022-05-13 09:07 UTC, bazinski commented
@martenole I am swapping between this and trying to understand the kr data oddities/mess/disfunction. I know the link length is getting calculated wrong somehow.

2022-05-16 09:40 UTC, f3sch commented on Detectors/TRD/simulation/src/Trap2CRU.cxx
>      unsigned int headerqpart = ((mTracklets[trackletoffset].getQ2() & 0x2f) << 2) + ((mTracklets[trackletoffset].getQ1() >> 6) & 0x3);
The charge calculation here is wrong.
I made a compatible PR #8836.

2022-05-24 20:08 UTC, bazinski commented
@martenole ok that also now sorts out the crash in your example, all my example fst work as well.
Will amend the summary at the top to reflect what this actually now does. Q stuff will come shortly but seperately.

2022-05-26 10:33 UTC, tdietel submitted a review, later dismissed
Looks good to me.

2022-05-26 10:35 UTC, tdietel reviewed
Actually, I just noticed @martenole's open change request. Has this been handled?

2022-05-26 10:43 UTC, martenole commented
> Actually, I just noticed @martenole's open change request. Has this been handled?

Not yet included here, but Sean told me that he got consistent results now. So once he updates the code I will check again and then we can hopefully merge this.
Currently there are inconsistencies between reading the raw files produced from converted simulated data and the simulated data itself

2022-05-26 10:45 UTC, bazinski commented
@martenole my plots similar to yours that are slightly less pretty, I am changing to do the comparison automatically. The digit fix also affects the tracklets. It was a mix up between linkid and hcid

2022-05-26 17:59 UTC, bazinski commented
After running fst, on the directory that was crashing for @martenole 
root [0] .x CheckTRDFST.C                                                                                                               
[INFO] 1 digits entries found                                                                                                           
[INFO] 1 tracklet entries found                                                                                                         
[INFO] 1 digits entries found                                                                                                           
[INFO] 1 tracklet entries found                                                                                                         
Info in <TCanvas::Print>: pdf file DigitsPerLayerAfterSim.pdf has been created                                                          
Info in <TCanvas::Print>: pdf file TrackletsPerLayerAfterSim.pdf has been created                                                       
Info in <TCanvas::Print>: pdf file DigitsPerLayerAfterReco.pdf has been created                                                         
Info in <TCanvas::Print>: pdf file TrackletsPerLayerAfterReco.pdf has been created                                                      
Digit Difference layer: 0 sim - reco : 0                                                                                                
Tracklet Difference layer: 0 sim - reco : 0                        
Digit Difference layer: 1 sim - reco : 0                                                                                                
Tracklet Difference layer: 1 sim - reco : 0                                                                                             
Digit Difference layer: 2 sim - reco : 0                                                                                                
Tracklet Difference layer: 2 sim - reco : 0                                                                                             
Digit Difference layer: 3 sim - reco : 0                                                                                                
Tracklet Difference layer: 3 sim - reco : 0                                                                                             
Digit Difference layer: 4 sim - reco : 0                                                                                                
Tracklet Difference layer: 4 sim - reco : 0                                                                                             
Digit Difference layer: 5 sim - reco : 0                                                                                                
Tracklet Difference layer: 5 sim - reco : 0                                                                                             
Info in <TCanvas::Print>: pdf file DigitsPerLayerDiff.pdf has been created                                                              
Info in <TCanvas::Print>: pdf file TrackletsPerLayerDiff.pdf has been created 
[DigitsPerLayerAfterSim.pdf](https://github.com/AliceO2Group/AliceO2/files/8781092/DigitsPerLayerAfterSim.pdf)
[DigitsPerLayerAfterReco.pdf](https://github.com/AliceO2Group/AliceO2/files/8781093/DigitsPerLayerAfterReco.pdf)
[DigitsPerLayerDiff.pdf](https://github.com/AliceO2Group/AliceO2/files/8781095/DigitsPerLayerDiff.pdf)

[TrackletsPerLayerAfterSim.pdf](https://github.com/AliceO2Group/AliceO2/files/8781096/TrackletsPerLayerAfterSim.pdf)
[TrackletsPerLayerAfterReco.pdf](https://github.com/AliceO2Group/AliceO2/files/8781097/TrackletsPerLayerAfterReco.pdf)
[TrackletsPerLayerDiff.pdf](https://github.com/AliceO2Group/AliceO2/files/8781099/TrackletsPerLayerDiff.pdf)

2022-05-26 21:18 UTC, davidrohr commented
@bazinski : What is the status of this? Do I understand correctly this should fix the problem of the digit2raw conversion? I am preparing a reference data set for synthetic runs, and would be good to have good TRD data.

When I merge this and I have existing TRD datasets, what do I need to rerun? Only `o2-trd-trap2raw`?

2022-05-26 21:22 UTC, bazinski commented
@davidrohr yes simply re run o2-trd-trap2raw  the command line option of -x 2 is now default so no change required to full_system_test.sh

2022-05-26 21:52 UTC, davidrohr commented
ok, I cannot verify that it is fully correct, but processing runs well on 3 128 orbit TFs after this and there are TRD tracks. Before there were no tracks. So merging this, since currently it is definitely broken.

2022-05-26 21:53 UTC, merged