DPL Analysis: Remove backward compability from combinations
AliceO2Group/AliceO2 pull request #8793
Opened 2022-05-11 13:14 UTC by saganatt

No use of string column names in block policies. BinningPolicy becomes obligatory.

2022-05-12 06:50 UTC, ktf requested changes
Could you check the error? it seems genuine, although I do not understand how it could be cc8 specific.

2022-05-12 07:00 UTC, saganatt commented
It seems cs8 used an older build of O2Physics. The error is caused by using old version of combinations with string.
But I removed that in https://github.com/AliceO2Group/O2Physics/pull/733/

2022-05-12 07:34 UTC, ktf commented
Ah, ok, maybe the test started before I updated the tag. Let me restart it.

2022-05-12 07:48 UTC, jgrosseo commented
> Ah, ok, maybe the test started before I updated the tag. Let me restart it.

cs8 does not build against master. see https://mattermost.web.cern.ch/alice/pl/5yeqd6wtzidyxrzh53w6b3qmea

2022-05-12 08:44 UTC, ktf commented
It should build now, since I merged the PR for the nightly build.

2022-05-13 08:59 UTC, saganatt commented
It passed cs8 check, could you merge, please? :-)

2022-05-13 09:08 UTC, jgrosseo approved these changes

2022-05-13 09:08 UTC, merged