Adds: PID cut configurables in the PID task
AliceO2Group/AliceO2 pull request #9215
Opened 2022-06-17 15:44 UTC by sbhawani

2022-06-20 13:24 UTC, wiechula requested changes

2022-06-20 13:24 UTC, wiechula commented on Detectors/TPC/qc/include/TPCQC/PID.h
> +                  float MaxdEdxTot = 70., float MinpTPC = 0.05, float MaxpTPC = 20., float MinpTPCMIPs = 0.45, float MaxpTPCMIPs = 0.55)
Naming:
```suggestion
  void setPIDCuts(int minnCls = 60, float absTgl = 1., float mindEdxTot = 10.0,
                  float maxdEdxTot = 70., float minpTPC = 0.05, float maxpTPC = 20., float minpTPCMIPs = 0.45, float maxpTPCMIPs = 0.55)
```

2022-06-20 15:01 UTC, sbhawani commented on Detectors/TPC/qc/include/TPCQC/PID.h
> +                  float MaxdEdxTot = 70., float MinpTPC = 0.05, float MaxpTPC = 20., float MinpTPCMIPs = 0.45, float MaxpTPCMIPs = 0.55)
Changed them now

2022-06-20 15:03 UTC, sbhawani commented
@wiechula @davidrohr and @shahor02, this PR is ready to be merged!, thanks

2022-06-20 17:01 UTC, wiechula approved these changes

2022-06-21 07:49 UTC, sbhawani commented
This error seems not related to  codes change in this PR apparently

2022-06-21 10:33 UTC, tklemenz commented
Yes, the error is unrelated. Can it be merged?

2022-06-22 11:42 UTC, wiechula commented
@davidrohr , @shahor02 , errors look unrelated. Can this be merged?

2022-06-22 11:49 UTC, merged