[EMCAL-565]: Add deployment-ready bad channel map code.
AliceO2Group/AliceO2 pull request #9620
Opened 2022-08-11 00:47 UTC by hjbossi

2022-08-11 00:59 UTC, hjbossi commented
@mfasDa @jokonig

2022-08-11 07:50 UTC, mfasDa requested changes
Few small changes needed.

Before merging:
1) rebase to upstream/dev
2) squash all new commits of the branch into one
3) Change the commit message, be more detailed about what you changed, use commit header as short description and the message body for a more detailed explanation.

2022-08-11 07:50 UTC, mfasDa commented on Detectors/EMCAL/calibration/include/EMCALCalibration/EMCALCalibExtractor.h
> +          auto meanPerCell = calibrationInformation.energyPerHitMap[index][cellID];
Be careful with variable names (`index` in this case) - not that you redefine existing names

2022-08-11 07:50 UTC, mfasDa commented on Detectors/EMCAL/calibration/run/runCalibOffline.cxx
> +
Needs new fair logger:

``` c++
 if (debugMode) {
      fair::Logger::SetConsoleSeverity("debug");
} else {
      fair::Logger::SetConsoleSeverity("info");
}
```

2022-08-11 07:50 UTC, mfasDa commented on Detectors/EMCAL/calibration/include/EMCALCalibration/EMCALChannelCalibrator.h
> +    LOG(info) << "Done with the calibraiton";
Please set the debug statements to `LOG(debug)`

2022-08-11 18:24 UTC, hjbossi commented
@mfasDa - the requested changes have been made. Should be good to merge.

2022-08-11 18:58 UTC, mfasDa approved these changes
Looks good

2022-08-13 14:04 UTC, mfasDa commented
Finally the CI finished - forwarding to @shahor02, @davidrohr or @chiarazampolli for final merge.

2022-08-15 07:57 UTC, shahor02 approved these changes

2022-08-15 07:57 UTC, merged